### ISSUE TITLE
Open reveal View controller when click a button

### ISSUE THREAD

**Issue by eburnay** [John-Lluch/SWRevealViewController#101]
Hello

I want to open the main view controller when click on a button in a ViewController.
When my application starts I open a ViewController with a button.
I want to click on that button and open the main view with the menu.

**Comment by ammoqq** [comment]
could you perhaps tell how to do that in swift ?
tried this, but doesnt work :
@IBAction func sideBarShow(sender: AnyObject) {
      
        let revealController = SWRevealViewController()
       
        revealController.rightRevealToggleAnimated(true) 
        
    }
I have a pangesturerecognizer added like this:
self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
and it works perfectly
