### ISSUE TITLE
iOS 7, 49px black bar just on the front view

### ISSUE THREAD

**Issue by gbrhaz** [John-Lluch/SWRevealViewController#103]
I'm working with storyboards. My hierarchy is as follows:

TabBarController -> SWRevealViewController -> NavigationController -> MyCustomController

The segues are set correctly.

I had a look in `layoutSubViews` in SWRevealView and on the first pass bounds is set correctly, but there's a second pass where `self.bounds` and the bounds of the front view are both -49px. The 49px is then just empty space and turns black. This doesn't happen with the rear view.

I tried just adding 40px to the bounds height in `layoutSubViews`, and it works until you use the pan gesture. The view loads correctly, and then when panning the black bar appears, and disappears again when the transition is complete. If you just reveal the rear view, it works fine still.

There is no "black bar" in the rear view ever.

EDIT: Actually, adding the 49px within the `hierarchycalFrameAdjustment:` method (outside of the if statement) pretty much fixes it for everything. Best band-aid ever.

**Comment by anthony-bernardo** [comment]
I had the same issue.

I add 49px to bounds.size.height: 

```
CGRect frame = CGRectMake(xLocation, 0.0f, bounds.size.width, bounds.size.height+49);
_frontView.frame = [self hierarchycalFrameAdjustment:frame];
```

in layoutSubviews

**Comment by iDevelopper** [comment]
#598

**Comment by iDevelopper** [comment]
I think this issue is because your tab bar is not translucent

**Comment by bdrelling** [comment]
What @xero88 recommended might be a good workaround, but this issue is really bad and I'm receiving it as well, still, years later. It only happens on `setFrontViewController`, not on `pushFrontViewController`.

Anyone recommend a library that is still being maintained that is similar? Maybe in Swift?

**Comment by iDevelopper** [comment]
I wrote another library: https://github.com/iDevelopper/PBRevealViewController.git as I think SWRevealViewController will not be updated anymore. The side views are showed above the main view controller.

**Comment by iDevelopper** [comment]
Otherwise there is the sample i wrote with SW:

[SWSecondView2.zip](https://github.com/John-Lluch/SWRevealViewController/files/401738/SWSecondView2.zip)

**Comment by iDevelopper** [comment]
Also if your tab bar is not translucent add:

```
    self.extendedLayoutIncludesOpaqueBars = true
```

in the viewDidLoad function of the controllers embedded in navigation controller: (or if you use storyboard, check Under opaques bars.

[SWSecondView2 2.zip](https://github.com/John-Lluch/SWRevealViewController/files/401900/SWSecondView2.2.zip)
