### ISSUE TITLE
Back Button not Working

### ISSUE THREAD

**Issue by adriangbut** [John-Lluch/SWRevealViewController#117]
I was looking for a method similar to [self.navigationController popViewControllerAnimated:YES]; Using the SWRevealViewController.

my problem is I go from View 1 to View 2 and I want to be able to press a back button and go back View 1. 

here is how I get to View 2

swSegue.performBlock = ^(SWRevealViewControllerSegue\* rvc_segue, UIViewController\* svc, UIViewController\* dvc) {

```
        UINavigationController* navController = (UINavigationController*)self.revealViewController.frontViewController;
        [navController setViewControllers: @[dvc] animated: YES ];
        [self.revealViewController setFrontViewPosition: FrontViewPositionLeft animated: YES];


    };
```

Any help would be great.

**Comment by ronak-ntech** [comment]
how to back previous ViewController ..?
