### ISSUE TITLE
Status Bar Won't Hide - iOS7

### ISSUE THREAD

**Issue by ghost** [John-Lluch/SWRevealViewController#131]
Hi there - Great component!  Having a bit of a showstopper issue for my app though.   

After implementing the SWRevealController my status bar no longer hides.   I have tried the following:
1.  Hiding via IB
2.  Hiding in my base view controller using

```
(BOOL) prefersStatusBarHidden
```
1.  Hiding using this code in viewdidload.

```
[self prefersStatusBarHidden];
[self performSelector:@selector(setNeedsStatusBarAppearanceUpdate)];
```

Prior to SWRevealController I was just using 2 above and everything work perfectly.  Any ideas?

**Comment by chrisharrison** [comment]
@perryao Yes, did you get it working in the end?

**Comment by Ricardo1980** [comment]
I have the problem of the navigation bar being resized. Any update? Thanks.

**Comment by jrejaud** [comment]
Has anyone found a solution regarding the navigation bar being resized?

**Comment by iDevelopper** [comment]
https://github.com/wicharek/UINavigationBar-FixedHeightWhenStatusBarHidden

And to hide the status bar : 

In your info.plist : 

Status bar is initially hidden = YES
View controller-based status bar appearance = NO

[SWRevealViewController-master.zip](https://github.com/John-Lluch/SWRevealViewController/files/156478/SWRevealViewController-master.zip)

Voilà!

**Comment by jrejaud** [comment]
@iDevelopper Thanks for the link, I will try this out.

@wicharek Is there a Cocoa pod for this library?

**Comment by wicharek** [comment]
@jrejaud nope, didn't had chance to add it. It is a very simple category though, just a single header and .m-file. Feel free to use it. However, note that although it should be working in general, in some cases it can cause a "jumpy" effect when showing/hiding status bar with animation.

P.S. Will add a podspec if you need it :)

**Comment by jrejaud** [comment]
No worries, I'll just copy and pasted it.
Cheers, Jordan Rejaud, EIT M.S. Carnegie Mellon University jrejaud@gmail.com jordanrejaud.com

On Fri, Mar 4, 2016 at 4:54 AM, Vitaliy Ivanov < notifications@github.com > wrote:
@jrejaud nope, didn't had chance to add it. It is a very simple category though, just a
single header and .m-file. Feel free to use it. However, note that although it
should be working in general, in some cases it can cause a "jumpy" effect when
showing/hiding status bar with animation.

P.S. Will add a podspec if you need it :)
