### ISSUE TITLE
 SWRevealViewController - UITabBarController - self.window.rootViewController

### ISSUE THREAD

**Issue by bobgodwinx** [John-Lluch/SWRevealViewController#133]
From apple documentation UITabBarController must be a rootViewController!!! Can you please explain if there is any solution to make SWRevealViewController a NON rootViewController in order to use the both of them...? because SWRevealViewController wants to be alway a rootViewController..!!! Help

**Comment by Soumya420** [comment]
How you have created the [ revealController ] is my SWRevealViewController what is your frontViewController. Please respond.
