### ISSUE TITLE
Disable FrontViewController when Rear is Displayed?

### ISSUE THREAD

**Issue by adamdehaven** [John-Lluch/SWRevealViewController#152]
I saw this solution: https://github.com/John-Lluch/SWRevealViewController/issues/92#issuecomment-24543131

When I implement the following code in one of my FrontViewControllers, it never gets called. Am I missing something? Or where should it go?

```
- (void)revealController:(SWRevealViewController *)revealController willMoveToPosition:(FrontViewPosition)position
{
    if(position == FrontViewPositionLeft) {
        self.view.userInteractionEnabled = YES;
    } else {
        self.view.userInteractionEnabled = NO;
    }
}

- (void)revealController:(SWRevealViewController *)revealController didMoveToPosition:(FrontViewPosition)position
{
    if(position == FrontViewPositionLeft) {
        self.view.userInteractionEnabled = YES;
    } else {
        self.view.userInteractionEnabled = NO;
    }
}
```

**Comment by abhisheknik23** [comment]
How do disable frontview view but keep enable toggelbutton in Slider table view class ??

 i implemented below method in SliderTableViewcontroller.m but its diable whole frontviewcontroller view and not able to access menu button.

#pragma mark - SWRevealViewController Delegate Methods
- (void)revealController:(SWRevealViewController *)revealController willMoveToPosition:(FrontViewPosition)position
  {
  
  if (position == FrontViewPositionRight){
  
  ```
  self.revealViewController.frontViewController.view.userInteractionEnabled = FALSE;
  ```
  
  }else if (position == FrontViewPositionLeft){
  
  ```
  self.revealViewController.frontViewController.view.userInteractionEnabled = TRUE;
  ```
  
  }
  }

**Comment by maksumon** [comment]
To disable front view controller and keep front view active to interact with tap/pan gesture to close the menu, add following block in MenuViewController:

```
-(void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];

    [self.revealViewController.frontViewController.view setUserInteractionEnabled:NO];
}

-(void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];

    [self.revealViewController.frontViewController.view setUserInteractionEnabled:YES];
}
```

And following block in each of the front view controller:

```
SWRevealViewController *revealController = [self revealViewController];
[revealController tapGestureRecognizer];
[revealController panGestureRecognizer];
```

**Comment by iDevelopper** [comment]
No!

**Comment by iDevelopper** [comment]
Only in the first front view controller:

SWRevealViewController *revealController = [self revealViewController];
[revealController tapGestureRecognizer];
[revealController panGestureRecognizer];

And in the delegate method:

WillMoveToPosition, it's OK

**Comment by maksumon** [comment]
@iDevelopper, you're right about following block, in only first front view controller:

```
SWRevealViewController *revealController = [self revealViewController];
[revealController tapGestureRecognizer];
[revealController panGestureRecognizer];
```

but if we put the following block in MenuViewController the we don't need to call delegate in each of front view controller to get the desired result:

```
-(void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];

    [self.revealViewController.frontViewController.view setUserInteractionEnabled:NO];
}

-(void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];

    [self.revealViewController.frontViewController.view setUserInteractionEnabled:YES];
}
```

Anyway, thanks for correcting me.

**Comment by iDevelopper** [comment]
Yes you're right, but you can adopt the protocol only on MenuViewController too and implement the delegate methods here! Or in a subclass of SWReveaViewController what I do all the time.

**Comment by maksumon** [comment]
@iDevelopper Thanks for you explanation.

**Comment by shashi-kiwi** [comment]
Hi,when i am trying to set tap and pan gesture both on front view controller,didselect of menuviewcontroller stop working.how can do the following things.
1. Slide menu through pan and tap both .
2. Disable userinteraction of front view controller ,when side menu is visible or only menu button of front view controller will be tapable.
3. menu view controller’s tableview will work fine.
Thanks in advance.

**Comment by iDevelopper** [comment]
1. In your first front view controller, in viewDidLoad, call tapGestureRecognizer and panGestureRecognizer methods of SW.

2. Adopt the SWRevealViewControllerDelegate protocol, in your rear view controller for example, and implement willMoveToPosition to set userInteractionEnabled to true or false on the front view controller regarding his position.

3. Menu view controller will work fine.

**Comment by shashi-kiwi** [comment]
Hi,
I have a fix issue with Swipe gesture in my app.Suppose i have following items in My Profile and My Orders.The Controller which is associated with My Profile has a button "Edit",which is pushing a controller named "ABC".
Now the issue is if i click on MyProfile cell in side menu  and then edit on My Profile Screen.Now on Swiping on ABC Controller did not show Side Menu .which is right.
But When Side menu is opened and i tap on front View controller and then click edit .The swiping on ABC controller opens side menu.Which is wrong.Same issue is going on with all the items of side menu and their successive screens.
Please help how to fix this.
Thanks in advance.

**Comment by iDevelopper** [comment]
You did not say us how you disabled the front view finally.

When you tap on front view, willMoveToPosition is fired and the userInteractionEnabled is set to true. So the pan gesture will work again. I suggest you check if the top view controller is ABC in willMoveToPosition delegate method.
