### ISSUE TITLE
Scroll to top issue

### ISSUE THREAD

**Issue by krazie99** [John-Lluch/SWRevealViewController#159]
Hi. 
First, I want to say Thank you.

Anyway, I have a question. 
I'm using SWRevealViewController with my project.
If I Touch (Tap) Status bar, scrolling to top is not working with SWReavel.

```
 for (UIView *subview in view.subviews) {
        if ([subview isKindOfClass:[UIScrollView class]]) {
            ((UIScrollView *)subview).scrollsToTop = isBool;
        }
}
```

This Code is not working ..... ;=(
Is there any solution to fix this?

**Comment by ypaulovich** [comment]
HI! 

This issue related, but badly described

i have both Rear and Front view controllers with UITableView
tapping on StatusBar scroll to top works only  for Front view controller

Issue is only for iPhone version both simulator and real devices 9.3+.

Thanks a lot!

**Comment by iDevelopper** [comment]
Hello,

![2016-07-08_10-09-56](https://cloud.githubusercontent.com/assets/1782450/16681366/86d6fb8a-44f4-11e6-896a-5c00c9a36edf.png)

**Comment by iDevelopper** [comment]
@ypaulovich , perhaps you can disable scrollsToTop of the front view when the rear is opened and enable it again when the rear view is closed...

**Comment by ypaulovich** [comment]
@iDevelopper    

already tried, 

```
- (void)viewDidLoad { //.....
 self.revealViewController.delegate = self;
}

- (void)revealController:(SWRevealViewController *)revealController didMoveToPosition:(FrontViewPosition)position {
        self.tableView.scrollsToTop = position == FrontViewPositionLeft;
}
```

Works fine for me, thanks for help!
