### ISSUE TITLE
Is there a way to slide the "right view controller" over the "front view controlller"?

### ISSUE THREAD

**Issue by joshdholtz** [John-Lluch/SWRevealViewController#160]
I'm looking to add a right sidebar menu that is semi-transparent to slide over the front view controller where the front view controller does not move.

I've looked through issues and examples but could not find a way. If you could point me in the correct direction that would be awesome.

**Comment by abduliOS** [comment]
Put below code on menu view controller its works for me

@interface SidebarTableViewController ()
{
    UIView\* coverView;
}

-(void) viewWillDisappear:(BOOL)animated
{
    [coverView removeFromSuperview];
    //[self.revealViewController.frontViewController.view setUserInteractionEnabled:YES];
    // get your window screen size

}
-(void) viewWillAppear:(BOOL)animated
{
    // get your window screen size
    CGRect screenRect = [[UIScreen mainScreen] bounds];
    //create a new view with the same size
    coverView = [[UIView alloc] initWithFrame:screenRect];
    // change the background color to black and the opacity to 0.6
    coverView.backgroundColor = [[UIColor blackColor] colorWithAlphaComponent:0.6];
    // add this new view to your main view
    [self.revealViewController.frontViewController.view addSubview:coverView];
   //   [self.revealViewController.frontViewController.view setUserInteractionEnabled:NO];

}
