### ISSUE TITLE
UITabBarController with a "reveal" button in title bar.

### ISSUE THREAD

**Issue by rawGH** [John-Lluch/SWRevealViewController#161]
I'm new at this, so please bare with me. It's been two days now, and I can't make this work.
Issue: Cannot put a "reveal" button on a TabBar (title bar, like on a normal navigation controller)
I've tried embedding tab bar items in navigation controller. They now have their own reveal button, but it appears in a new navigation bar, which is under the TabBar's controller title (so, it's not in the same line). The problem would also be solved if I could hide the TabBar's title bar... 
I also made a connection from my main Reveal View Controller to the TabBar, but it only works on a normal Navigation controller.

I've been using mostly storyboard so far.
1. Storyboard:
   ![screen shot 2013-12-17 at 11 37 36](https://f.cloud.github.com/assets/6204898/1763199/da6ced2c-6707-11e3-8e93-7532613eb790.png)
2. TabBar (reveal button on a new (child's) navigation bar):
   ![screen shot 2013-12-17 at 11 50 41](https://f.cloud.github.com/assets/6204898/1763235/3b855fda-6709-11e3-9fb5-afb2c976392d.png)
3. Should look like this (a normal view with navigation bar):
   ![screen shot 2013-12-17 at 11 51 02](https://f.cloud.github.com/assets/6204898/1763252/5c710a1e-6709-11e3-991f-4021714889f7.png)

**Comment by KheangSenghort** [comment]
Thanks rawGH, you code is very good when i used it for resolve with my problem.
