### ISSUE TITLE
Disable one side of SWRevealViewController for a specific ViewController

### ISSUE THREAD

**Issue by phamquochoan** [John-Lluch/SWRevealViewController#165]
Hi,

I want to disable `rightViewController` for a specific `UIViewController`.
So, I think the quickest way is adding some code to disable it in `viewWillAppear` and re-enable it again in `viewWillDisappear`. How ever, I don't know how to do it.

Can anyone help pls ? 
Thank you.

**Comment by invisibleBully** [comment]
Hi John, 

Great to meet you. So I have a UITabBarController that I have embedded with SWReveal ..works fine until you switch between tabs and try to slide in and out of the rear view(Side Menu). What could be the issue?

**Comment by iDevelopper** [comment]
Have you called  
`self.revealViewController().panGestureRecognizer()`
in the first front view controller?
