### ISSUE TITLE
Hide Status Bar (but keep spacing above Navigation Controller)

### ISSUE THREAD

**Issue by adamdehaven** [John-Lluch/SWRevealViewController#169]
I'd like to hide the device's status bar when the rear view loads, and then have it reappear when the front view loads.

I know I can accomplish this with `[[UIApplication sharedApplication] setStatusBarHidden:YES withAnimation:UIStatusBarAnimationSlide];`

However, when I use this method, the rear view moves upwards the 20px that represent s the status bar. I'd like to keep that 20px visible so that the views don't shift.

**Comment by ghost** [comment]
Set the top constraint to the `superview` rather than the `top layout guide`
