### ISSUE TITLE
Storyboard Example, State Restoration and Preservation, rear and front views?

### ISSUE THREAD

**Issue by rochbu** [John-Lluch/SWRevealViewController#171]
This is a question regarding state restoration and preservation and the SWRevealViewController. 

I've modified the storyboard sample (available here: https://github.com/rochbu/SWRevealViewController.git) for the basics of state preservation and restoration as per the available apple documentation.

For the SWRevealViewController the encode and decode methods are invoked as expected. What I can't figure out is why the encode and decode methods are not invoked on the other view controllers. They have restoration IDs in the storyboard. I tried modifying the sample to see if I can replicate the challenge I've had in my own code. The behaviour is the same.

For those curious you can try it out by building and running the app in the emulator. Home key to leave the app. Stop in Xcode to trigger the state preservation. You'll see the log message of preserving state for the SWRevealController but not the other controllers based on added logging.

If I have the AppDelegate method added (and uncommented)
- (UIViewController *)application:(UIApplication *)application viewControllerWithRestorationIdentifierPath:(NSArray *)identifierComponents coder:(NSCoder *)coder

it also only shows the restoration id of the SWRevealController.

I've also tried the restoration class approach in my app. It isn't in the above repository.

This would be a useful extension to the storyboard example (i.e. a working one).

If someone has it working or can steer me towards a solution I would be happy to finish updating the sample.

Thanks in advance,

Rob

**Comment by hamzaozturk** [comment]
Hi rochbu,
Did you find any solution to this problem?

**Comment by rochbu** [comment]
yes, it was a while ago.

Changes were made to the SWRevealViewController for state restoration and
preservation.

I don't recall updating the example to show it working fully. I don't know
if anyone else did.

If your still interested I could have a quick look at the example... on a
best effort basis timewise. the ios app I built and support is a side
endeavour.

**Comment by Manueldjz** [comment]
You could upload the example, or the solution you found, I have a view that is updated by a json, but once I go home and leave this does not maintain its status and recharged countless times

Thanks

**Comment by rochbu** [comment]
Want to confirm I understand the scenario.

    YourController:UIViewController
        YourView:UIView

I presume the view is getting initialized as part of the regular lifecycle.

* added an attribute to set when restoring state
* where the code runs to load the view with the json data check the attribute and determine if it should be called. **viewWillApear** or a method called by it
* in the **decodeRestorableStateWithCoder** set the attribute to true (restoring state)
* upon state restoration, the attribute is set indicating state has been restored and in **viewWillApear** you'll know not to make the json call

Also checked out, loaded and ran the latest example, looks ok**. if I've missed something, let me know. If I have the scenario correct and it isn't clear I can add something to the example.

**first run log:**
    2015-04-01 07:02:25.460 RevealControllerStoryboardExample2[1338:28304] Warning: Unable to create restoration in progress marker file

**triggered state preservation.**
    RevealControllerStoryboardExample2[1338:28304] -[MenuViewController encodeRestorableStateWithCoder:]
    2015-04-01 07:03:28.436 RevealControllerStoryboardExample2[1338:28304] -[MapViewController encodeRestorableStateWithCoder:]

**second run log:**
    2015-04-01 07:04:46.364 RevealControllerStoryboardExample2[1358:29931] -[MenuViewController decodeRestorableStateWithCoder:]
    2015-04-01 07:04:46.369 RevealControllerStoryboardExample2[1358:29931] -[MapViewController decodeRestorableStateWithCoder:]
    2015-04-01 07:04:46.369 RevealControllerStoryboardExample2[1358:29931] -[MenuViewController applicationFinishedRestoringState]
    2015-04-01 07:04:46.369 RevealControllerStoryboardExample2[1358:29931] -[MapViewController applicationFinishedRestoringState]

**Comment by Manueldjz** [comment]
hi bro! actually im working with  2.1 version  and my project was going well, but update the class to use your changes (preservation & restoration) , and now does not work in my dynamic view, I try to implement the restoration of state in my "NTCviewController"

I hope you can help me

this is my code (Xcode project) 
this is the best way I can represent, because my native language is not English :(

https://www.dropbox.com/s/m9tjy0bev31er7n/DitcoAppProyect-4.4.zip?dl=0

**Comment by rochbu** [comment]
please provide steps to recreate the problem using the code you provided.
include the state you want preserved and restored.

FYI:

Only iPhone4.storyboard provided. I worked around it.
No controller named NTCviewController however there is a
NtcTableViewController,
please confirm this is the one your trying to add state restoration to.

**Comment by Manueldjz** [comment]
Yes my project only work on iphone 4 inches for the moment, you're right is "NTCTableViewController"
 (this is the first window on the app) sorry

The application works fine at first, but when you open the menu and selected "news" the application crashed

in version 2.1 of swrevealviewcontroller, the application works well all time, connected the cell "news" with "NTCTableViewController" and using segue class "SWRevealViewControllerSegue" and all was well..... but in the new class (2.3) connect the cell "news" with "SWRevealViewControllerSeguePushController" ....Am I wrong? 

but the biggest problem is when you select on the menu the cell "news"... the view content  (NTCTableViewController) reloaded again and again,  I want to preserve the state of the NTCTableViewController.. so when in and out of it, the information (Json) is not updated constantly

Thanks for your time and patience
I really hope you can help me 


this is my project with the old class (2.1)

https://www.dropbox.com/s/b1p1poqotm7f5p7/the%20old%20class.zip?dl=0

not think it helps much, but here "news" works perfectly when entering and leaving on menu....
and understands that in and out of "news" data is constantly updated and do not preserve their status

**Comment by rochbu** [comment]
State preservation/restoration is not utilized in this sample code.

the old code does not like the menu items to any views. It works.
the new code links the menu items to the UIViews with SWRevealController
segues. Not sure one should be using the swrevealcontroller custom segues
for this window linkage.

by swiping and revealing the menu your starting at the 'top' again.
which is the issue in my opinion.

not an area of expertise for me.
