### ISSUE TITLE
Setting the initial segue (sw_front) dynamically

### ISSUE THREAD

**Issue by palmerc** [John-Lluch/SWRevealViewController#183]
I've been trying some strategies for setting up the sw_front segue dynamically on start.

Currently I have set the 'menu' controller as both the front and rear, and I'm trying to immediately segue to the correct view controller. The reason being that when entering the reveal navigation the first view controller needs to be determined as it enters the Reveal Navigation.
![screen shot 2014-01-24 at 10 18 02](https://f.cloud.github.com/assets/533118/1993372/7db3cf26-84d8-11e3-92be-da2f2d505968.png)

As you can see along the bottom there is a double custom segue. So on initial load I need to segue to the correct controller and then subsequently the normal navigation. Can you provide any idea how I might do this?

**Comment by vipinfalke** [comment]
I have a login screen and after that SWRevelViewController. So I want to change the the first screen (sw_front) after login depending upon some conditions. Will you please help?

**Comment by jogshardik** [comment]
Hello @vipinfalke  you can do that what you need to make changes in SWRevealViewController.h two methods and add your custom segue identifier in that also.

I have also want to do the same you want to do that is work for me and hope it will definitely work for you as well.
Have a happy coding.

#pragma mark - SWRevealViewControllerSegueSetController segue identifiers

NSString * const SWSegueRearIdentifier = @"sw_rear";
NSString * const SWSegueFrontIdentifier = @"sw_front";
NSString * const SWSegueRightIdentifier = @"sw_right";
NSString * const SWSegueCustomSegue = @"sw_custom";

And then change the following method according to your segue and set the frontviewcontroller

- (void)perform
{
    SWRevealControllerOperation operation = SWRevealControllerOperationNone;
    
    NSString *identifier = self.identifier;
    SWRevealViewController *rvc = self.sourceViewController;
    UIViewController *dvc = self.destinationViewController;
    
    if ( [identifier isEqualToString:SWSegueFrontIdentifier] )
        operation = SWRevealControllerOperationReplaceFrontController;
    
    else if ( [identifier isEqualToString:SWSegueRearIdentifier] )
        operation = SWRevealControllerOperationReplaceRearController;
    
    else if ( [identifier isEqualToString:SWSegueRightIdentifier] )
        operation = SWRevealControllerOperationReplaceRightController;
    
    else if ( operation != SWSegueCustomSegue )// your condition
        [rvc _performTransitionOperation:operation withViewController:dvc animated:NO];

    if ( operation != SWRevealControllerOperationNone )
        [rvc _performTransitionOperation:operation withViewController:dvc animated:NO];

}

- (void)loadStoryboardControllers
{
    if ( self.storyboard && _rearViewController == nil )
    {
        //Try each segue separately so it doesn't break prematurely if either Rear or Right views are not used.
        @try
        {
            [self performSegueWithIdentifier:SWSegueRearIdentifier sender:nil];
        }
        @catch(NSException *exception) {}
        
        @try
        {
            [self performSegueWithIdentifier:SWSegueFrontIdentifier sender:nil];
        }
        @catch(NSException *exception) {}
        
        @try
        {
            [self performSegueWithIdentifier:SWSegueRightIdentifier sender:nil];
        }
        @catch(NSException *exception) {}

        @try
        {
            [self performSegueWithIdentifier:SWSegueCustomSegue sender:nil];
        }
        @catch(NSException *exception) {}
    }
}

**Comment by vipinfalke** [comment]
Thank you @jogshardik for your response.. But I have already implemented it using some different way..

**Comment by chawlatarika5** [comment]
@vipinfalke Can you please add the way you used to get your use case working. I have the same use case. I would really appreciate.

**Comment by iDevelopper** [comment]
@jogshardik , I think it is better to subclass SWRevealViewController to do this.

@chawlatarika5  , use setFontViewController:animated:
