### ISSUE TITLE
RIght side menu

### ISSUE THREAD

**Issue by mchirino89** [John-Lluch/SWRevealViewController#185]
You mention this can be displayed both from left and right side, but i've spent time both trying and searching a way to display it at the right side (default behavior is from left) without having success. I tried to replace the segue name with "sw_right" instead "sw_rear" and the animation didn't fire. 

Could you give me a heads up about this please?

**Comment by omidkh68** [comment]
hey guys, I don't know how to change left side menu to right side, I don't know Objective-c!
Help me Please :)
