### ISSUE TITLE
automaticallyAdjustsScrollViewInsets setting ignored

### ISSUE THREAD

**Issue by dppeak** [John-Lluch/SWRevealViewController#187]
I came across an issue where the automaticallyAdjustsScrollViewInsets setting for my tableview controller was not being honored.  I found the issue was with the following code in the _deployForViewController method:

```
if ( [controller respondsToSelector:@selector(automaticallyAdjustsScrollViewInsets)] && [controllerView isKindOfClass:[UIScrollView class]] )
{
    BOOL adjust = (BOOL)[controller performSelector:@selector(automaticallyAdjustsScrollViewInsets) withObject:nil];

    if ( adjust )
    {
        [(id)controllerView setContentInset:UIEdgeInsetsMake(statusBarAdjustment(_contentView), 0, 0, 0)];
    }
}
```

adjust was always equal to YES.

I fixed the issue by removing the adjust attribute and just referencing controller.automaticallyAdjustsScrollViewInsets  as such:

```
if ( [controller respondsToSelector:@selector(automaticallyAdjustsScrollViewInsets)] && [controllerView isKindOfClass:[UIScrollView class]] )
{
    if ( controller.automaticallyAdjustsScrollViewInsets )
    {
        [(id)controllerView setContentInset:UIEdgeInsetsMake(statusBarAdjustment(_contentView), 0, 0, 0)];
    }
}
```

**Comment by skumancer** [comment]
I'm having this problem, my Swift application always returns YES for this, as the selector is never called, so the adjustment is always made.
