### ISSUE TITLE
panGestureRecognizer used in another view controller

### ISSUE THREAD

**Issue by Xcode-RankPrivate** [John-Lluch/SWRevealViewController#193]
Hi, i am using storyboards and in the view that i want to implement the sidebar, when i use "[self.view addGestureRecognizer: self.revealViewController.panGestureRecognizer];"  in 'ViewDidLoad', i get an error without the view being loaded but when i put the code in 'ViewDidAppear', the view loads but right away the app terminates with the same error.

The error: Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

![screen shot 2014-02-12 at 15 50 13](https://f.cloud.github.com/assets/6659204/2146578/1cc0a6d6-93c3-11e3-8602-1a185b706827.png)

when i implement the line of code in the 'Main View Controller', it did work. Now i am wanting to implement the sidebar to the 'Pictures Collection Controller'. What could have been the problem?

My other question that could help is should i link the 'Login Controller' with the second 'Navigation Controller' using a modal segue or a custom segue with SWRevealViewController as the class of the custom segue?

And for your information, i used a second navigation controller so that i could do a push segue in the 'Pictures Collection Controller'.

Thanks

**Comment by bobbydank** [comment]
Outstanding fix. Thank you very much!
