### ISSUE TITLE
Memory Issues - Pushing a new navigation controller each time 

### ISSUE THREAD

**Issue by sairasamdani** [John-Lluch/SWRevealViewController#224]
Hi John,

Lets state it by an example,  I ran "RevealControllerExample" It started with a front and a rear navigation controllers. I click on Map View Controller. Push another navigation controller and it looks good. Now I click back on Front Controller from menu. And I check if its not the top controller so push it again. Front View Controller pushed at start will be somewhere down in lane but still resided in memory and every time I'll do this. Select Front. Slide Go to map. Slide. Again select front and so on. Won't it increase my memory consumption? As all these navigation controllers are residing in memory.

Please correct me if I am wrong.

Best Regards

**Comment by marcoreyesc** [comment]
Hi, 
I'm new in iOS development, may be I'm wrong but I think the word push in the method's name is related to a stack, so if the method pushFrontViewController doesn't push on a stack, it could be a good idea to change its name.

**Comment by iDevelopper** [comment]
Not necessarily  ! Example SpriteKit -> SKTransition -> pushWithDirection:duration:

**Comment by iDevelopper** [comment]
And to answer to the original question, just save in a property the view controller's instance and reuse it to avoid instantiate it again each time!
