### ISSUE TITLE
How to hide the keyboard

### ISSUE THREAD

**Issue by rishadali** [John-Lluch/SWRevealViewController#232]
Hello, It is a very nice tool but I am have a problem in it.  I have a textfield in a scene, if I swipe left when the keyboard is open, the menu appears but it does not dismiss the keyboard. How do I dismiss keyboard on left swipe? I have tried

UISwipeGestureRecognizer *swipe = [[UISwipeGestureRecognizer alloc] initWithTarget:self action:@selector(dismissKeyboard)];
swipe.direction = UISwipeGestureRecognizerDirectionLeft;
[self.view addGestureRecognizer:swipeRecognizer];

-(void)dismissKeyboard
{
    [self.textField resignFirstResponder];
}
but it does not work, I think because I am already using a panGestureRecognizer for revealViewcontroller i.e. [self.view addGestureRecognizer:self.revealViewController.panGestureRecognizer];

I am also using UITapGestureRecognizer but it only works for tap not for swipe. I hope there is a very simple solution for this problem. Can you please help?

Thanks

**Comment by kbirand** [comment]
@rishadali Can you paste the code that you solved the problem with .. thank you.
