### ISSUE TITLE
Navigate Programatically

### ISSUE THREAD

**Issue by Ankish** [John-Lluch/SWRevealViewController#237]
Hey is there a way to navigate programatically . Explicitly  , A user need to click the drawer and click the row to navigate to that view controller. If i want to programatically navigate the  user from one tab to another , how can i do that.

**Comment by ryanhomer** [comment]
pushFrontViewController:animated: works for me but does not animate. I'm doing this in Swift and passing animated:true. The comments in the code states that it should perform the default animation (move to rightmost, replace, move back). Any ideas?

**Comment by Ankish** [comment]
I am sorry i dont remember this issue now. Its been more than a year i reported. Anyways thanks!
