### ISSUE TITLE
How to push and popup the SWRevealViewController from UIViewController

### ISSUE THREAD

**Issue by sudalainaz** [John-Lluch/SWRevealViewController#244]
Hi John,

I am using SWRevealViewController in my project.This Reveal Controller is easy to worked in my project.Now my client want to change the RevealController to next page.I need  this format,when i open the application first i want to display front page,in that front page,tap the button it is push to SWReveal Controller,it works fine.From that reveal page,i want to pop up to front page,it doesn't work for me.Here i attached my screen shot.

Thanks
Sudalai
![ios simulator screen shot 06-may-2014 11 42 09 am](https://cloud.githubusercontent.com/assets/1997803/2886484/fed22d06-d4e6-11e3-9273-5dc27331dfbc.png)
![ios simulator screen shot 06-may-2014 11 42 22 am](https://cloud.githubusercontent.com/assets/1997803/2886485/fed32512-d4e6-11e3-96d5-2ba2f3ee29b4.png)

**Comment by alirezanmz** [comment]
i cant back to viewcontroller on swrevealviewcontroller please help me!!!!

**Comment by iDevelopper** [comment]
Your question does not mean anything ! Can you be more specific if you want an answer? What did you try? What do you want to do?

**Comment by johnlpm** [comment]
Hi John, How can I use the menu without going to the other controller instead calling a function in the current view

**Comment by iDevelopper** [comment]
Retrieve your front view controller:

let yourController = reveaController().frontViewController as? YourController

yourController.myFunction()

**Comment by johnlpm** [comment]
Thanks.. but how i can implement it on objective-c

**Comment by iDevelopper** [comment]
The same!

YourController *yourController = (YourController *)self.revealViewController.frontViewController;
[yourController myMethod];

if yourController is embedded in a navigation controller:

UINavigationController *nc = (UINavigationController *)self.revealViewController.frontViewController;
YourController *yourController =  (YourController *)nc.topViewController;
[yourController myMethod];

**Comment by johnlpm** [comment]
Thanks Sir.. It Works,

I've added [self.revealViewController revealToggle:nil]; at the top of the code to reveal the previous controller that should perform the function..

Thanks :)
This is my first time to ask question and it really helps..

**Comment by Comrade-SwiftUI** [comment]
let destination = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SubCategoryVC")
        self.revealViewController().pushFrontViewController(destination, animated: true)


this code is not working properly ...plz guid me how to back previous controller

**Comment by iDevelopper** [comment]
> this code is not working properly

What is the issue?

**Comment by Comrade-SwiftUI** [comment]
sir i have attache my demo program. can you check my code sir ?

**Comment by Comrade-SwiftUI** [comment]
let destination = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SubCategoryVC")
        self.revealViewController().pushFrontViewController(destination, animated: true)

**Comment by Comrade-SwiftUI** [comment]
![screen shot 2017-12-06 at 12 18 02 pm](https://user-images.githubusercontent.com/21832611/33648379-8bc57c6c-da7f-11e7-8a9a-8d987b6a9f14.png)

**Comment by iDevelopper** [comment]
So destination is nil, check the identifier in the storyboard.

**Comment by Comrade-SwiftUI** [comment]
yes, sir i have give the same name  subCategoryVC

**Comment by Comrade-SwiftUI** [comment]
![screen shot 2017-12-06 at 12 40 31 pm](https://user-images.githubusercontent.com/21832611/33649140-aefc5842-da82-11e7-8988-cdc78875880e.png)

**Comment by iDevelopper** [comment]
If you put a breakpoint on this line, what is nil? destination or self.revealViewController()?

**Comment by iDevelopper** [comment]
And I can't see you demo project anywhere!

**Comment by SaadNT** [comment]
is there any method to pop the front view controller?? like there is a method "pushFrontViewController" : self.revealViewController().pushFrontViewController(vc, animated: true)
I want the pop method for this. My scenarios is I have MenuVC as RearVC. and FrontVC is a NavigationVC. 
![git](https://user-images.githubusercontent.com/37143643/42454351-b7675c28-83a8-11e8-8fd8-0bf4a1161802.png)

**Comment by Comrade-SwiftUI** [comment]
Set the Navigation controller in Root controller and access in all screen

**Comment by SaadNT** [comment]
@786BhaveshChavda it will cause another issue :(

**Comment by SaadNT** [comment]
![img_17389cf98aa8-1](https://user-images.githubusercontent.com/37143643/42455380-84591940-83ab-11e8-9934-1f57ef51f9d6.jpeg)
@786BhaveshChavda

**Comment by iDevelopper** [comment]
```
            // Push with front's navigation controller to have a back button to it.
            UINavigationController *nc = [[UINavigationController alloc] initWithRootViewController:_frontViewController];
            [self.revealViewController setFrontViewController:nc animated:NO];
            [nc pushViewController:_otherViewController animated:NO];
            [self.revealViewController setFrontViewPosition:FrontViewPositionLeft animated:YES];
```

**Comment by SaadNT** [comment]
@iDevelopper Thanks, but thats not what I need. I need the flow to be like twitter ios app. Where when you touch any item from side menu, it feels like its pushing(PUSH) a view controller, and then on back button touch event of the pushed view controller it feels like its popping(POP) back.

**Comment by iDevelopper** [comment]
It is exactly what the code does.

**Comment by iDevelopper** [comment]
I have just retrieved a sample I wrote in Swift for this purpose:
[SWHomePushSwift.zip](https://github.com/John-Lluch/SWRevealViewController/files/2179153/SWHomePushSwift.zip)

**Comment by SaadNT** [comment]
@iDevelopper let me check that.. BTW, ty

**Comment by SaadNT** [comment]
is it the above project  SWHomePushSwift.zip an extension of SWRevealViewController?? I am talking about the implementation. What if I replaced my current files of SWRevealViewController with the above files??

**Comment by SaadNT** [comment]
@iDevelopper thanks a lot man.. 👍

**Comment by iDevelopper** [comment]
No, it is not an extension at all.

**Comment by SaadNT** [comment]
actually the base for this is to push any VC from menu VC using the navigation controller of the front VC of SWRevealViewController, which will eventually Push from front VC.  @iDevelopper

**Comment by iDevelopper** [comment]
You can write an extension that looks like that:

```
import Foundation
import UIKit

extension SWRevealViewController {
    func pushViewController(_ viewController: UIViewController, animated: Bool) {
        
        var pushingController: Any?

        if frontViewController is UINavigationController {
            if (frontViewController as! UINavigationController).topViewController != viewController {
                pushingController = frontViewController
            }
        }
        else if let navigationController = frontViewController.navigationController {
            pushingController = navigationController
        }
        
        if pushingController != nil && !(viewController is UINavigationController) {
            (pushingController as! UINavigationController).pushViewController(viewController, animated: false)
            revealToggle(animated: animated)
        }
        else {
            pushFrontViewController(viewController, animated: animated)
        }
    }
}
```

[SWHomePushSwift 2.zip](https://github.com/John-Lluch/SWRevealViewController/files/2181478/SWHomePushSwift.2.zip)
