### ISSUE TITLE
how to use   SWRevealViewController with splitviewcontroller in storyboard apps

### ISSUE THREAD

**Issue by prasadgdv** [John-Lluch/SWRevealViewController#249]
Hi I want to use SWRevealViewController with my splitview controller. I am trying to add SWRevealViewController to master view but while adding my master view size is changing from 320X768 to 1024X768. Please any one could suggest me how to achieve this.

**Comment by thomers** [comment]
Have a look here: https://github.com/John-Lluch/SWRevealViewController/issues/518
