### ISSUE TITLE
UIBarButtonItem : call automatically the action revealToggle: 

### ISSUE THREAD

**Issue by micdam69** [John-Lluch/SWRevealViewController#262]
Hello, 

I set up (in viewDidLoad) with the class SWRevealViewController both the Left and Right button 
(/ / Change button color 
     _sidebarButton.tintColor = [UIColor colorWithWhite: 0.1f alpha: 0.9f]; 
     _rightsidebarButton.tintColor = [UIColor colorWithWhite: 0.1f alpha: 0.9f]; 
    
     / / Set the side bar button action. When it's tapped, it'll show up the sidebar. 
     _sidebarButton.target = self.revealViewController; 
     _sidebarButton.action = @ selector (revealToggle :); 

     _rightsidebarButton.target = self.revealViewController; 
     _rightsidebarButton.action = @ selector (rightRevealToggle :); 

     / / Set the gesture 
     [self.view addGestureRecognizer: self.revealViewController.panGestureRecognizer]; 
) 
What I would do is call automatically the associated action (revealToggle:) the right button using a boolean property of my view. How can I do? 
thank you very much
Michele

**Comment by Deepal-axs** [comment]
SWRevealViewController *revealController = self.revealViewController;
    [revealController revealToggleAnimated:YES];
