### ISSUE TITLE
Custom UIButton and revealToggle not working

### ISSUE THREAD

**Issue by slhodson969** [John-Lluch/SWRevealViewController#287]
I had setup the `SWRevealViewController` as such in my `AppDelegate`

``` Objective-C
ETContainerViewController *frontViewController = [ETContainerViewController new];

SWRevealViewController *revealViewController = [[SWRevealViewController alloc]
        initWithRearViewController:nil
               frontViewController:frontViewController];
revealViewController.delegate = self;

ETSettingsViewController *rightViewController = [ETSettingsViewController new];

revealViewController.rightViewController = rightViewController;

self.viewController = revealViewController;

[self.window setRootViewController:self.viewController];
```

I have then setup my button in the `FrontViewController` as so:

``` Objective-C
SWRevealViewController *revealViewController = [self revealViewController];

UIButton *settingsButton = [UIButton buttonWithType:UIButtonTypeCustom];
[settingsButton setImage:[UIImage imageNamed:@"settings_icon"] forState:UIControlStateNormal];
[settingsButton setImage:[UIImage imageNamed:@"settings_icon_active"] forState:UIControlStateHighlighted];
[settingsButton setImage:[UIImage imageNamed:@"settings_icon_active"] forState:UIControlStateSelected];
[settingsButton addTarget:revealViewController action:@selector(revealToggle:) forControlEvents:UIControlEventTouchUpInside];
```

However, when I click the button, nothing happens. With a little debugging I managed to see it actually gets to the `revealToggle` function and performs it but on screen, nothing happens.

Any ideas or something silly i'm doing wrong?

**Comment by tvich1** [comment]
I am not much sure about Objective-C but in swift it can be done in following way:

In your button action, write following code;

sender.addTarget(revealViewController(), action: "revealToggle:", forControlEvents: UIControlEvents.TouchUpInside)
        revealViewController().rightViewRevealWidth = 150
        view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())

Reference:-> [How to open SWRevealViewController from a UIButton](http://swiftforums.org/forum/third-party-libraries-aa/swrevealviewcontroller/47-how-to-open-swrevealviewcontroller-from-a-uibutton)

**Comment by spark0128** [comment]
on swift, I'm getting fatal error: unexpectedly found nil while unwrapping an Optional  from:

sender.addTarget(revealViewController(), action: "revealToggle:", forControlEvents: UIControlEvents.TouchUpInside)
revealViewController().rightViewRevealWidth = 150
view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())

**Comment by iDevelopper** [comment]
```
@IBAction func reveal(sender: AnyObject) {
    revealViewController().revealToggle(sender)
}
```

[SWStaticRear.zip](https://github.com/John-Lluch/SWRevealViewController/files/321614/SWStaticRear.zip)

**Comment by spark0128** [comment]
Thanks for the file. Made me realise that I forgot to make SWRevealViewController as the initial vc. :)
