### ISSUE TITLE
SWRevealViewController with UITabbarController  and the tabs and Side menu remain open all the time.

### ISSUE THREAD

**Issue by krkamani** [John-Lluch/SWRevealViewController#289]
Hi , 

I want to use this SWRevealViewController with UITabbarController, and I want to have the tabs (bottom) to be avilable all the time for quick access to popular functions and the Side menu is present so that the user can open and close depends on the requirement.

Currenly I have login -> SWRevealViewController  ->  Two Controllers (sw_front - Tab bar) & (sw_rear - Table ) . Tab bar have two tabs  and rear view i.e side Menu have two view now.   The links in both are different and I want to see the link to menu ( side bar) even from tab bar & when I click the side menu item , The tab bar needs to there . 

Currently when I click on the side item the tab bar is closing and no way I could get to the tab bar.

Could you please help me how can I have tab bar remain all the time and the link to side manu all the time  

Here is the current way I have in my code

NOTE :- No link between the side menu and tab , thats is the reason I want both to be available all the time  

![untitled](https://cloud.githubusercontent.com/assets/8119517/3630805/6f47acee-0eaf-11e4-98e8-2b6d88457833.png)

**Comment by Sudarshan33** [comment]
@krkamani 

u did this please tell me to do this task

**Comment by ghost** [comment]
Hello Mr. @John-Lluch I'm implementing exactly the same above structure, I've followed example2 with storyboard. Its working fine exactly what just wanted.
But with a small issue.
"PanGestureNotWorking Properly"
Steps To Reproduce. 
When app launches with First tabbar item as selected Gesture Works Great.
Now Select Second Tab Gesture Works Again Properly.
Now Reselct the First Tab Gesture fails to work but RevealButton action is working.

Conclusion. the last tab which is being selected working properly with gestures. previous selected tabs are not working with gestures.

I've taken BaseViewController as Parent View Controller For All Tabbed ViewControllers. There I've Implemeted in View Did Load

  if (menuButton != nil )
        {
            if self.revealViewController() != nil
            {
                menuButton.target = self.revealViewController()
                menuButton.action = "revealToggle:"
                self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
                self.navigationController?.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
            }
        }

 Please Assist Me to Fix this bug.
@krkamani did you find this issue in your App?

**Comment by kerimsari** [comment]
Hi @krkamani could you please share how you did (if you can post code sample i would be gratefull) to implement the solution you wanted. I need the same solution. I want the tab bar and side menu appears in all view controllers.

**Comment by kerimsari** [comment]
Hi,

I found the solution from the below link. For those who still try to get some solution, download the file below to get it work.

https://github.com/John-Lluch/SWRevealViewController/files/275828/SWTabBarSwift2.zip
