### ISSUE TITLE
Problem with Navigation Bar Item position. (Swift,  XCode 6 b3). This message include GIF 1Mb

### ISSUE THREAD

**Issue by tsybanov** [John-Lluch/SWRevealViewController#290]
Hi. I have problem with navigationBarItem position when work with SWRevealViewController and Swift.

When I call some Navigation View Controller (first page of Navigation VIew Controller) from menu (SWRevealViewController), Navigation Bar Item on this page move so close to the left. When I've pressed home button and open application - it is move to correctly position. When I've try call something again from menu (SWRevealViewController) Navigation Bar Item move to left so close again.

Please, give some advice for solve this problem.

Here gif for best description:
![](http://i66.fastpic.ru/big/2014/0720/99/b61eb76108c139e7b3cc13466c5d4f99.gif)

This is real effect (not montage). Button moves after open application again.

**Comment by Gregusse** [comment]
@MaximDroy could contact me cause I have some trouble with SWReveal and swift?
Thx

**Comment by kumararvind** [comment]
I am getting the same issue. I have spend around 2 days But I did'nt get Solution. I am using Objective C Language with Xcode 8.1, Please share your thought how I can resolve this issue.
Thanks,

![simulator screen shot 06-dec-2016 3 48 53 pm](https://cloud.githubusercontent.com/assets/7710425/20921749/847773e4-bbcb-11e6-8aef-224b369ad282.png)

**Comment by iDevelopper** [comment]
I wrote a lot of samples with SWRevealViewController in Swift and Objective-c. I have never seen that! Could you upload a sample reproducing this issue?

**Comment by kumararvind** [comment]
Thanks for your reply
Its not possible to create Sample for now I will share later when I will get time.
In my Project I am using Custom Tabbar, It happen When I tap any tabbbar and then click on Left Menu button and then options of Menus Listed in Reveal 
after that Left and Right bar button offset changed as I Shared Screenshots.

**Comment by iDevelopper** [comment]
Is the custom tab bar controller is your? Otherwise where can I find it?

**Comment by kumararvind** [comment]
here is the my custom Tabbar code link:
https://drive.google.com/file/d/0B6u1v7u3YkatcHlTbEJCSldwQWs/view?usp=sharing

**Comment by kumararvind** [comment]
// Calling Method 
HelpViewController *helpTaskViewController = GET_VIEW_CONTROLLER(kHelpViewController);
  [self push:helpTaskViewController];

Here is the SWReveal method
#pragma mark - Push Using SWRevealViewController
-(void)push:(UIViewController *)controller
{
    SWRevealViewController *revealController = self.revealViewController;
    UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:controller];
    
   [revealController pushFrontViewController:navigationController animated:YES];
}

**Comment by iDevelopper** [comment]
Ok I will try a test

**Comment by iDevelopper** [comment]
Don't have the macros GET_VIEW_CONTROLLER_STORYBOARD, GET_VIEW_CONTROLLER

**Comment by kumararvind** [comment]
#define GET_VIEW_CONTROLLER(viewController) [self.storyboard instantiateViewControllerWithIdentifier:viewController]

static NSString *const kHelpViewController               = @"HelpViewController";
