### ISSUE TITLE
Bug with iOS 8. Blank menu (EDITED: found the problem)

### ISSUE THREAD

**Issue by tsybanov** [John-Lluch/SWRevealViewController#300]
Today I got bug with iOS 8.0 simulator. I don't change anything around SWRevealViewController and the code and right know instead menu I see blank menu

![](http://i67.fastpic.ru/big/2014/0801/fe/51b9a9879399be6c9e4d1ab8e1eb3dfe.gif)

But it should be

![](http://i68.fastpic.ru/big/2014/0801/b3/f2bf99cc8e19ec1df63b7507d8e13eb3.gif)

Problem has simulator with iOS 8.0. With simulator and real device with iOS 7.0 everything works good.

Strange this because it appeared for no apparent reason. I almost did not change anything in the code and early it's work with iOS 8.0 simulator.

**Comment by joarleymoraes** [comment]
Hey guys,

I'm facing the issue described here for iPad only, but both on device and simulator. I'm running iOS 8.4, using storyboard and auto-layout. Check out screenshots. 

![captura de tela 2015-07-09 as 20 16 47](https://cloud.githubusercontent.com/assets/8397645/8609098/dd8b3ea6-2677-11e5-8335-3361dbf32cc4.png)
![captura de tela 2015-07-09 as 20 18 33](https://cloud.githubusercontent.com/assets/8397645/8609099/dd8d99e4-2677-11e5-861b-2c2a67be1acb.png)
