### ISSUE TITLE
make the rearView appear on top of the frontView

### ISSUE THREAD

**Issue by trivikram619** [John-Lluch/SWRevealViewController#312]
Is there any way to make the rearView appear on top of the frontView ? I tried to tweak with the shadow properties but it did not give any fruitful results.

**Comment by chlebta** [comment]
@John-Lluch Hello , Can you help me to make reavel menu appear on top of front view ?

**Comment by mohamedmansour** [comment]
@trivikram619 have you implemented it yet? I am creating something similar to yours where my frontView is static and the left sidebar will pop in on top. Would be nice to make it configurable via SWRevealViewController

**Comment by John-Lluch** [comment]
The one on top, the one that moves, is the frontViewController. Just think that way.

**Comment by marioffmarques** [comment]
Any improvements on this question ? I still cant make the frontView static :/

**Comment by chlebta** [comment]
@marioffmarques Nope I don't thing so any way you can use REFrostedMenu : https://github.com/romaonthego/REFrostedViewController/issues .

**Comment by John-Lluch** [comment]
Hi chlebta and marioffmarques, 

As stated before the frontView is NOT static, because it is the controller that moves. Only the rear or right view controllers are static. 

So just set the controller you want to be static to the rear or right view controller, and the one that slides on top of any them to the front view controller. It's pretty straightforward. I really am not sure about what is so difficult about this, or why you need some change in the reveal controller as it already does what you want !!

**Comment by mohamedmansour** [comment]
@John-Lluch  but when you do that, the front view that slides will always be visible. The rear doesn't appear on top of the front.

In my case, My sw_front is "My left menu that should slide" and my sw_rear is "My whole application". Doing what you recommended will just make keep the menu on front and the application will never show. Even when you swipe which will not work.

If I flip them, my sw_front is "my main application" and my sw_rear is my "Menu" the application will always show, and the menu is static and the application will move.

So here are the problems:
1) Front View will always appear on top and the front view is the only view that moves. We cannot move a rear view. 
2) Front View will always be shown, so creating the affect that this main thread stated (Let the rear view animate top of the front view) cannot be accomplished.

At this current stage, SWRevealViewController is not designed to allow the rear view animate to the front while keeping the front view fixed because the way it is implemented in the code, the front view is the view that moves and it is onto of everything and it is always shown at start.  To make that work, you have flip the logic, the rear view should appear on the front while animating.

**Comment by John-Lluch** [comment]
Hi Mohamed. You have full control of the class, including on initialisation. That's one if its strengths. You can do everything programatically. So just call the appropriate methods whenever you need it. Basically you can do everything with setFrontViewPosition:animated. Also, you do not need to show the frontViewController on initialisation. That's just the default but you can conceal it even before loading your controller views so you can make it not initially visible just as you want. You must set the rear or right view controllers as your "main application". while the front view will be your "menu". There's really nothing complicated on it. You just need to implement some programatic actions according to your desired behaviour.

**Comment by mohamedmansour** [comment]
@John-Lluch Can you show a simple example how to do this? 

1) The red view that will always be shown is the application 
2) Swipe from left to right, to show a green view appear on top of the application, swipe it out to show the static view.

There is nothing complicated, but if a new user wants the rear view to appear on top (like most apps are these days), this solution doesn't work out of the box, unless we are misunderstanding each other. I was using this for a hackathon with storyboards, but we ended up with REFrostedViewController. 

The reason why I am here is I like the amount of customizations this has, and the storyboard integration is a nice one.

**Comment by John-Lluch** [comment]
Mohamed. I insist, the REAR view will NOT appear on top of the FRONT view, Its the CONTRARY. Please do not attempt to do what the class doesn't do. Maybe you must think on a fresh way. FORGET about having the rear view on top of the front view. That's the first thing you need to understand. If you are capable of making this mental switch I think everything will suddenly become easier. According to your example, the RED view is the RIGHT view. The GREEN view is the FRONT view. Not the opposite.

**Comment by Marcopohlo** [comment]
When I do everything like @John-Lluch described, I don't achieve transparency, what do I do wrong?

https://github.com/John-Lluch/SWRevealViewController/issues/448

**Comment by abduliOS** [comment]
Put below code on menu view controller its works for me

@interface SidebarTableViewController ()
{
UIView\* coverView;
}

-(void) viewWillDisappear:(BOOL)animated
{
[coverView removeFromSuperview];
//[self.revealViewController.frontViewController.view setUserInteractionEnabled:YES];
// get your window screen size

}
-(void) viewWillAppear:(BOOL)animated
{
// get your window screen size
CGRect screenRect = [[UIScreen mainScreen] bounds];
//create a new view with the same size
coverView = [[UIView alloc] initWithFrame:screenRect];
// change the background color to black and the opacity to 0.6
coverView.backgroundColor = [[UIColor blackColor] colorWithAlphaComponent:0.6];
// add this new view to your main view
[self.revealViewController.frontViewController.view addSubview:coverView];
// [self.revealViewController.frontViewController.view setUserInteractionEnabled:NO];

}

**Comment by rvvivek** [comment]
@abduliOS : but i am unable to interact with the front view now after applying this code.

**Comment by iDevelopper** [comment]
The coverView must be added to the rightViewController.view, not on the frontViewController.view

**Comment by rvvivek** [comment]
yes i did that, now my tap gesture on front view is not working as normally it does to go back to front view.

**Comment by rvvivek** [comment]
@iDevelopper @abduliOS @John-Lluch

**Comment by iDevelopper** [comment]
I wrote a small example to illustrate this thread. It's a start, I hope it will help someone!

[SWMenuOnTop.zip](https://github.com/John-Lluch/SWRevealViewController/files/192283/SWMenuOnTop.zip)

**Comment by rvvivek** [comment]
@iDevelopper : thanx that pretty much helped, i got some idea..

**Comment by rvvivek** [comment]
![screen shot 2016-03-29 at 11 15 40 am](https://cloud.githubusercontent.com/assets/17777023/14099058/c2ee93f2-f59f-11e5-8dde-48bd34e8a0d2.png)
@iDevelopper @John-Lluch @mohamedmansour 
see here , what i want is when i tap the background view ie.(view controller1 scene) the menu table should again go back

**Comment by rvvivek** [comment]
@iDevelopper : but here my cover view is not allowing to interact.

**Comment by iDevelopper** [comment]
OK, I added a tapGestureRecognizer in this project and i corrected rightViewRevealOverdraw value  when open the menu (it was false).

[SWMenuOnTop 2.zip](https://github.com/John-Lluch/SWRevealViewController/files/192946/SWMenuOnTop.2.zip)

**Comment by rvvivek** [comment]
@iDevelopper :+1: thanx man :)

**Comment by iDevelopper** [comment]
It was not a problem with interaction as there is not a tapGesture in SW to act on rightViewController but only on frontViewController

**Comment by rvvivek** [comment]
@iDevelopper : Yes..Actually now, after going deeper into SW i got that.

**Comment by omayerg** [comment]
@iDevelopper Thank you for your help, but the front view (the menu) is truncated, if it was a right or rear view, I would change the overdraw and it will "adjust" to the given width and all elements of the menu view will be shown (now only the right half of the menu view is visible), any suggestions?

**Comment by iDevelopper** [comment]
Since I wrote a library for that (rear view on top of the front view), I can't help anymore, as there is some complicated points to resolve with SW for this topic. See my profile.

**Comment by omayerg** [comment]
@iDevelopper Thanks for answering, I know and I saw it (PBReveal), but unfortunately I have to use the SW and only it, I just have to change it so that menu view will be on top if opened and not pushed, your SWMenuOnTop did the job! the only problem is the mentioned above.

**Comment by iDevelopper** [comment]
In my sample I indent the cells.

```
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"Cell" forIndexPath:indexPath];
    
    // Configure the cell...
    cell.indentationLevel = 1;
    cell.indentationWidth = kRIGHTWIDTH;
    cell.textLabel.text = [NSString stringWithFormat:@"Controller %ld", (long)indexPath.row + 1];
    
    return cell;
}
```

**Comment by omayerg** [comment]
@iDevelopper I don't have only table, my menu view is a viewcontroller in which contains a lot of view and one of them is the table of the cells. I tried to set its width to 225 but it did not help.

I have another problem maybe its relevant to the problem, when the app loads, the menu view is presented first (because it is the front view I assume) and over the full screen!, did you manage to handle this issue?

**Comment by rvvivek** [comment]
Don't load menu view as the first view.. use a base view and then present
the menu on top of it from left just like Facebook

**Comment by iDevelopper** [comment]
Yes, setFrontViewPosition to leftSideMost.

For your menu, you have to set constraints

**Comment by omayerg** [comment]
@rvvivek That is the exact question, how to load the right/rear view as the first view?

@iDevelopper "Yes" is for the order of presenting the view? 

_setFrontViewPosition to leftSideMost_: simply makes the menu completely disappear, I used leftSide and leftSideMost exactly as you did in SWMenuOnTop.

_For your menu, you have to set constraints_: That what should resolve the truncation of the menu from the left? and constraints between what elements?

**Comment by rvvivek** [comment]
Go simple.. load a base view call it baseviewcontroller. On right top or
left top corner add a menu button.. on button action present a view from
left.. design that view such that only left 1/4th will be table.. rest will
be transparent means clear color. on tap of rest of the view other than
table view close the view with animation right to simple.. use tapgesture
recogniser for behind view
