### ISSUE TITLE
How to programmatically reveal SWRevealViewController menu without swipe or button press

### ISSUE THREAD

**Issue by Nerves82** [John-Lluch/SWRevealViewController#315]
Hi John,

I just need some quick advice.

I am using SWRevealViewController to produce a slide reveal menu and all is working wonderfully, as it should. I have it only affecting one View Controller within the app with a button and a swipe gesture recognizer to reveal the menu.

I am attempting to get the menu to automatically reveal when I move into the affected view controler but I am very unable to do it. I have tried to call the revealToggle: method directly, programmatically fire the button action and other variations with no success.

This is how it is implemented in viewdidload:

menu.target = self.revealViewController;
menu.action = @selector(revealToggle:); 
[self.view addGestureRecognizer:self.revealViewController.panGestureRecognizer];

How do I reveal the menu automatically without the swipe or button press?

Thanks for the awesome work!

**Comment by JayMehta97** [comment]
For swift 3 :-
self.revealViewController().revealToggle(self)

**Comment by manoj190** [comment]
see, what I got to open and close SWRevealViewcontroller or reveal the menu
       For right one using only button  -  self.revealViewController()?.rightRevealToggle(animated: true)
