### ISSUE TITLE
UIScrollViewPanGestureRecognizer was deallocated while key value observers were still registered with it

### ISSUE THREAD

**Issue by balkarov** [John-Lluch/SWRevealViewController#327]
Thanks! Sorry! Delete

**Comment by ulisescarreonalvarez** [comment]
@John-Lluch Hi, awesome work, how @balkarov fix it that?

**Comment by iDevelopper** [comment]
I think he had remove an observer.

**Comment by ulisescarreonalvarez** [comment]
@iDevelopper Hi, yes you're right i remove an observer of one of the uitableviews thanks!
