### ISSUE TITLE
Presenting view controllers on detached view controllers is discouraged

### ISSUE THREAD

**Issue by rock88** [John-Lluch/SWRevealViewController#344]
Hi, 
I try to present view controller from SWRevealViewController.rearViewController and get this log from console:

```
Presenting view controllers on detached view controllers is discouraged <SideMenuViewController: 0x14fbc6f0>
```

May be i do some wrong and need present view controller from SWRevealViewController?

**Comment by pt-arvind** [comment]
you ever figure this out?

**Comment by rock88** [comment]
@pt-arvind, I wrote own minimalistic RevealViewController =)
