### ISSUE TITLE
Put Side View on Main View like Google Maps or Drafts

### ISSUE THREAD

**Issue by LucaIaconelli** [John-Lluch/SWRevealViewController#352]
Hi,
I wanted to know if is possible to put the side view above the main view as Google Maps or Drafts (iOS 8)
Thanks so much

![1413341017-2014-10-15-at-04-43-23-](https://cloud.githubusercontent.com/assets/8015379/4986237/88aed5ee-6937-11e4-8e4a-17972048d63c.jpeg)

**Comment by liuxuan30** [comment]
Well I have the same question, the problem may be, to keep the Home/Main View (front view) not moving, when clicking the sidebar button, the side bar (rear view) will slide out and overlay home view.

**Comment by liuxuan30** [comment]
if talking about the stack, the sidebar view will on top of the main view when sliding out
