### ISSUE TITLE
[Ask for help] Pass object data to front view

### ISSUE THREAD

**Issue by ttv100682** [John-Lluch/SWRevealViewController#390]
Hi,

I did things on storyboard and work perfectly. Now just want to pass object data from a view controller to front view of SWReavelViewController. I tries as following but the frontViewControll is nil so can not pass data to:

SWRevealViewController *sw = [communityStoryBoard instantiateViewControllerWithIdentifier:@"RevealViewController"];
    AFODirectoryCategories *vc = (AFODirectoryCategories *)sw.frontViewController;
    vc.categories = [NSMutableArray arrayWithArray:categories];
...
[self presentViewController:sw animated:YES completion:nil];

Any ideas?

Thanks,
Vu

**Comment by schayes04** [comment]
You should not be instantiating the reveal view controller again. You need to get a reference to the existing reveal view controller. Likely just self.revealViewController (you may need to do #import "SWRevealViewController.h")

**Comment by ttv100682** [comment]
I checked code of SWRevealViewController.m and recognised that can not pass object data to front view controller if we use storyboard approaching because all related view controller be loaded in "loadview()":

- (void)loadView
{
    ...
    // load any defined front/rear controllers from the storyboard before
    [self loadStoryboardControllers];
.....
}

So need to find out another way.
