### ISSUE TITLE
Pan gesture on view not only on nav bar

### ISSUE THREAD

**Issue by ryanmsusa** [John-Lluch/SWRevealViewController#40]
instead of having the pan gesture only on the navigation bar to open/close the menu, it would be nice if it was on the entire view

(see the official facebook app for example)

**Comment by umarazhar** [comment]
I solved the issue by adding the panGestureRecognizer to the navigationcontrollers view instead. 
self.navigationController?.view.addGestureRecognizer(self.revealViewController.panGestureRecognizer())

This will allow pan gesture on both the view and the bar
