### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by shams-ahmed** [John-Lluch/SWRevealViewController#407]
Hey @John-Lluch,

is this project still be actively maintained?

**Comment by tdroenner** [comment]
I guess not.

2015-04-20 13:00 GMT+02:00 Shams Ahmed <notifications@github.com>:

**Comment by John-Lluch** [comment]
I intent to continue updating it to keep with the latest xCode releases provided this will not require a major refactoring or overhaul of the class. I just updated to version 2.4.0 to remove Xcode 6.3.1. Thanks for using the class.

John

**Comment by tholder** [comment]
Thanks John, I really like the project. I've only got about a week of iOS experience with Swift and I found it pretty easy to drop in.

One issue I am having, is that there are very few swift examples. Specifically, I've found a few people asking how to perform a manual segue when using SWRevealViewController. 

I posted a message about this at http://stackoverflow.com/questions/29792270/manual-segue-with-swrevealviewcontroller-in-swift/29792883

Can you add anything to this? It seems like, currently, the only way to work with Swift... is to learn Objective C :smile:

**Comment by John-Lluch** [comment]
I am not proficient on Swift, a lot of old very large Obj-C projects being maintained don't leave me enough time to make the switch just yet. I hope someone else may help you in the mean time. Thanks.

**Comment by tholder** [comment]
Hi John, no worries, appreciate it that worlds are colliding a bit in iOS land at the moment! Is it possible to describe (at an abstract level) what the approach would be in objective c? Should you be intercepting the prepareforsegue event and pushing the new controller some how? If I can work this out, I'll write up the swift solution to it!

**Comment by tdroenner** [comment]
Hi John,

is it possible to add the the [super layoutSubviews] to your layoutSubviews
override?

Thorsten

2015-04-22 15:26 GMT+02:00 Tom Holder <notifications@github.com>:

**Comment by shams-ahmed** [comment]
@John-Lluch thanks for getting back!
