### ISSUE TITLE
Swipe on navigationbar (like the dating app 'Happn'/'Tinder')?

### ISSUE THREAD

**Issue by danieldelouya** [John-Lluch/SWRevealViewController#412]
How can I make the navigationbar swipable to left and right as well?

(In Swift)

**Comment by cbh2000** [comment]
Have you tried adding the panGestureRecognizer to your nav bar?

**Comment by imnathan** [comment]
@danieldelouya just use self.revealViewController() .panGestureRecognizer(),
        self.revealViewController() .tapGestureRecognizer() and it works fine!
