### ISSUE TITLE
Reason: Incompatible library version

### ISSUE THREAD

**Issue by tomaszwojcik** [John-Lluch/SWRevealViewController#456]
I have encountered the following problem while running app on the device (on the simulator it works fine):

```
Reason: Incompatible library version: <MyApp> requires version 2.0.0 or later, but SWRevealViewController provides version 1.0.0
```

Here's Podfile (pods version `0.38.2`, iOS 8, Swift) line for SWRevealViewController:

```
pod 'SWRevealViewController', '~> 2.3', inhibit_warnings: true
```

**Workaround**

I have changed the SWRevealViewController Pod's target `Build Settings/Linking/Compatibility Version` to `1` and it seems to work. However I'm not sure how bad it is :disappointed:

**Comment by jerrychen109** [comment]
This is an issue with the newest version CocoaPods that a lot of people have run into. Try deleting your DerivedData folder and rebuilding your project as described in the top answer here: http://stackoverflow.com/questions/18933321/deleting-contents-from-xcode-derived-data-folder

**Comment by tomaszwojcik** [comment]
Thanks a lot Jerry, it worked like a charm!
