### ISSUE TITLE
Go back from rear viewcontroller to front viewcontroller

### ISSUE THREAD

**Issue by param0091** [John-Lluch/SWRevealViewController#457]
Hello sir,
I have implemented UITabbarController with SWRevealviewController every this is fine expect one

i.e when i push to one of the view in RearViewController i'm not able to pop to FrontView controller

is it possible how. 

my Structure

TabBarController(RootViewController)>NavigationController>RevealViewController then Front and rear view

**Comment by alirezanmz** [comment]
i have this problem you solve this problem if you find out about work pop to frontVew controller  this problem please  tell me how i can fix this problem

**Comment by iDevelopper** [comment]
Push your controller from the front view controller:

self.revealViewController.frontViewController.navigationController.pushViewController(yourController, animated: true)
