### ISSUE TITLE
I need to close reveal menu while tap on base controller

### ISSUE THREAD

**Issue by imrielruchi** [John-Lluch/SWRevealViewController#458]
Hi,

Currently reveal menu close only by tap on slide button or swipe the screen.

I need to close it manually. How to do same ?

Thanks in adv.

**Comment by imrielruchi** [comment]
ok i solved this by putting below code:

override func touchesBegan(touches: Set<NSObject>, withEvent event: UIEvent) {
        if let touch = touches.first as? UITouch {
            if self.revealViewController() != nil {
                self.view.addGestureRecognizer(self.revealViewController().tapGestureRecognizer())
            }
        }

```
    super.touchesBegan(touches , withEvent:event)
}
```

**Comment by vineethvijayan** [comment]
This doesn't work with UITableViewController 
touchesbegan is not working for UITableVireController

**Comment by ZalyalovIldar** [comment]
solution for objective-c 
 if (self.revealViewController != nil){
        [self.view addGestureRecognizer:self.revealViewController.tapGestureRecognizer];
    }
    [super touchesBegan:touches withEvent:event];

**Comment by iDevelopper** [comment]
```
[self.revealViewController setFrontViewPosition:FrontViewPositionLeftSide];
```

Voila !

**Comment by ZalyalovIldar** [comment]
I found some pull request and re write library with it, it give possibility to set black shadow to your front view controller, and close menu by tapping on it . If you want, i can give you this re written methods. By the way, as for me,  it would be great to have this inside swrevel library, i think a lot of people will see this useful.

**Comment by iDevelopper** [comment]
I don't really understand the feature. Could you share a image please?

**Comment by ZalyalovIldar** [comment]
![2015-12-23 15 54 58 rectangle 1 rectangle 2](https://cloud.githubusercontent.com/assets/8490823/11976912/0271f3e2-a98e-11e5-8480-697c47af9f41.png)
![group](https://cloud.githubusercontent.com/assets/8490823/11976961/9b79a864-a98e-11e5-84d0-a8d7de9f75ea.png)

**Comment by iDevelopper** [comment]
Actually you can close the menu if you tap on frontViewController with the pan gesture feature. What you want is only add a black shadow when menu is open?

**Comment by ZalyalovIldar** [comment]
pan gesture not working with tableView (no, it's work but not like a "voila!"), here added shadow view to all of font view, and use pan gesture of view

**Comment by iDevelopper** [comment]
I wanted to say tap gesture

**Comment by iDevelopper** [comment]
Pan gesture work with tableview. You can't add the same pan gesture on the navigation bar and on the tableview

**Comment by ZalyalovIldar** [comment]
you'r right, but i think this update will work better just with one bool line of code for user

**Comment by iDevelopper** [comment]
You can add the pan gesture to the navigationController.view and all is OK! Pan work on entire view (tableview and navigation bar)

**Comment by ZalyalovIldar** [comment]
yeah, knew it, whatever, both  work.

**Comment by iDevelopper** [comment]
Then?

**Comment by leizard** [comment]
I read through the issue and still don't find (or understand) an solution for Swift. Could anyone please make it clear?

**Comment by iDevelopper** [comment]
I wrote two samples. #577 (MapSample in swift).

Have a look and tell me what you want to do exactly.

**Comment by iDevelopper** [comment]
In fact, you don't need to add your gestures yourself in each controllers, just call the SW methods (tapGestureRecognizer() and panGestureRecognizer() in the SW subclass or just in your first frontViewController. SW take care of everything...

I completed the example with other features:

[MapSample 2.zip](https://github.com/John-Lluch/SWRevealViewController/files/250195/MapSample.2.zip)

Hope this help!

**Comment by leizard** [comment]
Thank you.
I put

`
 self.revealViewController().tapGestureRecognizer()
 self.revealViewController().panGestureRecognizer()
`

in my frontViewController and it works like charm.
Cheer!
