### ISSUE TITLE
How to hide menu when click on frontview?

### ISSUE THREAD

**Issue by OptimusKoala** [John-Lluch/SWRevealViewController#461]
Hi all,
I want to hide/close menu view when I click anywhere in the front view (right) when the menu is shown. 

Can somebody help me?

**Comment by vineethvijayan** [comment]
Did you got answer for this?

**Comment by vineethvijayan** [comment]
Found the answer at 
https://github.com/John-Lluch/SWRevealViewController/issues/458
Thanks  :)
