### ISSUE TITLE
use 2 viewcontrollers to the right side

### ISSUE THREAD

**Issue by mortelpoison972** [John-Lluch/SWRevealViewController#471]
I would use two views on the right side called by two different buttons . No problem for the first , I use this method: `performSegueWithIdentifier ("rightRevealToggle" sender: self)` and in my storyboard i have a segue identifier named  `sw_right`;
but for the 2nd button I try to create a new method like: `performSegueWithIdentifier ( " customRevealToggle " sender: self) ;`
and  ``NSString * const SWSegueCustomIdentifier = @ " sw_custom " ;` and change the name of the segue to my storyboard "sw_custom" but it don't work
can u help me?

**Comment by burakkoray** [comment]
hi,
Have you found how to call two different viewcontroller ?
