### ISSUE TITLE
Push delay on iOS 8

### ISSUE THREAD

**Issue by Moonko** [John-Lluch/SWRevealViewController#476]
I have a strange delay on iOS 8 when using SWRevealViewControllerSeguePushController segue. It takes about 2 seconds before transition animation takes place. Also first call of "reveal toggle" takes about 3-4 seconds. Here's my storyboard:
![2015-09-23 15 39 37](https://cloud.githubusercontent.com/assets/5665912/10048466/a9f5bc58-621b-11e5-81e4-a2392d842bad.png)
On iOS 7 and 9 it works fine without any delay.

**Comment by bordadagua** [comment]
Hi Moonko. Did you fixed this issue? I'm having the same problem with iOS 9 when pushing a second view controller.

**Comment by Moonko** [comment]
@bordadagua Yes, it was my own fault. I just forgot to add my custom fonts in resources and the system was searching for them first time.
