### ISSUE TITLE
How can I disable my regular views when the reveal view controller is activated?

### ISSUE THREAD

**Issue by leonardbonfils** [John-Lluch/SWRevealViewController#489]
When my reveal view controller is open, how can I make it so that touching my regular views will not do anything ? 

I.e. on this screenshot, I don't want anything on the right side of the screen to be active. I only want to be able to tap anywhere on the right side of the screen to make the menu disappear. Right now, when I tap on the right side of the screen, my table is active and tapping a cell takes me to my detail view controller, which I don't want.

Help?

![screen shot 2015-10-19 at 4 23 42 pm](https://cloud.githubusercontent.com/assets/6782987/10617506/f00e842c-7738-11e5-98d3-fe9792dab1b1.png)

**Comment by croccio** [comment]
i've found best (IMO) solution for this case:

declare UIVIew as class variable:

```
let overlayView: UIView = UIView()
```

than in viewDidAppear

```
override func viewDidAppear(animated: Bool) {
    super.viewDidAppear(animated)

    self.revealViewController().frontViewController.view.addSubview(overlayView)

}
```

and than in viewDidDisappear

```
override func viewDidDisappear(animated: Bool) {
    super.viewDidDisappear(animated)

    overlayView.removeFromSuperview()
}
```

and in viewDidLoad

```
overlayView = UIView(frame: self.view.frame)
```

**Comment by iDevelopper** [comment]
Just self.tableView.userInteractionEnabled = NO; // Objective-c

**Comment by croccio** [comment]
@iDevelopper ok but swipe to close menu and tap on front view controller not work

**Comment by iDevelopper** [comment]
It works for me

**Comment by croccio** [comment]
on ios8/ios9 doesn't work

on ios7 i dont' know

**Comment by iDevelopper** [comment]
It works for me on iOS 8 and 9. I don't anymore develop for iOS 7. You could also test the position of your frontViewController and and use the tableview delegate method WillSelectRowAtIndexPath and return nil if menu is open

**Comment by croccio** [comment]
ok, i understand, you set in on tableview! :D but i think that if in frontviewcontroller you've three button you've to set userInteractionEnabled = NO on all button. with my way you do all-in-one :D

**Comment by iDevelopper** [comment]
viewDidAppear is not called when you tap on the frontViewController, it is call if you tap on the menu. It should be better to use a delegate method of SWRevealViewController :)

**Comment by croccio** [comment]
in my case viewDidAppear (of menu controller) is called when i tap on menu button or i swipe on frontviewcontroller. however i'm going to try with its delegate :)

**Comment by iDevelopper** [comment]
I thought you was in frontViewController

**Comment by croccio** [comment]
no i'm in menuViewController so i can "block iteration" on all frontViewController without add iterationEnable on all views in all frontViewController

**Comment by iDevelopper** [comment]
Yes i see, sorry

**Comment by iDevelopper** [comment]
You can set userInteractionEnabled to NO to the view (instead of tableView). It works too !

**Comment by iDevelopper** [comment]
```
- (void)revealController:(SWRevealViewController *)revealController didMoveToPosition:(FrontViewPosition)position
{
    UIViewController *controller;
    if ([revealController.frontViewController isKindOfClass:[UINavigationController class]]) {
        UINavigationController *nc = (UINavigationController *)revealController.frontViewController;
        controller = (UIViewController *)(nc.topViewController);
    }
    else {
        controller = revealController.frontViewController;
    }
    if (position == FrontViewPositionLeft) {
        controller.view.userInteractionEnabled = YES;
    }
    else {
        controller.view.userInteractionEnabled = NO;
    }
}
```

**Comment by leonardbonfils** [comment]
Hey, so I tried the very first answer and it didn't work. I can't swipe to close the menu (right-to-left motion) and I can't click the menu button at the top of my tableView to close the menu. How can I make that work ?

I never learned any Objective-C at all, I'm doing all my iOS programming in Swift. Can you rewrite your last suggestion in Swift please ? I don't 100% know how to translate it.

**Comment by leonardbonfils** [comment]
Also, when I set userInteraction to "false" (in Swift), it has the same effect that the overlay view had. It blocks everything (including the swipe from right-to-left and pressing the menu button).

**Comment by iDevelopper** [comment]
@croccio : can you translate the last objective-c suggestion to swift ?

**Comment by leonardbonfils** [comment]
For anyone who might be interested, I got a great answer from posting this question on Reddit, and it works _flawlessly_.

Here is the code! https://gist.github.com/DennisDreissen/9217de6bc4ecb154cdbc

**Comment by khs8727** [comment]
@LeonardBonfils Thanks for sharing the answer. It work perfectly as I wanted!

**Comment by iDevelopper** [comment]
Just do that:

```
import UIKit

class RevealViewController: SWRevealViewController, SWRevealViewControllerDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()

        self.delegate = self

        self.tapGestureRecognizer()
        self.panGestureRecognizer()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }

    //MARK : - SWRevealViewControllerDelegate

    func revealController(revealController: SWRevealViewController!, willMoveToPosition position: FrontViewPosition) {
        if position == FrontViewPosition.Right {
            self.frontViewController.view.userInteractionEnabled = false
        }
        else {
            self.frontViewController.view.userInteractionEnabled = true
        }
    }
}
```
