### ISSUE TITLE
Delegate for menu opened/closed?

### ISSUE THREAD

**Issue by piotrros** [John-Lluch/SWRevealViewController#492]
How can I listen to an event when menu was closed or opened? I can't even find in code some bool like isOpened or something like that. I have a bar button item, which opens or closes menu (also I have pan gesture) and I want to display different image when menu is closed and opened.

**Comment by iDevelopper** [comment]
You can test the position of the frontViewController (property frontViewPosition). Also you can implement the delegate method to be informed when the position change :

// The following delegate methods will be called before and after the front view moves to a position
- (void)revealController:(SWRevealViewController *)revealController willMoveToPosition:(FrontViewPosition)position;
- (void)revealController:(SWRevealViewController *)revealController didMoveToPosition:(FrontViewPosition)position;

**Comment by piotrros** [comment]
Great! Thanks for help!

Here's my code:

```
func revealController(revealController: SWRevealViewController!, willMoveToPosition position: FrontViewPosition) {
        switch(position){
        case FrontViewPosition.LeftSideMostRemoved:
            print("LeftSideMostRemoved")
            // Left most position, front view is presented left-offseted by rightViewRevealWidth+rigthViewRevealOverdraw

        case FrontViewPosition.LeftSideMost:
            print("LeftSideMost")
            // Left position, front view is presented left-offseted by rightViewRevealWidth

        case FrontViewPosition.LeftSide:
            print("LeftSide")

            // Center position, rear view is hidden behind front controller
        case FrontViewPosition.Left:
            print("Left")
            //Closed
            //0 rotation

            let menuButtonView = menuButton.valueForKey("view") as! UIView
            menuButtonView.transform = CGAffineTransformMakeRotation(CGFloat(0))

            // Right possition, front view is presented right-offseted by rearViewRevealWidth
        case FrontViewPosition.Right:
            print("Right")
            //Opened
            //rotated

            let menuButtonView = menuButton.valueForKey("view") as! UIView
            menuButtonView.transform = CGAffineTransformMakeRotation(CGFloat(M_PI_2))

            // Right most possition, front view is presented right-offseted by rearViewRevealWidth+rearViewRevealOverdraw

        case FrontViewPosition.RightMost:
            print("RightMost")
            // Front controller is removed from view. Animated transitioning from this state will cause the same
            // effect than animating from FrontViewPositionRightMost. Use this instead of FrontViewPositionRightMost when
            // you intent to remove the front controller view from the view hierarchy.

        case FrontViewPosition.RightMostRemoved:
            print("RightMostRemoved")

        }
    }
```

**Comment by kanumuri9593** [comment]
Hi How I can call the above method I need to change the Menu Button Icon when it is touched or menuView is opened

thank you

**Comment by iDevelopper** [comment]
@kanumuri9593 the above method (delegate method) is called by SW when you adopt SWRevealViewControllerDelegate protocol.

**Comment by kanumuri9593** [comment]
Thanks for the response Is there a way to animate the menu icon during the swipe?

**Comment by iDevelopper** [comment]
Yes I think so. Could you explain what you want to do?

**Comment by kanumuri9593** [comment]
can I change the menu icon  into a left arrow with transformation if possible?

**Comment by iDevelopper** [comment]
You have the code above from @piotrros to do this
