### ISSUE TITLE
Switching front view controller from the front view controller

### ISSUE THREAD

**Issue by JoeDurand3** [John-Lluch/SWRevealViewController#494]
Hello,

I'm developing a database-driven app that uses SWRevealViewController to control the menu functions. When my users first login and the SWRevealViewController is loaded with its initial front and rear controllers, the front view is a menu controller that has similar functionality to the rear controller menu. I want them to be able to switch to another view without having to open up the menu. My question is, how can I set a new front view controller from the current front view controller?

**Comment by iDevelopper** [comment]
[self.revealViewController pushFrontViewController:yourController animated:YES];

**Comment by JoeDurand3** [comment]
Thanks very much for quick reply and help, but when I implement that my new front view controller it gives me trouble with my revealviewcontroller code there. Attached is screenshot if that helps. Thanks again!!

![screen shot 2015-10-25 at 1 00 22 pm](https://cloud.githubusercontent.com/assets/13091711/10717534/8c334224-7b18-11e5-88c0-f3b65f68c84a.png)

**Comment by piotrros** [comment]
I have exact the same problem! menuButton is nil when I'm using this method. Xcode 7.1, swift 2.1, iPhone 6 simulator.

edit:

My code is:
let controller = ProductsTableViewController()
self.revealViewController().setFrontViewController(controller, animated: true)

**Comment by piotrros** [comment]
Ok so I figured out where's a problem. I forgot that my controller was embedded in NavigationController on storyboard. However this one still doesn't work:

```
let controller = ProductsTableViewController()
                let navigationController:UINavigationController = UINavigationController(rootViewController: controller)
                self.revealViewController().setFrontViewController(navigationController, animated: true)
```

edit: this actually works now, I had another bug that prevented it from working properly. 

By the time experimenting I've figured out 3 methods which work:

1) make new controller, embed it in navigation controller and use pushFrontViewController
2) use storyboard!.instantiateViewControllerWithIdentifier
3) make a custom segue (class SWRevealViewControllerSeguePushController) from menu to your navigation view controller (which embeds view controller) and just use performSegueWithIdentifier

Third method is the best :)

**Comment by iDevelopper** [comment]
@JoeDurand3 : menuButton is probably nil, is it connected with the storyboard ?

**Comment by JoeDurand3** [comment]
I'm using the storyboard programmatically, instantiating the storyboard in appdelegate and using instantiateViewWithIdentifier(String, Bundle) to create views.

But you are right, it's coming up as nil. I'm not sure how to connect my view to my viewcontroller that I instantiate, but that's another issue. Thanks for your help!

**Comment by MuhammadRizwan95** [comment]
@JoeDurand3  In Swift 3.01 Use this Way!


        if self.revealViewController() != nil {
            let reveal = self.revealViewController()
            reveal?.rearViewRevealWidth = 300
            reveal?.revealToggle(self)
            self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
        }

**Comment by ashwanikumaryadav** [comment]
How to switch frontviewcontroller.
I have a login
1. Customer
2. Service Provider
When login to customer the frontviewcontroller  will be different from service provider how to switch the frontviewcontroller.

**Comment by iamhassan** [comment]
@JoeDurand3  i think your menuButton outlet is not connected try after connecting outlets
