### ISSUE TITLE
How to load pop up view on the top of Front ViewController  

### ISSUE THREAD

**Issue by sambo168** [John-Lluch/SWRevealViewController#495]
Hi !  I am iOS newbie , and i start to develop simple application.And i have problem while i am developing. my problem is i have button in the rare ViewController. When i click on that button it show the PopView, but unfortunately that PopView is under the front view controller. (the front view controller is still shown ABOVE the right view controller, and the right view controller is shown below the former)  
So how can i show PopView on the top of front view controller ? 
![screen shot 2015-10-26 at 9 37 08 am](https://cloud.githubusercontent.com/assets/15316383/10719521/3a36012a-7bc5-11e5-9c68-4e7d7bcd2e63.png)

**Comment by iDevelopper** [comment]
What is PopView ? How do you present it ?

**Comment by sambo168** [comment]
a custom view using XIB.  This is how i present it. 

//CreateFolderPopViewFileOwner.h
+(void)presentViewinViewController:(UIViewController *)viewController  withCompletionHandler:(void (^)(NSString *, NSInteger))handler {

```
// Instantiating encapsulated here.
CreateFolderPopViewFileOwner* owner = [CreateFolderPopViewFileOwner new];
[[NSBundle mainBundle] loadNibNamed:@"CreateFolderPopView" owner:owner options:nil];

[owner.createFolderPopView setBackgroundColor:[[UIColor blackColor] colorWithAlphaComponent:.6]];
owner.createFolderPopView.txtTitle.delegate = viewController;
[viewController.view addSubview:owner.createFolderPopView];
[viewController.navigationController popToViewController:viewController animated:YES];
//Store referenced
completionHandler =  handler;
```

}

//RareViewController.m
[CreateFolderPopView presentViewinViewController:self withCompletionHandler:^(NSString *folderTitle, NSInteger buttonCode){

```
    NSLog(@"Folder title is : %@", folderTitle);
    NSLog(@"Button code is  : %@ ", (buttonCode == 1001) ?  @"Ok " : @"Cancel");

    if([folderTitle length] > 0){

            FolderEnt *folderEnt = [NSEntityDescription insertNewObjectForEntityForName:@"FolderEnt"
                                                                 inManagedObjectContext:kSBCoreData.managedObjectContext];

            //==save context
                if(folderEnt != nil){

                     folderEnt.folder_id    = [UtilityClass  getFourDegitNumberAsString:[self getFolderMaxID]];
                     folderEnt.folder_title = folderTitle;
                     folderEnt.create_date  = [UtilityClass getCurrentDateWithFormat_MMMM_dd_yyyy_HH_mm_a];

                    NSError *error_obj = nil;
                   //==save
                    if([kSBCoreData.managedObjectContext save:&error_obj]){
                        NSLog(@"Successfully saved the context.");
                    }else {
                        NSLog(@"Failed to save the context. Error = %@",error_obj);
                    }

                }
    }

}];
```

**Comment by iDevelopper** [comment]
Try this :

```
UIViewController *topController = [[[[UIApplication sharedApplication]delegate]window]rootViewController];
while (topController.presentedViewController) topController = topController.presentedViewController;
```

[CreateFolderPopView presentViewinViewController:topController withCompletionHandler:^(NSString *folderTitle, NSInteger buttonCode){

**Comment by sambo168** [comment]
Thank you so much. that is  exactly what i want to do. 
 Thank for helping me. 
![screen shot 2015-10-26 at 3 56 11 pm](https://cloud.githubusercontent.com/assets/15316383/10723852/309b1fc6-7bfa-11e5-8cb1-99ce922881b0.png)
