### ISSUE TITLE
How to simply close the reveal controller?

### ISSUE THREAD

**Issue by Multiforge** [John-Lluch/SWRevealViewController#498]
Hi, I'm a new user of the reveal controller. I have it set up so it reveals a menu on the left (a UITableViewController). Tapping any menu cell (table view cell) triggers the reveal push segue to show the appropriate navigation controller which pushes in from the right. So far so good.

_Question_: If the user opens the menu on the left, then taps on the cell corresponding to the currently-loaded navigation controller, it will cause a _new_ navigation controller to be loaded. How do I make the table view cell's tap simply close the menu? (since it's already showing the correct navigation controller)

Thanks for any help.

**Comment by iDevelopper** [comment]
https://github.com/John-Lluch/SWRevealViewController/issues/487

**Comment by Multiforge** [comment]
That's great, thank you!
