### ISSUE TITLE
Test if side menu is open

### ISSUE THREAD

**Issue by JMStudiosJoe** [John-Lluch/SWRevealViewController#528]
Hello, I need to do something like this. I have been going through the list of methods within the self.revealViewController object but couldn't find what I need. Please help and thank you!

override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
    {
       if // side menu is open
           //close side menu
      else
           //do nothing
    }

**Comment by JMStudiosJoe** [comment]
Ended up using delegate method willMoveToPosition to trigger a flag.. can close

**Comment by iDevelopper** [comment]
Objective-c:

```
    if (self.revealViewController.frontViewPosition == FrontViewPositionRight) {
        [self.revealViewController setFrontViewPosition:FrontViewPositionLeftSide];
    }
```

**Comment by jpopham** [comment]
In Swift:
`if self.revealViewController().frontViewPosition == FrontViewPosition.Right {
                    self.revealViewController().setFrontViewPosition(FrontViewPosition.Left, animated: true)
                }
`
