### ISSUE TITLE
SWRevealViewController not working with storyboard

### ISSUE THREAD

**Issue by jasminpethani** [John-Lluch/SWRevealViewController#532]
I am making simple application with Left menus( rear controller) and Front (Table view Controller) with **storyboard**

Using *_SWRevealViewController version 2.3.2 *_

i have followed tutorials:
http://www.appcoda.com/sidebar-menu-swift/    and used attached example _RevealControllerStoryboardExample2_ with framework

i have made sample tutorial demo it working fine

After some time it starting crashing with following error (typing **po $arg1**)
Error message : 
`Receiver (<SWRevealViewController: 0x7f83e2000000>) has no segue with identifier 'sw_right'`

Please help me

**Comment by iDevelopper** [comment]
Not understand. The sample crash or your own application ? And where ?

**Comment by garfiaslopez** [comment]
In  your  storyboard, in the view controller that's gonna be the right menu you need to add the string 'sw_right' at the identifier field of the storyboard segue that connects your SWREVEALVIEWCONTROLLER and your TABLEVIEW.

**Comment by jasminpethani** [comment]
@garfiaslopez 

I am not showing right menu, i am just showing left menu

**Comment by iDevelopper** [comment]
You have to show your storyboard and a part of your code if you want some help

**Comment by mutablestudio** [comment]
make sure you are using SWRevealViewControllerSegueSetController type for your sw_front and sw_rear, etc. segues. And they have to have those specific names.

**Comment by SantiagoGutierrez14** [comment]
I am also having an issue where I cant slide my menu open. I am also following the same tutorial.
