### ISSUE TITLE
Center Navigation Bar Title

### ISSUE THREAD

**Issue by cristinaITdeveloper** [John-Lluch/SWRevealViewController#548]
How I can center the title in Navigation Bar of Rear View Controller? 
![img_5915](https://cloud.githubusercontent.com/assets/11472348/12814436/5e2210d2-cb3f-11e5-9ae0-61b5ce957cbb.PNG)

**Comment by iDevelopper** [comment]
```
self.revealViewController.rearViewRevealOverdraw = 0;
```

**Comment by cristinaITdeveloper** [comment]
Thank you!
