### ISSUE TITLE
Keep front view loaded at all times

### ISSUE THREAD

**Issue by tommy-b-10** [John-Lluch/SWRevealViewController#573]
My front view is a mapkit view, and is running some gps location updates in the background.

When I select another view controller in the menu, it completely kills the map view. Then when I reload, all of the labels are set to default and the map has gone back to default.

Is there any way to keep the views loaded?

Thanks!

**Comment by iDevelopper** [comment]
Save your controller in a property in the viewDidLoad of your menu controller, your controller is self.revealViewController.frontViewController. In the didSelectRowAtIndexPath instantiate it if the property is nil otherwise just push it:

```
            ......
            if (!_viewController) {
                self.viewController = [storyBoard instantiateViewControllerWithIdentifier:@"ViewController"];
            }
            controller = _viewController;
            .....
    [self.revealViewController pushFrontViewController: controller animated:YES];

```

**Comment by tommy-b-10** [comment]
I have managed to get this working, however, with swift, we cannot test if viewcontroller is nil. Is there a way to do this?

Thanks!

**Comment by iDevelopper** [comment]
Here is a sample i wrote for you:

[MapSample.zip](https://github.com/John-Lluch/SWRevealViewController/files/218557/MapSample.zip)

**Comment by tommy-b-10** [comment]
Thanks! That was just what I was looking for! 

Cheers
