### ISSUE TITLE
Can't enable tap gesture recognizer.

### ISSUE THREAD

**Issue by OptimusKoala** [John-Lluch/SWRevealViewController#575]
Hi, 
I know this issue was already asked and I've read the answers. But, my issue is still here. 
I love the SWRevealViewController and all works fine exept with on view. 

I use the Google map sdk and I need to disable the userInteraction on my google map if the menu is up. But, it disable also my tap and pan gesture. 

I call the SWRevealViewController here : https://github.com/Yagora/CEOS_IOS/blob/master/CEOS/MapViewController.swift#L74 
I disable user interraction here : https://github.com/Yagora/CEOS_IOS/blob/master/CEOS/MapViewController.swift#L332

I've already tried to add a tapGestureRecognizer but didn't works. I've also tried to disable only Google map interraction, not the whole view, and didn't works too. 

What am I missing/doing wrong?

**Comment by iDevelopper** [comment]
Just do like this in a subclass of SWRevealViewController and nothing else in yours controllers:

```
import UIKit

class RevealViewController: SWRevealViewController, SWRevealViewControllerDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()

        self.delegate = self

        self.tapGestureRecognizer()
        self.panGestureRecognizer()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }

    //MARK : - SWRevealViewControllerDelegate

    func revealController(revealController: SWRevealViewController!, willMoveToPosition position: FrontViewPosition) {
        if position == FrontViewPosition.Right {
            self.frontViewController.view.userInteractionEnabled = false
        }
        else {
            self.frontViewController.view.userInteractionEnabled = true
        }
    }
}
```

**Comment by iDevelopper** [comment]
Example:

[MapSample.zip](https://github.com/John-Lluch/SWRevealViewController/files/227752/MapSample.zip)

**Comment by OptimusKoala** [comment]
I'll try it after work, this evening (I'm in France) :D Thank you so much for this.

**Comment by iDevelopper** [comment]
Welcome, I'm in France too.

**Comment by OptimusKoala** [comment]
It works soooo great, thank you sooooo much.

**Comment by iDevelopper** [comment]
Happy for you!
