### ISSUE TITLE
How to make the rear view appear over front view like Google + Slide Drawer?

### ISSUE THREAD

**Issue by thihaaung6245** [John-Lluch/SWRevealViewController#576]
I found the same question solved here : https://github.com/John-Lluch/SWRevealViewController/issues/312

But,the problem is I don't know anything about in Obj-C

Any Help in Swift?

**Comment by iDevelopper** [comment]
What about this?

[SWFrontMenu.zip](https://github.com/John-Lluch/SWRevealViewController/files/234448/SWFrontMenu.zip)

**Comment by iDevelopper** [comment]
otherwise there is:

https://github.com/alexkrzyzanowski/SidebarOverlay

https://github.com/evnaz/ENSwiftSideMenu

https://github.com/jonkykong/SideMenu

**Comment by leizard** [comment]
Hi @iDevelopper, your example is great and give me some ideas how to implement this requirement. But how could I make the frontview dim black when the menu appear ? and the menu seem missing width when run on iphone 5s and smaller device.
Thank you

**Comment by iDevelopper** [comment]
Hi @leizard , for the front view dim black, have a look at the RevealViewController.swift, I added a coverView. And for the width, you can act on font's size. Have a look in cellForRowAtIndexPath function in MenuTableViewController.swift. I added also a rightViewController to the otherController.

[MapSample 3.zip](https://github.com/John-Lluch/SWRevealViewController/files/253425/MapSample.3.zip)

**Comment by iDevelopper** [comment]
Hi @leizard , it was a mistake as the sample was not the good one. So I deleted my response. Have a look to the coverView I added in the RevealViewController class (subclass of SW). The coverWiew is added to the right view (not the front view) when menu is open. Regarding the width, see the rightWidth variable.

[SWFrontMenu 2.zip](https://github.com/John-Lluch/SWRevealViewController/files/253834/SWFrontMenu.2.zip)

**Comment by iDevelopper** [comment]
The latest sample: I modified some features

[SWFrontMenu 3.zip](https://github.com/John-Lluch/SWRevealViewController/files/254010/SWFrontMenu.3.zip)

**Comment by leizard** [comment]
Hi @iDevelopper, I finally used https://github.com/jonkykong/SideMenu to implement my side menu, it resolve this requirement quite good beside some great animation configs. 
Your sample works perfectly, I hope it will help others who need to implement this kind of menu.
Thank you for spending your time.

**Comment by iDevelopper** [comment]
I had a look quickly! You are probably right as this project is recent and John-Lluch does not seems to maintain his one anymore. But I can't see how to replace the main view controller when selecting a cell in the left menu. (As the front view in SW). I don't like the push to the presented view controllers. I would like to change the content of the main view controller. Did you understand how to do this?

**Comment by leizard** [comment]
Hi @iDevelopper, I am a Swift beginner and just found sidemenu of jonky is easy to implement, I think this package doesn't provide the solution of replacing the main view controller but just push the new presented one. Is this approach not good ?

**Comment by iDevelopper** [comment]
I did not say it is not good, just I don't like. I am also a Swift beginner since only two or three weeks (I followed some tutorials) but I know Objective-c since 2009. It help! Did you have a look at the two others library I mentioned in this post? What disturbing you in SW? Sorry for my english!

**Comment by leizard** [comment]
Yes I did. And I found that the jonky's one provides great animations and easy to setup the kind of sidemenu that I want. Though recently I have some issue when using unwind segue to push new view. So I'm going to dig deeper to your sample and response asap.
Thank you very much for your time and your great responses.

**Comment by iDevelopper** [comment]
Hi @leizard , I wrote another sample (a better one!). Much simpler. Could you have a look?

[SWTopMenu.zip](https://github.com/John-Lluch/SWRevealViewController/files/260863/SWTopMenu.zip)

**Comment by iDevelopper** [comment]
Hi @leizard , I wrote another sample (a better one!). Much simpler. Could you have a look?

[SWTopMenu.zip](https://github.com/John-Lluch/SWRevealViewController/files/260890/SWTopMenu.zip)

**Comment by leizard** [comment]
Hi @iDevelopper, your sample is nice but I think it is missing animation when changing front view (appear from right to left). is there easy way to add animation ?
And I think I get your idea. With SWReveal, the side menu will not reload because it is just replacing the front view, in the other side, jonky's side menu will because it push new view every time navigate out. Please correct me if I'm wrong.

**Comment by iDevelopper** [comment]
What kind of animation? Is it the animation when you push the front view then rear go right a little before go to left? Within SW, there is no more animation between front and right, but we can reproduce it easily. I'm not sure I understand the second question. You can push the same view controller each time if you save it in a property like I do for the map controllers.

**Comment by leizard** [comment]
Sorry very much for late response. I was snowed under with other tasks, now come back to sidemenu. The kind of animation that I mentioned before is similar with the animation of this sidemenu:
https://github.com/evnaz/ENSwiftSideMenu
When you change front view, the new front view appear from right to left, like it pushing the sidemenu to close.

**Comment by iDevelopper** [comment]
Yes, what about this?

[SWTopMenu 2.zip](https://github.com/John-Lluch/SWRevealViewController/files/310164/SWTopMenu.2.zip)

**Comment by leizard** [comment]
That 's slick. And wow, such a good and fast support from you. Could you help me one last favour by giving another sample about implementing 2 side menu left - right ?
Thank you very much :)

**Comment by iDevelopper** [comment]
Wa can't because you wanted the menu on top, then we used the front view controller for the menu and the right view controller for the controllers to display. You can have another menu with rear view controller. Then two menus on the left. Otherwise you add a button to yours controllers and push a menu on the right with the navigation controller.

**Comment by leizard** [comment]
Thank you for your information. I'm looking into it.

**Comment by iDevelopper** [comment]
@leizard : 

[SWTopMenu 3.zip](https://github.com/John-Lluch/SWRevealViewController/files/310200/SWTopMenu.3.zip)

**Comment by iDevelopper** [comment]
Not very good because the right menu is full screen. I will do it with a popover.

**Comment by iDevelopper** [comment]
[SWTopMenu 4.zip](https://github.com/John-Lluch/SWRevealViewController/files/310372/SWTopMenu.4.zip)

I added a RightMenuTableViewController and it is display in a popover.
