### ISSUE TITLE
misplaced rearview on swipe

### ISSUE THREAD

**Issue by Datagard** [John-Lluch/SWRevealViewController#579]
Hi!
I've added SWRevealViewController into the app and almost everything's fine! 
There is only one issue. 
If revealViewController is shown on "Swipe left" then rearview is misplaced. 
If revealViewController is shown on "TouchUpInside" event then everything's perfect!
Here is a sample:
[https://github.com/Datagard/sampleSwipe](https://github.com/Datagard/sampleSwipe)

![question](https://cloud.githubusercontent.com/assets/15154142/15218946/0e5ae5fc-1873-11e6-8328-e5f5f2833968.png)

video:
![swipe2m](https://cloud.githubusercontent.com/assets/15154142/15220774/c34bb030-1879-11e6-8e11-f1c0e5d5dd3b.gif)

The declarations for events handlers:

`if self.revealViewController() != nil {

        menuButton.addTarget(self.revealViewController(), action: #selector(SWRevealViewController.rightRevealToggle(_:)), forControlEvents: UIControlEvents.TouchUpInside)
        self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
    }`

It seems like rearview on swipe has an offset -21px by Y and +8px by X.

Could you help me with it?

Best Regards,
Dmitry

**Comment by iDevelopper** [comment]
Could you reproduce this with a little sample ans post it?

**Comment by Datagard** [comment]
Hi!
Do you mean still image or gif-video?

**Comment by iDevelopper** [comment]
No, a sample project

**Comment by Datagard** [comment]
Hi,

I’m sorry it’s my first time ))
Do I need to publish a sample project on GitHub or just share it to you?

Best Regards,
Dmitry

**Comment by iDevelopper** [comment]
You can share it if you want

**Comment by Datagard** [comment]
Sure, Thanks! I’ll do the sample!

**Comment by Datagard** [comment]
I did it! )))
https://github.com/Datagard/sampleSwipe

Could you have a look?

**Comment by iDevelopper** [comment]
Yes but there is no SW in this project! It is just a table view controller with two view.

**Comment by Datagard** [comment]
Why not?
Did I miss something?
SWRevealViewController is Entry point.

![sw](https://cloud.githubusercontent.com/assets/15154142/15322726/82027f58-1c4f-11e6-9ba9-91e42fd947aa.png)

**Comment by iDevelopper** [comment]
It is not the project you post on Github

![sampleswift](https://cloud.githubusercontent.com/assets/1782450/15323283/947c0626-1c41-11e6-8284-de57123881df.png)

**Comment by Datagard** [comment]
You are correct!
Sorry, it’s my first public project on Github!

I’ve fixed it! 
Please, have a look the same link to project Datagard/sampleSwipe.

**Comment by iDevelopper** [comment]
Your right view controller is an subclass of UIImageView. When I tap the right button to display it or when I swipe right to left to display it, it is the same result...

**Comment by Datagard** [comment]
Yes! It’s correct! If you tap the button first then everything is okay!
The problem is appear when “swipe to left” first.
“Tap the button” normalize UI controls position (constraints).

**Comment by iDevelopper** [comment]
I have missed something, I can not reproduce the problem

**Comment by iDevelopper** [comment]
[SampleSwiftVideo01.mp4.zip](https://github.com/John-Lluch/SWRevealViewController/files/268327/SampleSwiftVideo01.mp4.zip)

**Comment by Datagard** [comment]
The problem will appear only if you'll make these steps:
1. Start the app
2. Swipe to the left.
It looks like (and it's a wrong position of rearview):
![scr](https://cloud.githubusercontent.com/assets/15154142/15324848/3402e734-1c59-11e6-9caa-86eabe56c290.png)



If you will "swipe to the right" and after that "swipe to the left" again the problem will disappeared.

**Comment by Datagard** [comment]
Yes! Your video is showing the problem! 
When you "swipe to the left" first time then all UI controls is misplaced!
It seems like rearview on swipe has an offset -21px by Y and +8px by X.

**Comment by iDevelopper** [comment]
Yes I see now !

**Comment by Datagard** [comment]
Thanks!! )) You spent a lot of time for me!
I hope it will be useful for everybody who uses SWRevealViewController!

**Comment by iDevelopper** [comment]
Yes but I did nothing always. No wrong code and I think the issue comes from image size or constraints. I need to explore more...

**Comment by Datagard** [comment]
Originally in the app there isn't image. 
There are buttons and other controls.

I have inserted image just for sample. 
But constraints issue is the same.

**Comment by iDevelopper** [comment]
I think in your storyboard you have to set constraints on your right view with standard value or your own but uncheck constrain to margins. See this sample project I wrote:

**Comment by iDevelopper** [comment]
Your project modified:

[sampleSwipe-master.zip](https://github.com/John-Lluch/SWRevealViewController/files/268854/sampleSwipe-master.zip)

**Comment by Datagard** [comment]
Thank you very much!
I'll clean up constraints!

**Comment by iDevelopper** [comment]
@Datagard , It's work?

**Comment by Datagard** [comment]
I have fixed "Horizontal space" constraints (the problem was in "relative to margin"). 
"Vertical space" constraints isn't works. But i'm not finished yet.

**Comment by Datagard** [comment]
It isn't working with "vertical" constraints.
On "swipe to the left" UI controls are placed 20px higher
![diff](https://cloud.githubusercontent.com/assets/15154142/15424152/1d450474-1e92-11e6-936f-b8657f18144f.png)

**Comment by iDevelopper** [comment]
Try this, it works at home: 
1) Set the frame with 0, 0, 600, 600 in the story for this view (Menu in the sample)
2) Clear constraints for this view.

![2016-05-20_13-41-23](https://cloud.githubusercontent.com/assets/1782450/15426774/0334516c-1e91-11e6-86c3-51c3a47e8eea.png)

And after this you have a warning, then select Update frame.

[sampleSwipe-master 2.zip](https://github.com/John-Lluch/SWRevealViewController/files/274475/sampleSwipe-master.2.zip)
