### ISSUE TITLE
Help with switching to view

### ISSUE THREAD

**Issue by amz4u2nv** [John-Lluch/SWRevealViewController#580]
Hi,
I'm having issues on how to switch the front view to a view controller when a menu link is pressed on the left side menu - 
I got the following code in prepareForSegue method  -

```
    HTMLViewController *vc = (HTMLViewController *) [sb instantiateViewControllerWithIdentifier:@"AccountLoginViewController"];
    UINavigationController *navController1 = [[UINavigationController alloc] initWithRootViewController:vc];
    [self.revealViewController pushFrontViewController:navController1 animated:YES];
```

When I run the code, the view comes up for about a second, then gets quicly changed to a black blank view, with nothing on it.

Any ideas?

**Comment by amz4u2nv** [comment]
Also do I have to implement the side menu button for each view controller that I create. Isn't there a way to just add it to the navigation controller and reuse it.

**Comment by iDevelopper** [comment]
1/ I think you have to do this in DidSelectRowAtIndexPath, not in prepareForSegue and delete the segue in the storyboard
2/ In a storyboard, I don't think so

**Comment by amz4u2nv** [comment]
Thanks,...
Ended up overloading uiviewcontroller to get the menu button to show on all views.
