### ISSUE TITLE
Same color status bar for menu as navigation bar

### ISSUE THREAD

**Issue by c0rv0s** [John-Lluch/SWRevealViewController#581]
![img_0039](https://cloud.githubusercontent.com/assets/6027978/15271852/011d0abe-1a12-11e6-88c8-d64ebcfa6da7.jpg)

As you can see my navigation bar is gold and so the status bar on that screen is gold also, but I want the background color of the status bar on the menu to be this olive green color. How can this be done?

**Comment by iDevelopper** [comment]
Is it a table view controller? Try to set the background color of your tableview to this olive color.

**Comment by c0rv0s** [comment]
Thanks! that worked perfectly.
