### ISSUE TITLE
Only enable right menu for selected views.

### ISSUE THREAD

**Issue by A-Lim** [John-Lluch/SWRevealViewController#583]
Currently I have a left side view which is for menu navigation. I've implemented another side view on the right side which I want it to appear on certain views only. However for the views that have the following code, the right menu is also enabled when the user swipes from right to left in other views. How do I make the right menu to be only enabled in certain views.

```
if revealViewController() != nil {
    view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
}

```

**Comment by iDevelopper** [comment]
Set rightViewController to nil or rightViewRevealWidth to 0 when you don't want to show the right view controller.

**Comment by A-Lim** [comment]
Setting **rightViewRevealWidth** to **0** still shows a little bit of the right view however setting it to **nil** does the trick.

Thanks for the prompt reply.

**Comment by A-Lim** [comment]
Hi, I encounter a problem when I set the rightViewController to nil. After I set it to nil, how do I set it back?

**Comment by iDevelopper** [comment]
self.revealViewController().rightViewController = yourController

**Comment by A-Lim** [comment]
Thanks. <3

**Comment by iDevelopper** [comment]
Hi @A-Lim , this is a sample:

[SWRight.zip](https://github.com/John-Lluch/SWRevealViewController/files/502282/SWRight.zip)
