### ISSUE TITLE
RightViewController layout broken related to status bar and panGestureRecognizer Obj-C

### ISSUE THREAD

**Issue by TonyAnhTran** [John-Lluch/SWRevealViewController#585]
I got his problem when try to implement rightViewController from storyboard then show the right menu for the _**first times**_ with panGestureRecognizer
![screenshot 2016-05-23 11 18 53](https://cloud.githubusercontent.com/assets/7332592/15463632/ddb66e64-20f4-11e6-8fc3-4feac84efcef.png)

Please note that this problem not happen with rightRevealToggle.
I try to debug with breakpoint on this and it not happen, but it always happen with out breakpoint  so seem like this issues related to the:
`[self _enqueueBlock:^{}]; // <-- dummy block`
Does anyone facing this issues or solution for this?
Thank you!

**Comment by iDevelopper** [comment]
The problem is that your constraints in the storyboard are not set correctly. Please see #579 .

**Comment by TonyAnhTran** [comment]
Great, thank you so much! #iDevelopper You are correct.
To simply reading for someone else face this again:
1. Your top leading constrain should be leading to "superview", not top leading constrain. To do it, please refer this: http://stackoverflow.com/a/31548575/4172423
2. From that constrain configuration, uncheck option "Related to the margin"
![screenshot 2016-05-23 16 13 23](https://cloud.githubusercontent.com/assets/7332592/15465988/95965934-2101-11e6-8654-edcd71c03724.png)
3. Build and enjoy.
