### ISSUE TITLE
How to create a submenu next to the "main" slide menu

### ISSUE THREAD

**Issue by Saerdn** [John-Lluch/SWRevealViewController#593]
I'd like to create a submenu in with SWRevealController in Swift. That means if I press a button in in the first slide out menu, another slide out menu appears right next to the first one. I already managed to create to two slide out menus. One on the right side of the view and one on the left side. I want to have both menus on the same side.

Just like in the third example "SWRevealController Example 3". Unfortunatly, there is no storyboard so I can't see how the segues are set etc.

Can anyone point me in the right direction?

In the example it looks like there's a view controller (aka VC2) called (from within the main slide out menu) which already has another slide out menu. If so, do I need a second/another SWRevealViewController that is connect with the VC2 AND the sub slide menu?

Thank you,
Andi

**Comment by iDevelopper** [comment]
Yes in the example John create another instance of SWRevealViewController with their rear and front view controller. The front view controller of the first SW is set with this new instance of SW.

**Comment by iDevelopper** [comment]
This is a sample I wrote:

[SWTwoLeftMenus.zip](https://github.com/John-Lluch/SWRevealViewController/files/320065/SWTwoLeftMenus.zip)

**Comment by Saerdn** [comment]
Thank you very much, that is much more than I'd hoped for :))
It's working perfectly fine.

**Comment by Saerdn** [comment]
Btw. I managed to work with the same slide out menu as it's own submenu by referencing to the "RevealViewController" instead of "ChildRevealViewController". By checking if the main menu has already been called, I can dynamically rename/relabel the sub slide menu.
