### ISSUE TITLE
apply menu in second or third viewcontroller

### ISSUE THREAD

**Issue by omsomar** [John-Lluch/SWRevealViewController#596]
Hi. I have a problem when I apply the swrevealviewcontroller in a different view to the first sight of the menu is not displayed on the same screen . someone has happened the same ?? how you could fix it ?? I would like to apply it in various views . Thanks for your answers.

**Comment by iDevelopper** [comment]
I don't understand the question!

**Comment by omsomar** [comment]
hello again!. thanks for the quick response!.

Look I have three views . the first does not have the swrevealviewcontroller apply . but the second if available. when I step from the first view to the second view which has the swrevealviewcontroller not show me the menu . Please observe the images of what is happening to me.

thanks.
![captura de pantalla 2016-06-28 a las 9 19 14 a m](https://cloud.githubusercontent.com/assets/9533102/16418990/b4438466-3d11-11e6-87b9-c9a37525dd86.png)

![captura de pantalla 2016-06-28 a las 9 20 18 a m](https://cloud.githubusercontent.com/assets/9533102/16419015/cbb0116e-3d11-11e6-9bb1-c1b22d74e802.png)
