### ISSUE TITLE
Fade in and Fade out effect on pan gesture

### ISSUE THREAD

**Issue by adarshsripathyrao** [John-Lluch/SWRevealViewController#597]
Hi, I have another issue, I need to have a fade in and fade out feature i.e I need to change the opacity of front view controller's view in such way that it feels like the front view controller fades in and fades out.

I observed this delegate method:-
- (void)revealController:(SWRevealViewController *)revealController panGestureBeganFromLocation:(CGFloat)location progress:(CGFloat)progress overProgress:(CGFloat)overProgress

But this method tracks the progress only till I the place where I have panned. I need to know a way to calculate the progress from 0 position till the front view controller reaches the rearViewRevealWidth.

**Comment by adarshsripathyrao** [comment]
Anyways. Got it to work.

**Comment by iDevelopper** [comment]
It will be nice to explain what you did for others people

**Comment by adarshsripathyrao** [comment]
Sure, I have used the delegate functions 
- (void)revealController:(SWRevealViewController *)revealController animateToPosition:(FrontViewPosition)position
  and 
- (void)revealController:(SWRevealViewController *)revealController panGestureMovedToLocation:(CGFloat)location progress:(CGFloat)progress

to check for the front view controller position and progress, and gave the opacity values accordingly.

here is a sample working code:-
- (void)revealController:(SWRevealViewController *)revealController animateToPosition:(FrontViewPosition)position{
  if (position == FrontViewPositionLeft) {
      self.view.alpha = 1;
  }else if(position == FrontViewPositionRight){
      self.view.alpha = 0.15;
  }
  }
- (void)revealController:(SWRevealViewController *)revealController panGestureMovedToLocation:(CGFloat)location progress:(CGFloat)progress{
  if (progress > 1) {
      self.view.alpha = 0.15;
  }else if(progress == 0){
      self.view.alpha = 1;
  }else{
      self.view.alpha = 1 - (0.85 \* progress);
  }
  NSLog(@"%f - %f",progress, self.view.alpha);
  }

Hope it helps someone 👍
