### ISSUE TITLE
Get ViewController of sw_rear?

### ISSUE THREAD

**Issue by Dbigshooter** [John-Lluch/SWRevealViewController#612]
Hi there!

My problem seems fairly simple, but I just can't figure out how to solve it. When my MenuViewController is showing, it's the rear one, I need to set a delegate in the MenuViewController so I can modify the content in the ViewController I came from. For instance I have a button in the MenuViewController which is meant to modify the map in the ViewController I am showing the MenuViewController from. Any suggestions? Really appreciated!

**Comment by iDevelopper** [comment]
Yes subclass SWRevealViewController and set the delegate to this subclass. Otherwise, see also https://github.com/iDevelopper/PBRevealViewController as SW is not maintained,anymore!

**Comment by Dbigshooter** [comment]
Thanks! Could you provide an example for SWRevealViewController? I am having trouble getting a hold of my MenuViewController, when I press the UIItemBarButton on my MapViewController, which is the sw_front. I tried to do this, however it didn't work.

```
func test() {
        self.revealViewController().revealToggle(self)
        if let viewControllers = self.view.window?.rootViewController?.childViewControllers {
            for viewController in viewControllers {
                // some process
                print(viewController)
                if viewController.isKindOfClass(MenuViewController) {
                    print("yes it is")
                    let c = viewControllers as! MenuViewController
                    c.delegate = self
                }
            }
        }
    }
```

Do you have guide to how to use PBRevealViewController in Swift?

**Comment by iDevelopper** [comment]
The class is documented in PBTevealViewController.h and on cocoapods. Use it as SWRevealViewController. On the github repo there is 2 examples written in Swift. Just use pb_left, pb_main and pb_right instead of sw_rear, sw_front and sw_right.

For your problem the rear view controller is: revealViewController().rearViewController. If it is embedded in a navigation controller, the MenuViewController is the topViewController of the navigation controller.

But what is for the MenuViewController's delegate?

**Comment by Dbigshooter** [comment]
My hierarchy looks like this:

SWRevealViewController --- sw_rear ---> MenuViewController
SWRevealViewController --- sw_front ---> MapViewController

When I click a button in the menu, I want to show something on the map in the MapViewController, hence the delegate.

**Comment by iDevelopper** [comment]
You don't need a delegate to. In your MenuViewController, have you retained a reference to your MapViewController?

**Comment by Dbigshooter** [comment]
No, how would I do that?

**Comment by iDevelopper** [comment]
Can you show a screenshot of your app?

**Comment by Dbigshooter** [comment]
Of the storyboard?

**Comment by iDevelopper** [comment]
If you don't have a reference for your MapViewController, a new instance is created each time you open it from the menu?

**Comment by Dbigshooter** [comment]
The only thing I do is this:

`self.revealViewController().revealToggle(self)`

**Comment by iDevelopper** [comment]
You have only one front view controller?

**Comment by iDevelopper** [comment]
Yes the storyboard.

**Comment by Dbigshooter** [comment]
Initially, yes. You can navigate to other front view's using the menu, but some of the menupoints are meant to manipulate the current viewcontroller you're opening the menu from.

**Comment by iDevelopper** [comment]
Then when you navigate to others from view and come back to map view, the map reloads.

**Comment by Dbigshooter** [comment]
Yes.

**Comment by iDevelopper** [comment]
Then keep a reference to it:

See this sample:

[MapSample.zip](https://github.com/John-Lluch/SWRevealViewController/files/429645/MapSample.zip)

**Comment by Dbigshooter** [comment]
Let's see if I'm right on this. So the reference is this?
```

let navController = self.revealViewController().frontViewController as? UINavigationController
        mapViewController1 = navController!.topViewController as? MapViewController
```

**Comment by Dbigshooter** [comment]
Oh, so you can just do this:

```
let navController = self.revealViewController().frontViewController as? UINavigationController
mapViewController1 = navController!.topViewController as? MapViewController
```

And it'll give you the sw_front, meaning the viewcontroller you came from?

**Comment by iDevelopper** [comment]
You are in my sample? In MenuTableViewController?

mapViewController1 is the reference to the MapViewController instance, you can use it directly.

**Comment by Dbigshooter** [comment]
Yea, I am. That was exactly what I was looking for, finding a way to get a hold of the instance of mapViewController, so I can do thing with the map inside the controller by clicking on one of the menu points.

**Comment by iDevelopper** [comment]
Then, it is OK?

**Comment by Dbigshooter** [comment]
Yea, perfect! Thank you so much! 

A last question, when I click the menu item which do stuff on the map, can I make it go back to the map before starting the thing? Since it's a webservice call which can take some time.

**Comment by iDevelopper** [comment]
Where is called the request?

**Comment by Dbigshooter** [comment]
It is called in the MapViewController, so I want the menu item to show the mapView and then request.

**Comment by iDevelopper** [comment]
On button tap:

if the MapViewController is embedded in a navigation controller:
            let navController = UINavigationController(rootViewController: mapViewController1!)
            revealViewController().pushFrontViewController(navController, animated:true)
else:
            revealViewController().pushFrontViewController(mapViewController1, animated:true)
and call the request function:
            mapViewController1.request()

**Comment by iDevelopper** [comment]
I did the same with a marker (added Add a marker in menu):

[MapSample 2.zip](https://github.com/John-Lluch/SWRevealViewController/files/429864/MapSample.2.zip)

**Comment by Dbigshooter** [comment]
Thanks! Is it done the same way in PBRevealViewController?

**Comment by iDevelopper** [comment]
Great! Yes. And you can have the left view (menu) above or below the main view.

**Comment by Dbigshooter** [comment]
Great! Thanks, much appreciated!

**Comment by Dbigshooter** [comment]
I just have a last question, when I push the map back, and add the pins, they layout I've done, another color on navigationBar is just white, and not the color I want, how come?

**Comment by iDevelopper** [comment]
I don't understand your question. In your app?

**Comment by Dbigshooter** [comment]
Nevermind, I figured it out. I had to call the function that setup the layout in viewWillLayoutSubviews, since the viewDidLoad doesn't get called. Is it possible to show on the menu, which menu item I'm current on? If I called the menu from the mapViewController, I could show a grey overlay on the map menu point?

**Comment by iDevelopper** [comment]
I think it is in your storyboard's constraints for the mapView.

**Comment by Dbigshooter** [comment]
Can I somehow know which viewController which called the menu?

**Comment by iDevelopper** [comment]
This is the front view controller.

revealViewController().frontViewController

**Comment by iDevelopper** [comment]
You can test that with the delegate function: (willMove or didMoveToPosition)

```
func revealController(revealController: SWRevealViewController!, willMoveToPosition position: FrontViewPosition) {
    if position == FrontViewPosition.Right { // Menu will open
         ... // Test which front view controller will open the menu
```

**Comment by iDevelopper** [comment]
Add this to my sample: In RevealViewController.swift:

```
func revealController(revealController: SWRevealViewController!, didMoveToPosition position: FrontViewPosition) {
    if position == FrontViewPosition.Right {
        var controller = revealController.frontViewController
        if controller is UINavigationController {
            let nc = controller as! UINavigationController
            controller = nc.topViewController
        }
        print(controller)
    }
}
```

**Comment by iDevelopper** [comment]
Is your menu a table view controller? I did not see that you edited a comment above:

"Is it possible to show on the menu, which menu item I'm current on? If I called the menu from the mapViewController, I could show a grey overlay on the map menu point?"

**Comment by Dbigshooter** [comment]
Yea it is. 

I was wondering, can I use SWRevealViewController for my left menu, and PBRevealViewController for my right?

**Comment by iDevelopper** [comment]
I don't think so! But why use both.

For the table view controller, in viewDidLoad:

```
    // Uncomment the following line to preserve selection between presentations
    //self.clearsSelectionOnViewWillAppear = false
```

**Comment by Dbigshooter** [comment]
I want the left menu to be animated like SWRevealViewController does, and the right like the other.

**Comment by iDevelopper** [comment]
PBRevealViewController can animates like SW (PBRevealToggleAnimationTypeSpring) and you can provide your custom animation controller too. Did you try the samples?

**Comment by Dbigshooter** [comment]
Oh perfect, I didn't even notice ;o) 

I'll try the samples and get back.

**Comment by Dbigshooter** [comment]
When I try to use CocoaPods to get PBRevealViewController I get:

`PBRevealViewController (~> 1.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `PBRevealViewController (~> 1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by iDevelopper** [comment]
Then in a new project?

**Comment by Dbigshooter** [comment]
I'm now trying to use PBRevealViewController, but I get a nil here. In the same project as before: 

`let navController = self.revealViewController().frontViewController as? UINavigationController`

And if I try to run the examples I get that there is no podfile and such, 3 errors.

Can PBRevealViewController animate just like SWRevealViewController? Like pushing the main view away and not showing above it?

**Comment by iDevelopper** [comment]
Where? In the main view controller? Is the view on the screen?

**Comment by Dbigshooter** [comment]
In the MenuViewController, it crashes since it is nil. But before we continue: Can PBRevealViewController animate just like SWRevealViewController? Like pushing the main view away and not showing above it?

**Comment by iDevelopper** [comment]
Yes.

**Comment by Dbigshooter** [comment]
Cool, do I need to subclass it and make my own controller, or can it be done in another way?

And I use static cells in my menu, how can I just change mainview when I click at them?

**Comment by iDevelopper** [comment]
If you want the main view controller to the right, and below, set leftPresentViewOnTop = false.

Like this?

![2016-08-23_16-50-28](https://cloud.githubusercontent.com/assets/1782450/17896721/f2267272-6951-11e6-9fbb-c4c6a58164b1.png)

**Comment by Dbigshooter** [comment]
Yea, but without the shadow ;o)

I cannot get the push to work. On my static cell I've made a custom segue with PBRevealViewControllerSeguePushController, but it doesn't work.

**Comment by iDevelopper** [comment]
Yes.

[Example3Swift.zip](https://github.com/John-Lluch/SWRevealViewController/files/432755/Example3Swift.zip)

You have some properties to set the shadow:

/**
-  Defines the radius of the main view's shadow, default is 5.0f.
  */
  @property (nonatomic) CGFloat           mainViewShadowRadius;

/**
-  Defines the main view's shadow offset, default is {0.0f,5.0f}.
  */
  @property (nonatomic) CGSize            mainViewShadowOffset;

/**
-  Defines the main view's shadow opacity, default is 1.0f.
  */
  @property (nonatomic) CGFloat           mainViewShadowOpacity;

/**
-  Defines the main view's shadow color, default is blackColor
  */
  @property (nonatomic) UIColor           *mainViewShadowColor;

The same for left and right views when above.

![2016-08-23_17-01-11](https://cloud.githubusercontent.com/assets/1782450/17897221/aebdb9e4-6953-11e6-9fd8-ea57126b60c6.png)

**Comment by Dbigshooter** [comment]
Where do I find those properties?

**Comment by iDevelopper** [comment]
All those properties are in PBRevealViewController.h and also documented on cocoa pods.

**Comment by Dbigshooter** [comment]
Oh okay, I can use different styles for the left and right menu? Your example gives me this error: linker command failed with exit code 1 (use -v to see invocation)

I cannot get the push to work. On my static cell I've made a custom segue with PBRevealViewControllerSeguePushController, but it doesn't work.

**Comment by iDevelopper** [comment]
Yes. On top or none, Custom shadow for each, overdraw, displacement etc...

**Comment by Dbigshooter** [comment]
How can I make the menu push the main view, and not go on top of it?

**Comment by iDevelopper** [comment]
This is the case of these last two images, no? The menu is not on top, there a just in this sample a blur effect on the table view.

**Comment by Dbigshooter** [comment]
At the moment the view covers something of my maincontroller, I don't want it to do that, I just want to push it to the right.

**Comment by iDevelopper** [comment]
Is it a test project you can provide here? Then I could see.

**Comment by Dbigshooter** [comment]
In your example, you can still see the menubutton on the maincontroller, my left menucontroller covers that at the moment, and I don't want it to. I want it to show exactly like SWRevealViewController

**Comment by iDevelopper** [comment]
Did you set LeftViewPresentOnTop to false? A property in PBRevealViewController.h

**Comment by Dbigshooter** [comment]
Perfect, thanks! I really appreciate your taking time to guide me! Can you answer this, since it find it really odd.

I cannot get the push to work. On my static cell I've made a custom segue with PBRevealViewControllerSeguePushController, but it doesn't work.

**Comment by Dbigshooter** [comment]
Can I somehow change the height of the right menu? I don't want it to start at the top on the screen, but just below the navigationbar.

**Comment by iDevelopper** [comment]
I have no sample with static cell, i never use that. Can you post your sample please?

For the second question, use the:

/**
- If YES (default is NO) the left view controller will be ofsseted vertically by the height of a navigation bar plus the height of status bar.
  */
  @property (nonatomic) BOOL              rightPresentViewHierarchically;

**Comment by Dbigshooter** [comment]
I can't get it to work by setting that to YES, nothing happens? 

I'll post an samle in a minute.

**Comment by iDevelopper** [comment]
OK and in my sample, the right menu is under the navigation bar. But in this case it must be presented on top on the main view because if not the navigation bar of the main view is pushed on left!

**Comment by Dbigshooter** [comment]
I tried to edit it in the .m file, but it is still covering the navigationbar.

**Comment by iDevelopper** [comment]
```
        self.revealViewController()?.rightPresentViewHierarchically = true
```

**Comment by Dbigshooter** [comment]
It worked, thanks! I'll post a sample with static cells, I really want to use that.

**Comment by Dbigshooter** [comment]
Uhm, but there's not much to show with the static cells, you just drag a segue from the menupoint to the controller you want to go to. But unfortunately it doesn't work.

**Comment by iDevelopper** [comment]
I have already test but with dynamic cells (table view cell -> push segue and test the indexPath). I have to write a sample if you can't send your with static cells. Why do you want to use static cells? Is it from rightViewController?

**Comment by Dbigshooter** [comment]
I got it to work ;o) Is it possible to make the right view controller a bit transparent?

**Comment by iDevelopper** [comment]
Cool! Those are your controllers, you do what you want with. PBRevealViewController just present them. In my sample, the right view controller is transparent and the left one have a blur effect. Play with your view's alpha property.

**Comment by Dbigshooter** [comment]
Thanks! Is it possible to reduce the height of the rightview? I want it to be a little short at the bottom, so I can fit in a tabbar.

**Comment by iDevelopper** [comment]
Hi,

In my sample, there is a tab bar controller (see storyboard). It is automatic...

**Comment by Dbigshooter** [comment]
@iDevelopper For some reason I can't run your example, I get: 

`linker command failed with exit code 1 (use -v to see invocation)`

**Comment by iDevelopper** [comment]
Did you not run it yesterday?

**Comment by iDevelopper** [comment]
You must open the xcworkspace and not the xcodeproj.

**Comment by Dbigshooter** [comment]
Got it solved. However I can see that your right menu is behind the tabBar, I actually want the view to stop by the tabBar. Is that possible?

**Comment by iDevelopper** [comment]
It is not! This is a table view controller. This controller takes all the screen by default. But you can see that all the cells are visibles when scrolling. If you want to do differently, uses a UIViewController with a table view. Don't forget to set the datasource and delegate of table view to it.

**Comment by iDevelopper** [comment]
I would like you to open issues in the PBRevealViewController's Github repository as this is not the right place here now! Thanks a lot!
