### ISSUE TITLE
Present left menu below navigation bar 

### ISSUE THREAD

**Issue by narri007** [John-Lluch/SWRevealViewController#614]
Hi, I am using SWRevealViewController to show left and right menu options in my project. I want to show the left menu below the navigation bar of Front view and changing the navigation bar item image with animation. And for the right menu i want to show it as normal effect as SWRevealViewController. How can i do the left menu presentation below navigation bar.  Below is my requirment. 

![menu](https://cloud.githubusercontent.com/assets/5907338/17918901/90d4a3f0-69e6-11e6-82c6-020fcd687f3c.png)

Thanks !

**Comment by iDevelopper** [comment]
I think it will not be possible: In the first case (left) SWRevealViewController must be embedded in a navigation controller and in the second not.

see https://github.com/iDevelopper/PBRevealViewController

**Comment by narri007** [comment]
Thanks for reply, 

With that example we can achieve the left menu presentation style. But how can I combine both left menu at below the navigation bar (same as PBRevealViewController) and right menu as (SWRevealingViewController).

**Comment by iDevelopper** [comment]
You can easily do that with PBRevealViewController. Left and right can be above or below main view and on top of screen or under the navigation bar.

**Comment by narri007** [comment]
Got it! Thank you. 

Where I can change the left Navigation bar button icon, like before opening the left menu it should be menu icon. After opening it should turn as a back button. Please let me know this.

**Comment by iDevelopper** [comment]
Implement one of this delegate methods:

```
/**
 *  Called just before the left view controller is presented.
 *
 *  @param revealController The reveal view controller object.
 *  @param controller       The left view controller object.
 */
- (void)revealController:(PBRevealViewController *)revealController willShowLeftViewController:(UIViewController *)controller;

/**
 *  Called just after the left view controller is presented.
 *
 *  @param revealController The reveal view controller object.
 *  @param controller       The left view controller object.
 */
- (void)revealController:(PBRevealViewController *)revealController didShowLeftViewController:(UIViewController *)controller;
```

**Comment by iDevelopper** [comment]
Change it again when you close the menu by selecting a menu's item.

**Comment by narri007** [comment]
Thank You.

**Comment by iDevelopper** [comment]
Great! If you have others issues about PBRevealViewController, do not hesitate, but open them in the PBRevealViewController's Github repository as this is not the right place here now!
