### ISSUE TITLE
Rear View doesn't respect status bar constraint with pan gesture, but revealToggle respects it.

### ISSUE THREAD

**Issue by dilizarov** [John-Lluch/SWRevealViewController#615]
I'm not sure why this is happening, but to access my rear menu, you can either press a button or you can use the pan gesture. Everything is perfect when you press the button, but when you use the pan gesture, it seems that the constraint for it to be below the status bar isn't acknowledged.

Here are 3 images to depict the difference:

How it should look:

[Correct constraints image](http://i.imgur.com/YXoCAvD.png)

How it looks when I use the pan gesture:

[Incorrect constraints image](http://i.imgur.com/yqmjcY9.png)

How the constraint looks like on my storyboard:

[Storyboard image](http://i.imgur.com/JngV17S.png)

**Comment by dilizarov** [comment]
#488 had a fix

**Comment by iDevelopper** [comment]
#585 
#555
