### ISSUE TITLE
SWRevealViewController rightRevealToggleAnimated not working in iOS 9

### ISSUE THREAD

**Issue by kirankhalkar** [John-Lluch/SWRevealViewController#618]
Hi,

Using SWRevealViewController I have implemented right and left slider into my application. while  integrating iOS9 localisation feature into my app  for (Arabic language) then right slider  option not worked (rightRevealToggleAnimated). 

have someone face same issue? please help ..

Thanks

**Comment by iDevelopper** [comment]
What changes does the use of arabic language? Can you test with https://github.com/iDevelopper/PBRevealViewController, a librairie I wrote as SWRevealViewController seems not to be maintained anymore.

**Comment by kirankhalkar** [comment]
Thanks for your quick response...

whenever i changed the language English to arabic, All also implementation to right. Only my right slider not work.

**Comment by iDevelopper** [comment]
When you write my right slider not work, you mean it does not open or the content is not shown correctly? If it is the case, can upload a screenshot?

**Comment by John-Lluch** [comment]
Hi iDeveloper, I am not currently able to give as much support on the class as I used to do (health issues), but please stop pushing your own controller for developer code issues that are anyway not related with the SWRevealViewController. This controller is very well supported on the web and used by thousands, so it's not right that you just tell people to replace it by your own. If you really think that yours is superior at least give some credit to me, as your code is blatantly based on my code.

**Comment by kirankhalkar** [comment]
Hi iDeveloper,
while changing  language English to arabic, Click on right menu, slider not open..

**Comment by iDevelopper** [comment]
It is not possible! Can you post a sample? SW is independent of langage setting...

**Comment by iDevelopper** [comment]
Yes, you are right! I tested it with one of my sample. It just remains to find out why.

**Comment by iDevelopper** [comment]
No, sorry it works! Check your target/action of your buttons for opening left and right. You have to test the langage and invert revealToggle and rightRevealToggle if RTL (and rear/front controller too).

**Comment by iDevelopper** [comment]
[SWArabic.zip](https://github.com/John-Lluch/SWRevealViewController/files/447073/SWArabic.zip)

**Comment by kirankhalkar** [comment]
Hi ,
hey it working.. Thanks for your help @iDevelopper
