### ISSUE TITLE
Issues with front view offset

### ISSUE THREAD

**Issue by ghost** [John-Lluch/SWRevealViewController#619]
I try to set some space between left screen side and front view controller that i can see rearview controller (menu). i find this method and change the location variable from 0 to 70. This solution helps me but i see only black line instead menu. But when i click button or swipe this black line become hide or something like this. I will be grateful for any help! 

P.S. On screenshots black bottom line is normal, only left screen side. 
http://take.ms/mWm08
http://take.ms/dvnr9

```
- (CGFloat)frontLocationForPosition:(FrontViewPosition)frontViewPosition
{
    CGFloat revealWidth;
    CGFloat revealOverdraw;
    CGFloat location = 70;

    int symetry = frontViewPosition<FrontViewPositionLeft? -1 : 1;
    [_c _getRevealWidth:&revealWidth revealOverDraw:&revealOverdraw forSymetry:symetry];
    [_c _getAdjustedFrontViewPosition:&frontViewPosition forSymetry:symetry];
    if ( frontViewPosition == FrontViewPositionRight )
        location = revealWidth;
    else if ( frontViewPosition > FrontViewPositionRight )
        location = revealWidth + revealOverdraw;
    return location*symetry;
}
```

**Comment by iDevelopper** [comment]
Why don't do this with a opaque shadow on front view, without modify the SW class code?

**Comment by iDevelopper** [comment]
I don't understand, you never want to display the front view entirely? Can you explain more please? Can you provide a drawing? What is for the space between rear and front views?

**Comment by ghost** [comment]
The space not between rear and front controllers, the space between left size of the screen and front controller like in screen shot: http://take.ms/ZmVgu 
I don't want to display front view entirely because i want to show buttons with images such as home, message etc.
I try to set CGReactMake for the viewController, i try to do it because when i set http://take.ms/21uoa

> [_viewController.view setBackgroundColor:[UIColor redColor]];

the black like change color, but if use CGReactMake with X coordinate for example 70 nothing to change, black line doesn't have offset at 70 from x coordinate. 

```
        UIWindow *window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
        self.window = window;

        MainViewController *mainViewController = [[MainViewController alloc] init];
        RearViewController *rearViewController = [[RearViewController alloc] init];

    UINavigationController *mainNavigationController = [[UINavigationController alloc] initWithRootViewController:mainViewController];
    UINavigationController *rearNavigationController = [[UINavigationController alloc] initWithRootViewController:rearViewController];
    SWRevealViewController *revealController = [[SWRevealViewController alloc] initWithRearViewController:rearViewController frontViewController:mainNavigationController];
        revealController.delegate = self;
        self.viewController = revealController;
       // [_viewController.view setBackgroundColor:[UIColor redColor]];
        [_viewController.view setFrame:CGRectMake(70, 0, 768, 1024)]; 
        NSLog(@"heignt = %f, width = %f", _viewController.view.frame.size.height , _viewController.view.frame.size.width);
        NSLog(@"x coord = %f", _viewController.view.frame.origin.x);
        self.window.rootViewController = self.viewController;    
        [self.window makeKeyAndVisible];
```

**Comment by iDevelopper** [comment]
You have to play with rearViewRevealWidth ans some delegate methods. This is one of my sample I modified:

[SWSample.zip](https://github.com/John-Lluch/SWRevealViewController/files/463250/SWSample.zip)

**Comment by ghost** [comment]
Thanks for your sample, you help me a lot! Now when project start i can see the my buttons with icons but when i press bar button the front controller sliding to zero x coordinates but when use swipes it works i think i can solved this problem by myself(in your example everything works well, i have a problems because use xib). Thank you one more time!

**Comment by iDevelopper** [comment]
Check your button's target and action, target must be your own (self.revealViewController.delegate i.e. RevealViewController.m in my sample, and action the reveal selector (must be declared in RevealViewController.h)
