### ISSUE TITLE
How to initially open Rear View ?

### ISSUE THREAD

**Issue by ChechkovEugene** [John-Lluch/SWRevealViewController#629]
If i put revealToggle in viewWillAppear than i have a little bit blinking . If i put revealToggle in viewDidLoad or viewDidLayoutSubviews Front/Rear view don't layout properly
![simulator screen shot oct 11 2016 1 26 29 pm](https://cloud.githubusercontent.com/assets/2751087/19267246/66eb0b1a-8fb6-11e6-83f5-3caa4993504c.png)
Is there proper way to make Rear View initially open?
Thanks for the help

**Comment by iDevelopper** [comment]
Try:

```
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        revealViewController().setFrontViewPosition(.right, animated: true)
    }
```

**Comment by ChechkovEugene** [comment]
Same thing (

**Comment by iDevelopper** [comment]
This is your constraints perhaps. I made a little test:

[SWLayout.zip](https://github.com/John-Lluch/SWRevealViewController/files/523953/SWLayout.zip)

**Comment by ChechkovEugene** [comment]
Oh. My issue in layout. Thanks !
