### ISSUE TITLE
Bloc/Disable background view when sliding

### ISSUE THREAD

**Issue by alaaghribi** [John-Lluch/SWRevealViewController#63]
I'm using your awesome library in my project, all is perfect except that I feel the need to bloc(or disable) the background view when sliding/enabling the menu.
Is that possible? Can you add that into the lib?

Thank you for your response.

**Comment by bharned3** [comment]
How do you implement this into a swift project?

**Comment by bassebaba** [comment]
@bharned3, I got it to work this way. No idea if its correct, started iOS development like a week ago :P Really frustrating with the mix of objective-c and swift.

1. Add "SWRevealViewControllerDelegate" to your controller
2. in "viewDidLoad()", do: self.revealViewController().delegate = self
3. use @OguzKupusoglu code like this:
```
    func revealController(revealController: SWRevealViewController!, didMoveToPosition position: FrontViewPosition) {
        self.tableView.userInteractionEnabled = (revealController.frontViewPosition == FrontViewPosition.Right) ? false : true
        println("didMoveToPosition: \(self.tableView.userInteractionEnabled)")
    }
```

Im using a table view, just modify the first row in (3) to suit your needs.

**Comment by bharned3** [comment]
I found this yesterday and it worked for me: In the view did load in my front view I just added this line..

self.view.addGestureRecognizer(self.revealViewController().tapGestureRecognizer())

**Comment by Swapna2606** [comment]
@bharned3 works perfect.. thanks.. never knew it wld be so simple.. :)

**Comment by slavikshen** [comment]
My solution

- (void)_setAllScrollView:(UIView*)view enable:(BOOL)enable {
    if( [view isKindOfClass:[UIScrollView class]] ) {
        [view setUserInteractionEnabled:enable];
        return;
    }
    for( UIView* v in view.subviews ) {
        [self _setAllScrollView:v enable:enable];
    }
}

- (void)revealController:(SWRevealViewController *)revealController didMoveToPosition:(FrontViewPosition)position {

    UINavigationController* navController = (UINavigationController*)revealController.frontViewController;
    UIViewController* viewController = navController.topViewController;
    UIView* view = viewController.view;
    BOOL enable = !( position == FrontViewPositionRight );
    
    [self _setAllScrollView:view enable:enable];
    
}

**Comment by jianglin612** [comment]
Doing this gives me an error: self.view.addGestureRecognizer(self.revealViewController().tapGestureRecognizer())

How do I add it?

**Comment by jianglin612** [comment]
Where is didMoveToPosition implemented? it never really gets used in my code

**Comment by ammoqq** [comment]
@John-Lluch answer was great
My swift version:

    func revealController(revealController: SWRevealViewController, willMoveToPosition position: FrontViewPosition){
        if(position == FrontViewPosition.Left) {
            self.view.userInteractionEnabled = true
        }else {
            self.view.userInteractionEnabled = false
        }
    }
    
    func revealController(revealController: SWRevealViewController, didMoveToPosition position: FrontViewPosition){
        if(position == FrontViewPosition.Left) {
            self.view.userInteractionEnabled = true
        } else {
            self.view.userInteractionEnabled = false
        }
    }

You implement didMoveToPostition in your FrontViewController (the name is just what i call it in my project), then in viewDidLoad of that same FrontViewController you add  these 2 lines (swift code):
    self.revealViewController().delegate = self
    self.revealViewController().panGestureRecognizer()

Additionaly u need to remember to add delegate to class FrontViewController: SWRevealViewControllerDelegate
