### ISSUE TITLE
Back Button for Menu item pages

### ISSUE THREAD

**Issue by errabelli09** [John-Lluch/SWRevealViewController#636]
In the menu my Deals page as front view controller. that is Persionalized Deals.
And One more Help VC

If i am selecting help from the menu. that page having a back button.
When i am clicking on back button it will return to Front page (Personalized Deals)

Can  you help me in this
`

**Comment by iDevelopper** [comment]
Use UINavigationControllerDelegate:
- (void)navigationController:(UINavigationController *)navigationController willShowViewController:(UIViewController *)viewController animated:(BOOL)animated {

**Comment by errabelli09** [comment]
Thanks again. Actually you are helped me 2 hours back on some others question.
