### ISSUE TITLE
Passing arguments from menu to controllers (part of tabbar)

### ISSUE THREAD

**Issue by kmyn** [John-Lluch/SWRevealViewController#637]
I need to include the slide menu with a tab bar controller having two controllers. I followed the sample code posted in thread #563  by @iDevelopper. It worked perfect!

I'm having a slightly different requirement i.e, when a user selects an option from the menu, an argument has to be passed to the destination view controller and a label on it should get updated with the argument. This is similar to #633 but Swift based

When the user is in ViewController1 & selects item 1 from the menu, I expect ViewController1  to reload and update the label. But, that does not seem to happen i.e., ViewController1 is not refreshed.

I've attached the zip folder of the code. Any help is appreciated.

[SWTabBarSwift Args.zip](https://github.com/John-Lluch/SWRevealViewController/files/563078/SWTabBarSwift.Args.zip)

**Comment by iDevelopper** [comment]
Use some properties with observers:

[SWTabBarSwift Args.zip](https://github.com/John-Lluch/SWRevealViewController/files/563424/SWTabBarSwift.Args.zip)

**Comment by kmyn** [comment]
This works perfect! Thanks! 

Two followup questions: 
1. In RevealViewController.swift, is the prepare segue method required? I don't think it is required.
2. Just like the way the arguments are passed from the slide menu to the controller, can the reverse be possible? i.e., in the MenuTableViewController::viewDidLoad() method of the menu, I would like to detect from which controller the menu button was clicked.

**Comment by iDevelopper** [comment]
1. Not required (only if you want to pass an argument before the viewDidLoad of the vc.
2. To detect from which controller the menu button was tapped, you can retrieve it with the delegate method of SW:

```
func revealController(_ revealController: SWRevealViewController!, willMoveTo position: FrontViewPosition)
```

or in viewWillAppear on MenuTableViewController.

[SWTabBarSwift Args 2.zip](https://github.com/John-Lluch/SWRevealViewController/files/565780/SWTabBarSwift.Args.2.zip)

**Comment by kmyn** [comment]
Cool! This works. Thanks a lot @iDevelopper 👍
