### ISSUE TITLE
Back button in swift

### ISSUE THREAD

**Issue by athzuma** [John-Lluch/SWRevealViewController#638]
How to menu button to return to the initial view in swift?
I try it:

`var revealController = self.revealViewController`
`var newFrontController: UIViewController? = nil`
`var frontViewController = HomeViewControler()`
`//or`
`//let frontViewController:UIViewController = UIStoryboard(name: "StoryboardC", bundle: nil).instantiateViewControllerWithIdentifier("Home") as UIViewController`
`newFrontController = UINavigationController(rootViewController: frontViewController)`
`revealController().pushFrontViewController(newFrontController, animated: true)`

**Comment by iDevelopper** [comment]
From where? Could you explain a little more, please? Could you show a screenshot of your storyboard?

**Comment by athzuma** [comment]
Hello, thank you for your attention.
On the menu I have a button to go back to my main screen (HomeViewController).
When I go to contact, I would like to return to homeViewController
![captura de tela 2016-11-01 as 06 38 00](https://cloud.githubusercontent.com/assets/1594418/19884084/185e1218-9fff-11e6-96f0-fd8686a0f1e5.png)

**Comment by iDevelopper** [comment]
Then push it (your HomeViewController) with SWRevealViewController. You can instantiate it from storyboard or save it in a property the first time it is loaded.

**Comment by athzuma** [comment]
I added a segue "reveal view controller controller push" the button Menu to NavMapaViewController, but it did not work.
"libc++abi.dylib: terminating with uncaught exception of type NSException"

**Comment by athzuma** [comment]
It worked! thank you!
