### ISSUE TITLE
Add view to SW_Front navigations controller from button in SW-rear VC

### ISSUE THREAD

**Issue by ghost** [John-Lluch/SWRevealViewController#639]
So I have a navigation controller as my Front VC and a few buttons in my Rear VC, now when I am in the SW_rear, I want to click one of the buttons this then adds another VC on top of the navigation controller stack and dismissed the SW_Rear VC. I have tried many different ways of doing this but have not achieved it yet any help would be most apricated

**Comment by iDevelopper** [comment]
You closed the issue. You don't need help anymore?

**Comment by ghost** [comment]
Nope thanks to the wonderfully written code of SWRevealViewController the answer was already there, but thank you anyway
