### ISSUE TITLE
Present a cell view as a modular view with the Main view still in background.

### ISSUE THREAD

**Issue by munibrahman** [John-Lluch/SWRevealViewController#641]
Hi,

I would like to present a selected table cell as a modular view, one that pops up, while the main screen or Home view is still in the background. And once you press a button inside the selected view, it depreciates and the home screen is displayed again.

If you would like to see such an example, the Uber app uses this sort of design pattern. Where clicking on any item in the sidebar menu simply presents a modular view, without leaving the main map view. And once a user taps on the little "x" it disappears and so does the SWRevealViewController.

Gif is a bit slow, but it should get the point across.
![untitled](https://cloud.githubusercontent.com/assets/15371881/20042835/2d738b72-a43e-11e6-8386-e94782969e09.gif)

Many Thanks.

**Comment by iDevelopper** [comment]
Simply close the side menu and tell the front view controller to present your modal view controller:

```
revealViewController().setFrontViewPosition(.left, animated: true)
revealViewController().frontViewController.present(yourController, animated: true, completion: nil)
```

if you want the side menu on top, you have to use front view controller for the menu and the right view controller for the main view, then:

```
revealViewController().setFrontViewPosition(.left, animated: true)
revealViewController().rightViewController.present(yourController, animated: true, completion: nil)
```

**Comment by munibrahman** [comment]
I will try this soon and post results.

Silly Question: Which file should I add this into? Home view controller or any of the table cell view controllers? 

Thanks

**Comment by iDevelopper** [comment]
yourController?

The controller you want to be presented on top of the front view controller.

**Comment by munibrahman** [comment]
I am still confused, apologies for my stupid questions but this is my first app that I use any sort of frameworks in.

My initial controller, when the app starts is called HomeViewController, and I want to show ProfileViewController modally, along with settingsVC, purchaseVC and so on. Where would I add the above lines?

I am also using storyboard so my layout looks like this. 

![screen shot 2016-11-11 at 9 36 23 pm](https://cloud.githubusercontent.com/assets/15371881/20235725/5d423430-a857-11e6-825e-96b58e610bd7.png)

**Comment by iDevelopper** [comment]
You can't do this like that. Your segues between the table view cells and yours controllers will present the controllers on the table view, not on the home view controller. Then here a sample:

[SWModal.zip](https://github.com/John-Lluch/SWRevealViewController/files/587135/SWModal.zip)

**Comment by munibrahman** [comment]
Thank you SO much for giving me an example. Very very very much appreciated. Makes a lot of sense now. Thanks again.
