### ISSUE TITLE
Issue with sw_front Segue between login verification and home screen

### ISSUE THREAD

**Issue by QuintonC** [John-Lluch/SWRevealViewController#642]
Hi, I've been going at this for a while now and I'd love to hear some potential solutions. Essentially, I'm trying to incorporate a right menu/nav, but when I attempt to go log into the app and go to my home screen/logged in landing, the app crashes. The app doesn't crash when the segue is a modal,etc. But it continues to crash while it's set to _reveal view controller set controller_. 

Here is the console output when the app crashes:

> 2016-11-09 22:48:58.178 Freely Market[20457:1633651] -[Freely_Market.LoginViewController _performTransitionOperation:withViewController:animated:]: unrecognized selector sent to instance 0x7ff380614ce0

Here is a view of what my storyboard looks like:

![Image of Main.storyboard](http://i.imgur.com/THeL6QU.png)

And here is the line that is highlighted when highlighting all Objective-C issues:

`if ( operation != SWRevealControllerOperationNone )
        [rvc _performTransitionOperation:operation withViewController:dvc animated:NO];`

Just for clarification, the segue between logged in, and the segue between it and the table view are all set properly to their _sw_front, sw_rear values_.

I'm still not quite sure how to fix this issue, hence the issue. Any help is appreciated.

**Comment by iDevelopper** [comment]
Not sure I understand the question. Could you show more of the storyboard with arrow annotation to comment the segues?

**Comment by QuintonC** [comment]
Hi Patrick, 

Thanks so much for the reply. 

I've annotated it below, hopefully this gets the message across.

![Picture of annotations](http://i.imgur.com/ILOCAZW.png)

The user enters their login information prior to pressing 'Login' (Identified as 1). After pressing login, the application performs some checks to see if the user has entered valid information for logging in. After the program successfully validates the user information, it should proceed to segue with 'sw_front' (identified as 2). 2 Should effectively lead the user to 3, known as the home page of the application. From the home page of the application, the user can press the Menu navigation (4). Once the user presses the menu navigation, they should see the menu (5) slide over to the right.

However, my application is getting hung up and crashing, throwing the following error:

> 2016-11-09 22:48:58.178 Freely Market[20457:1633651] -[Freely_Market.LoginViewController _performTransitionOperation:withViewController:animated:]: unrecognized selector sent to instance 0x7ff380614ce0

It has identified the following line of code when using breakpoints:
`if ( operation != SWRevealControllerOperationNone ) [rvc _performTransitionOperation:operation withViewController:dvc animated:NO];`

**Comment by iDevelopper** [comment]
Ok, where is the reveal view controller? Where is the segue sw_right? Is there a rear view controller too?

And

![2016-11-12_16-42-30](https://cloud.githubusercontent.com/assets/1782450/20239068/82d5ee0c-a8f8-11e6-9fe7-d2e0c4a081bc.png)

**Comment by QuintonC** [comment]
That segue is the sw_rear, and when pressing the button, it was trigger that segue, which I can see why that was the issue, but I thought that was the way that it had to be laid out after watching this video: https://www.youtube.com/watch?v=EWDNScxZ0YU

**Comment by QuintonC** [comment]
So from what I can tell, the application thinks that it is using this selector: `_performtransitionOperation:withViewController:animated:]`

So from this line: 

`if ( operation != SWRevealControllerOperationNone )
        [rvc _performTransitionOperation:operation withViewController:dvc animated:YES];`

But that is obviously not Swift, and is Objective-C. So I'm not quite sure how to get my segue to actually operate as it should.

This is where the segue is being called from after verifying the user's login information.

```
} else if (username.isEqual(to: usernameV!) && password.isEqual(to: passwordV!)) {

       self.performSegue(withIdentifier: "sw_front", sender: self)
```

And this is where I am stuck, maybe it is just an issue with Objective-C and Swift clashing? Other's have gotten this add-in to work just fine without any issues, but I have not. Maybe it is because I am verifying user login information and then passing it onto this new screen, where as others just start at the basic screen.

Any help is appreciated.

**Comment by iDevelopper** [comment]
I would like to see the entire story board or can you share it? Otherwise, can you write a sample project to reproduce the issue?

**Comment by QuintonC** [comment]
I'm not positive that the issue lies within the storyboard, but I can certainly show you the image.

Alternatively, I did send you an email. It may be beneficial that we set up a screen share as that would allow you to take a more in-depth look at the project.

![Storyboard](http://i.imgur.com/lZoLJKA.png)

1: Landing Screen, user can choose to register or login
2: Register screen, user inputs their information here
3: After registering, the user is directed here unless they have already selected to be taken here from the landing screen.
4: Forgotten password screen, user is taken here if they select 'Forgot Password' from the login screen. User will verify their information here.
5: Forgotten password reset page, user changes their password here. After changing their password, they are taken to the login page.
6: The main screen. This is where all of the listings will be at for the application, and where the user can fully interact with the application.
7: The navigation menu.

Please, feel free to email me so we can set up screen share session if you feel that would be best.

You can reach me at quintonchester@gmail.com

**Comment by iDevelopper** [comment]
1) Then 3 is your Reveal view controller? 
2) What is the kind of segue between 1 and 3? (kind AND identifier)
3) What is the kind of segue between 3 and 6? (kind AND identifier)
4) What is 8?

**Comment by QuintonC** [comment]
3 would be the reveal view controller, yes.

The segue between 1 and 3 is a _Show (e.g. Push)_, does not have an identifier.
The segue between 3 and 6 is is indirect as there is a navigation controller in between it. But the segue between 3 and the navigation controller is _reveal view controller set view controller_ and is **sw_front**.

Edit: 

You can ignore 8, it's something that will be referenced from the menu later on. It was a test earlier on in the application.

**Comment by iDevelopper** [comment]
Then when you launch the app, 6 appear first?

**Comment by QuintonC** [comment]
1 appears first. If the user has an account, they press login. If they don't have an account, then they will be redirected to 2 after trying to sign in. After they sign in, they should be taken to 6.

**Comment by iDevelopper** [comment]
Yes sorry, but when the user has an account, he tap Log in. And Show (e.g. Push) is performed -> SWRevealViewController. Then how do you do to avoid SW to show 6 to allow the user to grab id and password?

**Comment by QuintonC** [comment]
It doesn't go to SWRevealViewController because the login screen has its own class, LoginViewController.swift

And that's where the issue lies, I'm unsure how to integrate the two so that they speak to one another.

Because LoginViewController is where the function for validating the username/password combination is housed. sw_front is called here:

```
        if usernameV == nil || passwordV == nil {

            let alertController = UIAlertController(title: "Oops!", message: "It appears you have not registered, please register first and then proceed to logging in.", preferredStyle: .alert)
            let OKAction = UIAlertAction(title: "OK", style: .default) {
                (action:UIAlertAction) in
                self.performSegue(withIdentifier: "registerRedirect", sender: self)
            }
            alertController.addAction(OKAction)
            self.present(alertController, animated: true, completion:nil)

        } else if (username.isEqual(to: "") || password.isEqual(to: "")) {

            let alertController = UIAlertController(title: "Oops!", message: "Please be sure to enter login information before attempting to login.", preferredStyle: .alert)
            let OKAction = UIAlertAction(title: "OK", style: .default) {
                (action:UIAlertAction) in
                print("Alert Dismissed")
            }
            alertController.addAction(OKAction)
            self.present(alertController, animated: true, completion:nil)

        } else if (username.isEqual(to: usernameV!) && password.isEqual(to: passwordV!)) {

            self.performSegue(withIdentifier: "sw_front", sender: self)

        } else {

            let alertController = UIAlertController(title: "Oops!", message: "Password and Username pair not found.", preferredStyle: .alert)
            let OKAction = UIAlertAction(title: "OK", style: .default) {
                (action:UIAlertAction) in
                print("Alert Dismissed")
            }
            alertController.addAction(OKAction)
            self.present(alertController, animated: true, completion:nil)
        }
```

So the problem is that when it attempts to do the segue for sw_front, it is sending an invalid selector. Recall the error that is being thrown:

> 2016-11-12 22:21:04.861 Freely Market[16811:3049283] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Freely_Market.LoginViewController _performTransitionOperation:withViewController:animated:]: unrecognized selector sent to instance 0x7fc71950ea30'

So from what I can tell, and I'm pretty sure we're both on the same page here, is that the app is not allowing SWRevealViewController.m and LoginViewController to speak to one another.

**Comment by iDevelopper** [comment]
Yes, I don't think you can do like that. SWRevealViewController is a container view controller (as UINavigationController or UITabBarController). You can't have an user interface here. Then your login view controller have to be the first front view controller and the reveal view controller the entry point. Set the new front view controller when username & password are ok in the first front view controller (LoginViewController)

**Comment by QuintonC** [comment]
So, you're saying to create a view controller after the login view controller that directs the user to that view controller pending everything is okay? And if it is okay, then to continue on with the progression through the application towards the logged in screen?

I'll give it a shot and see what I can find out.

Edit: What segue would be best between the login UI and the reveal view controller?

**Comment by QuintonC** [comment]
Good news, it now works. 

Thanks so much for your help! 

I couldn't get the menu to work on the right side, but it now works on the left side. Not a huge deal to switch sides. 

Cheers!

Edit:

For those who come here later, here is a picture of the solution outlined by Patrick.

Create a view controller in between the login verification. Make the segue between the login verification and the SWRevealViewController 'Present Modally'. From there, create your segues to the main menu of the logged in portion, and then from there you should be linked to where you would like.

![Image of storyboard](http://i.imgur.com/wkvfKhF.png)

**Comment by iDevelopper** [comment]
Personally I would do like this:

[SWLoginTest.zip](https://github.com/John-Lluch/SWRevealViewController/files/587915/SWLoginTest.zip)

**Comment by iDevelopper** [comment]
With right menu:

[SWLoginTest 2.zip](https://github.com/John-Lluch/SWRevealViewController/files/587943/SWLoginTest.2.zip)
