### ISSUE TITLE
Table View Controller Cells Constraints 

### ISSUE THREAD

**Issue by subhay389** [John-Lluch/SWRevealViewController#643]
Hi, 
I tried to use the RightMenu and it worked but the items in the rightmenu seems to be hidden behind the main view. Can you help me fix it. 

[a.zip](https://github.com/John-Lluch/SWRevealViewController/files/584043/a.zip)
<img width="375" alt="screen shot 2016-11-10 at 12 41 40 pm" src="https://cloud.githubusercontent.com/assets/13982554/20187660/27a259e6-a743-11e6-8223-ece924340d28.png">

**Comment by iDevelopper** [comment]
self.revealViewController().rightViewRevealOverdraw = 0

**Comment by iDevelopper** [comment]
Thanks !
