### ISSUE TITLE
viewController Disabled

### ISSUE THREAD

**Issue by rovialex** [John-Lluch/SWRevealViewController#648]
Hi All. I just started to work in a project that was already using this framework. Although I think is great and it's working fine, we recently found that when we come back from a viewController to another using popViewController the new main view gets disabled and it comes alive only if we open the side drawer. 

I think there's a situation with the gestures but I can't seem to find the solution. All I want is when we come back to a view it keeps working as it was.

Thanks in advances.

**Comment by iDevelopper** [comment]
Not enough detail but check if userInteractionEnabled is not set to false.

**Comment by rovialex** [comment]
Hi, thanks for your response. I have set my self.view.userInteractionEnabled to YES. But my viewController is still not working. 

By the way this self.view is the one that contain the panGestureRecognizer : [self.view addGestureRecognizer:self.revealViewController.panGestureRecognizer];

I have even implemented these delegates: 
(void)revealController:(SWRevealViewController *)revealController willMoveToPosition:(FrontViewPosition)position
{
	if(position == FrontViewPositionLeft) {
		self.view.userInteractionEnabled = YES;
	} else {
		self.view.userInteractionEnabled = NO;
	}
}

- (void)revealController:(SWRevealViewController *)revealController didMoveToPosition:(FrontViewPosition)position
{
	if(position == FrontViewPositionLeft) {
		self.view.userInteractionEnabled = YES;
	} else {
		self.view.userInteractionEnabled = NO;
	}
}

And they are called when I go to the view or when I go from the view to the sideDrawer but when I hit back from the other view and I pop back they aren't called.

**Comment by iDevelopper** [comment]
Ok, normal, how do you push and pop the view controller in question?

**Comment by rovialex** [comment]
This is how I push the view controller: 
IniciarSesionViewController * vc = [storyboard instantiateViewControllerWithIdentifier: @"iniciosesionid"]; 
 
UINavigationController* navController =      
     (UINavigationController*)self.revealViewController.frontViewController;
[navController pushViewController:vc animated:YES];
[self.revealViewController setFrontViewPosition: FrontViewPositionLeft animated: YES];

And in IniciarSesionViewController when I hit back button I do this:
 NSLog(@"intentando cerrar");
    if (self.navigationController) {
        NSLog(@"navigation");
        [self.navigationController popViewControllerAnimated:YES];
        self.navigationController.navigationBarHidden=NO;
    }
    [self dismissViewControllerAnimated:YES completion:nil];

**Comment by iDevelopper** [comment]
Why an action for back button, it will be automatic.

Why [self dismissViewController...] ?

**Comment by rovialex** [comment]
Actually I really don't know. As I first said I am new here and this project is already working and they left this little bug here.

I can tell you this is a button because this view is kind of a login view, so they hide the navigation bar, but they need to navigate back (in some cases I think) and they put a button with the back action I just showed you.

I even have looked into SWRevealViewController.h and found the moment when they use userInteractionEnabled to disable the view controller and have commented it and it still gets disabled and in this disable view controller I open and close the side drawer and it gets back to normal.

It seems pretty strange to me

**********   Update   ***********
I have actually showed the navigation controller to work with the back button of it and it behaves the same.

**Comment by iDevelopper** [comment]
If you don't need a navigation controller, just present the IniciarSesionViewController modally. No need to push it with the navigation controller. [self.revealViewController.frontViewController presentViewController: ...]; and in your back action: [self dismissViewControllerAnimated:YES completion:nil];

**Comment by rovialex** [comment]
Thank you for your advised. I finally found the problem after carefully looking into the project's code. They were changing self.view.userInteractionEnabled in some other unexpected and illogical place. Now it's working correctly thank you very much for your time and trying to help me.

**Comment by iDevelopper** [comment]
Great!
