### ISSUE TITLE
Can I load rear view controller when lauch application?

### ISSUE THREAD

**Issue by mvn-anhnguyen-h-hn** [John-Lluch/SWRevealViewController#653]
Reveal controller just only init when first time I call function revealToggle in frontViewController. So Can I load rear view controller when lauch application?

**Comment by iDevelopper** [comment]
Yes with storyboard entry point or in AppDelegate initWithFrontViewController:rearViewController or precise your question

**Comment by mvn-anhnguyen-h-hn** [comment]
@iDevelopper : Thank you for you help! Sorry for my mistake. I want to load rearview (viewcontroller in left side) when launch application. Do you have any idea with this issue

**Comment by iDevelopper** [comment]
In your front view controller (in viewDidLoad), call:

```
        revealViewController().setFrontViewPosition(.right, animated: false) // or true
```
