### ISSUE TITLE
Issue in gestures while swipe the menu

### ISSUE THREAD

**Issue by preethapre** [John-Lluch/SWRevealViewController#654]
Hi @John-Lluch ,first i would like you to say thanks for developing the useful library,this is useful for me,and i faced tiny issue in that,while am swiping the menu in very first time there is no response after that swipe the menu that time working fine,and i refered many solutions(SWRevealViewController->Issues),links are  https://github.com/John-Lluch/SWRevealViewController/issues/577,https://github.com/John-Lluch/SWRevealViewController/issues/649 but stil am not getting any solutions for that,so please if you are providing some solution for this much appreciated.

Regards
Preetha.

**Comment by iDevelopper** [comment]
"while am swiping the menu in very first time there is no response after that swipe the menu that time working fine"

Not understand. What do you mean by response? and time working fine?

**Comment by preethapre** [comment]
Entering the view in first the menu is not swipped after i opened some other view then its working fine!

**Comment by preethapre** [comment]
And finally got an solutions
