### ISSUE TITLE
Swipe from revealViewController

### ISSUE THREAD

**Issue by mvorisis** [John-Lluch/SWRevealViewController#659]
Hi 

Is it possible to swipe the slider from inside the revealview?

I'm sorry if this question has been asked again but i couldn't find something.

Thanks in advance

**Comment by iDevelopper** [comment]
Which slider?

**Comment by mvorisis** [comment]
The sw_rear view, now i can close it if I tap or swipe from my front view but I can't swipe from th sw_rear view

**Comment by iDevelopper** [comment]
You can add the SW pan gesture to the rear view, but this pan gesture can be added only to one view

**Comment by iDevelopper** [comment]
You can also subclass SWRevealViewController (don't forget to change the class in the storyboard), and add the pan gesture recognizer to the reveal view:

```
import UIKit

class RevealViewController: SWRevealViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        self.view.addGestureRecognizer(panGestureRecognizer())
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}
```

**Comment by mvorisis** [comment]
Ok it worked thanks for the help
