### ISSUE TITLE
Setting sw_front for SWRevealViewControllerSegueSetController

### ISSUE THREAD

**Issue by A-Lim** [John-Lluch/SWRevealViewController#660]
I'm trying to set the sw_front segue based on the user device. If its Ipad, then I want the sw_front to be eg. IpadViewController and if its an Iphone, the sw_front should be IphoneViewController. How do I implement this?

**Comment by A-Lim** [comment]
Found the solution from issue #225

**Comment by iDevelopper** [comment]
Two storyboards, one for iPhone and one for iPad, or one controller checking the device type.

**Comment by iDevelopper** [comment]
An other solution would be to subclass SWRevealViewController and implement shouldPerformSegue:sender:

Check the device for sw_front, set the correct controller to front view controller and return NO;
