### ISSUE TITLE
Rear View is not working after tapping on top left burger Menu

### ISSUE THREAD

**Issue by attiqueullah** [John-Lluch/SWRevealViewController#661]
Hi, I have created multiple rear views in the app but when multiple rear view comes the burger menu didnt work fine . Please tell me where is the issue actually is. Thanks

**Comment by iDevelopper** [comment]
"did not work fine" ? What is not working. Please can you develop ?

**Comment by attiqueullah** [comment]
Kindly follow your example 3 . This is the scnerio actually
When you go into the example press on 5th tab in which multiple rear view controller will be shown to you after that again tap in first tab and then press white burger menu it didnt slide out . this is the issue  actually.

**Comment by iDevelopper** [comment]
This is not my sample, I am an user like you. In this sample there are two instances of SWRevealViewController. You tap first on ... More, and after you tap on heart.png or on image 1? For my understanding all is OK

**Comment by attiqueullah** [comment]
You tap first on ... More, and after you tap on heart.png or on image 1 after that click on top left corner burger menu image the didnt slide out to right Have you check this ?

**Comment by iDevelopper** [comment]
If you tap on heart.png you come back to the first reveal instance, then tap on the menu button close or open the first menu, it is OK. If you tap on image 1, then you are still in the second reveal instance, the tap on the menu button open or close the second menu, it is OK. But this is an example and it would be better to explain what you want to do.

**Comment by attiqueullah** [comment]
In between have you tap on more and then tap on heart image and then tap on
menu is it working ?

**Comment by iDevelopper** [comment]
[2016-12-20_15-46-19.mp4.zip](https://github.com/John-Lluch/SWRevealViewController/files/663975/2016-12-20_15-46-19.mp4.zip)

**Comment by attiqueullah** [comment]
Thank a Lot i have resolve the issue . Thanks Again :)
