### ISSUE TITLE
SWRevealViewController work with TabbarController

### ISSUE THREAD

**Issue by xuanzi23** [John-Lluch/SWRevealViewController#664]
Hi,
I working on SWRevealViewController with TabBarController together.
But I facing one problem, after I click 1 of the cell go to the new view with UITabBar.
Then I press the UITabBar will go back to the TabBarController with selected index.

```
  func tabBar(tabBar: UITabBar, didSelectItem item: UITabBarItem) {
        if(item.title == "Hi")
        {
            let tabBarController = self.storyboard?.instantiateViewControllerWithIdentifier("TabBarController") as! TabBarController
            let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
            tabBarController.comeinID = 0
            appDelegate.window?.rootViewController = tabBarController
         
        }
        else
        {
            let tabBarController = self.storyboard?.instantiateViewControllerWithIdentifier("TabBarController") as! TabBarController
            let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate

            tabBarController.comeinID = 1
            appDelegate.window?.rootViewController = tabBarController
        }
    }
```

But the side menu button does not working after that.
I think the problem is because click from the UITabBar straight go to the TabBarController without go through the SWRevealViewController.
So, how I can change the method to do it?

**Comment by iDevelopper** [comment]
Why do you instantiate a new tab tab controller each time an item is selected? You have already your tab bar controller in the hierarchy. You replace your reveal view controller (witch is the root view controller, I suppose, with a new instance of a tab bar controller).

**Comment by xuanzi23** [comment]
@iDevelopper the situation is like this.
First the SWRevealController will set go to "B" viewcontroller So I press the side menu button will open the side menu table and press the first cell go to "A" viewcontroller.

In "A" viewcontroller I got UITabBar, I press "A1" tab bar will go back to the "B" viewcontroller but when i go back the side menu button doest not work.

![untitled-1](https://cloud.githubusercontent.com/assets/19340910/21492356/f172db9a-cc3e-11e6-8616-e4bd0cdf8f13.jpg)

**Comment by iDevelopper** [comment]
Where are the SWRevealViewController and the sw_front and sw_rear segues?

**Comment by xuanzi23** [comment]
The SWRevealViewController is "D" 
sw_rear is "E"
sw_front is "F"

![untitled-1-1](https://cloud.githubusercontent.com/assets/19340910/21493149/e68cf55c-cc44-11e6-9c92-3ec5df23dc8b.jpg)

**Comment by iDevelopper** [comment]
In B save the instance of tab bar controller:

```
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let appDelegate = UIApplication.shared.delegate as! AppDelegate
        appDelegate.tabBarController = self.tabBarController
        
        menuButton.target = self.revealViewController()
        menuButton.action = #selector(SWRevealViewController.revealToggle(_:))
        
        revealViewController().tapGestureRecognizer()
        revealViewController().panGestureRecognizer()
    }
```
In A, retrieve it and push it with reveal view controller:

```
    func tabBar(_ tabBar: UITabBar, didSelect item: UITabBarItem) {
        if item.title == "Hi" {
            let appDelegate = UIApplication.shared.delegate as! AppDelegate
            let tabBarController = appDelegate.tabBarController
            tabBarController?.selectedIndex = 0
            revealViewController().pushFrontViewController(tabBarController, animated: true)
        }
    }
```

**Comment by iDevelopper** [comment]
[SWTabbarSample.zip](https://github.com/John-Lluch/SWRevealViewController/files/673761/SWTabbarSample.zip)

Hope it helps!

**Comment by xuanzi23** [comment]
@iDevelopper Greats! It working good with me!
