### ISSUE TITLE
What function does toggle calls?

### ISSUE THREAD

**Issue by mvorisis** [John-Lluch/SWRevealViewController#665]
Hi 

I was wondering what function does the close/toggle of slider calls.
I mean if i press the button that opens the slider and then I press it again to close it.
Thanks in advance

**Comment by iDevelopper** [comment]
- (IBAction)revealToggle:(id)sender;

**Comment by mvorisis** [comment]
I mean which function of the front view (like viewdidload, viewdidappear etc)

**Comment by iDevelopper** [comment]
In viewDidLoad:

```
class ViewController: UIViewController {

    @IBOutlet weak var revealButton: UIBarButtonItem!

    override func viewDidLoad() {
        super.viewDidLoad()
        
        revealButton.target = self.revealViewController()
        revealButton.action = #selector(SWRevealViewController.revealToggle(_:))
    }
```

**Comment by mvorisis** [comment]
No you didn't get me, I had setted up and its working fine but I want to know which function is called when I close the slider(like open and close it again)

**Comment by iDevelopper** [comment]
```
    //MARK: - SWRevealViewControllerDelegate
    
    func revealController(_ revealController: SWRevealViewController!, willMoveTo position: FrontViewPosition) {
        if position == .right {
            // Will open
            NSLog("Will open")
        }
        else {
            NSLog("Will close")
        }
    }
    
    func revealController(_ revealController: SWRevealViewController!, didMoveTo position: FrontViewPosition) {
        if position == .right {
            NSLog("Did open")
        }
        else {
            NSLog("Did close")
        }
    }
```

**Comment by mvorisis** [comment]
Thank you this is what I want but I was wondering can I call these functions to my main view instead of the revealviewcontroller?

**Comment by iDevelopper** [comment]
You don't call these methods. SW call these delegate methods if your class adopt SWRevealViewControllerDelegate protocol and you implement them.
