### ISSUE TITLE
SWRevealViewController rightViewController disable the opening

### ISSUE THREAD

**Issue by harunozdemir** [John-Lluch/SWRevealViewController#667]
Hello,
Can you help me with this question?
http://stackoverflow.com/questions/41510133/swrevealviewcontroller-rightviewcontroller-open-disable

**Comment by iDevelopper** [comment]
You have to check the pan gesture's direction:

```
- (BOOL)revealControllerPanGestureShouldBegin:(SWRevealViewController *)revealController {
    if ([revealController.panGestureRecognizer velocityInView:revealController.view].x < 0) {
        // pan direction left, should open right side
        // ...
        return NO;
    }
    return YES;
}
```

**Comment by cmauroie** [comment]
I have the same issue but this solution not work for me. I have SWRevealViewController with map google and The ViewController where run the map not work the tap for hide the SwRevealViewController. Can help me?

**Comment by iDevelopper** [comment]
You have to use:

```
// Implement this to return YES if you want other gesture recognizer to share touch events with the pan gesture
- (BOOL)revealController:(SWRevealViewController *)revealController
    panGestureRecognizerShouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer;

// Implement this to return YES if you want other gesture recognizer to share touch events with the tap gesture
- (BOOL)revealController:(SWRevealViewController *)revealController
    tapGestureRecognizerShouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer;
```

**Comment by cmauroie** [comment]
I implement this solution and Return true but when need detect the tap only work in a part of screen

**Comment by iDevelopper** [comment]
Yes the tap is detected on the front view

**Comment by iDevelopper** [comment]
Implement the delegate method:

```
#pragma mark - GMSMapView delegate

- (void)mapView:(GMSMapView *)mapView didTapAtCoordinate:(CLLocationCoordinate2D)coordinate {
    if (self.revealViewController.frontViewPosition == FrontViewPositionRight) {
        [self.revealViewController setFrontViewPosition:FrontViewPositionLeft animated:YES];
    }
    else {
        // ...
    }
}
```

**Comment by Harunozdemir** [comment]
@iDevelopper I used your solution, but there is one more problem.If I don't pulling my finger from the screen,If I open the left page first and then try to open the right page, the right view opens again.
My code is this way:

`- (BOOL)revealControllerPanGestureShouldBegin:(SWRevealViewController *)revealController
{
    // right to left swipe
    if ([revealController.panGestureRecognizer velocityInView:revealController.view].x < 0) {
        if([revealController.frontViewController isKindOfClass:[UINavigationController class]])
        {
            UINavigationController *navController = (UINavigationController *)revealController.frontViewController;
            
            NSLog(@"::: LAST OBJECT NAVIGATION CONTROLLER CLASS: %@",  [navController.viewControllers.lastObject class]);
            
            UIViewController *lastViewController = navController.viewControllers.lastObject;
            
            if ([lastViewController isKindOfClass:[PersonelViewController class]] || [lastViewController isKindOfClass:[RandevuListViewController class]]) {                
     
                return YES;
            }
            else{
                return NO;
            }
      
        }
    }
    
    // left to right swipe
    {
        return YES;
        
    }
    
}
`
what is the solution?

**Comment by harunozdemir** [comment]
@iDevelopper I used your solution, but there was a problem.If I open the left page and open the right page again before opening my finger out of the screen, the right view opens.I modified the code this way:

     
    - (BOOL)revealControllerPanGestureShouldBegin:(SWRevealViewController *)revealController {
   
    // right to left swipe
    if ([revealController.panGestureRecognizer velocityInView:revealController.view].x < 0) {
        if([revealController.frontViewController isKindOfClass:[UINavigationController class]])
        {
            UINavigationController *navController = (UINavigationController *)revealController.frontViewController;
            
            NSLog(@"::: LAST OBJECT NAVIGATION CONTROLLER CLASS: %@",  [navController.viewControllers.lastObject class]);
            
            UIViewController *lastViewController = navController.viewControllers.lastObject;
            
            if ([lastViewController isKindOfClass:[PersonelViewController class]] || [lastViewController isKindOfClass:[RandevuListViewController class]]) {
                
                return YES;
            }
            else{
                return NO;
            }
      
        }
    }
    
    // left to right swipe
    {
        return YES;
        
    }
    }

How to I solve this problem?

**Comment by iDevelopper** [comment]
While panning, you can check the location like this (you have to check the class of your controller also):

```
#import <UIKit/UIGestureRecognizerSubclass.h>

// ...

- (void)revealController:(SWRevealViewController *)revealController panGestureMovedToLocation:(CGFloat)location progress:(CGFloat)progress
{
    if (location <= 0) {
        revealController.panGestureRecognizer.state = UIGestureRecognizerStateCancelled;
    }
}
```

**Comment by harunozdemir** [comment]
@iDevelopper Right-to-left motion does not work while left menu is open.To solve this, I took and checked the current position.

```
- (void)revealController:(SWRevealViewController *)revealController willMoveToPosition:(FrontViewPosition)position{
    currentPosition = position;
    // .....
}
```

and Pan movement works accordingly:

```
- (BOOL)revealControllerPanGestureShouldBegin:(SWRevealViewController *)revealController
{
    NSLog(@"%f",[revealController.panGestureRecognizer velocityInView:revealController.view].x);
    // right to left swipe
    if (currentPosition != FrontViewPositionRight) {
        if ([revealController.panGestureRecognizer velocityInView:revealController.view].x < 0) {
                //...
        }
     
    }
       
    // left to right swipe
    {
        return YES;
        
    }
    
}
```
It worked but disrupt the images of the right and left menu.How can I?

**Comment by iDevelopper** [comment]
You don't need a currentPosition variable. In revealControllerPanGestureShouldBegin, the position is revealController.frontViewPosition

**Comment by iDevelopper** [comment]
```
- (BOOL)revealControllerPanGestureShouldBegin:(SWRevealViewController *)revealController {
    if (revealController.frontViewPosition == FrontViewPositionRight) {
        return YES;
    }
    if ([revealController.panGestureRecognizer velocityInView:revealController.view].x < 0) {
        // pan direction left, should open right side, test your classes
        // ...
        return NO;
    }
    return YES;
}

- (void)revealController:(SWRevealViewController *)revealController panGestureMovedToLocation:(CGFloat)location progress:(CGFloat)progress
{
    if (location <= 0) {
        revealController.panGestureRecognizer.state = UIGestureRecognizerStateCancelled;
        [revealController setFrontViewPosition:FrontViewPositionLeft];
    }
}
```

**Comment by Harunozdemir** [comment]
Do you say that?I tried this and it's result same

```
- (BOOL)revealControllerPanGestureShouldBegin:(SWRevealViewController *)revealController
{
     // right to left swipe
        if ([revealController.panGestureRecognizer velocityInView:revealController.view].x < 0) {
            if (revealController.frontViewPosition != FrontViewPositionRight) {
                // ...
                }

            } else{
                return YES;
            }
        }
    
     
    // left to right swipe
    {
        return YES;
        
    }
    
}
```
I guess the problem occurs when the location variable is negative.Maybe it is not. I do not know

**Comment by iDevelopper** [comment]
I have edited my response, did you see?

**Comment by Harunozdemir** [comment]
Thanks worked for me.What is the reason for the problem?

```
[revealController setFrontViewPosition:FrontViewPositionLeft];
```
Is it relevant to this?
