### ISSUE TITLE
About toggling viewControllers

### ISSUE THREAD

**Issue by mrfarukturgut** [John-Lluch/SWRevealViewController#670]
Hi, 

Is there way that makes me to know when the user pressed a button on the menu that will change `masterViewController`?

I ask this because, I need a way to execute a `HTTPRequest` and then wait for it to be done right before dismissing a `ViewController'. Finally dismiss the `ViewController`. It is because the related `VC` is meant to be updating some type of data on server. 

I will be very appreciated if someone helps.

**Comment by iDevelopper** [comment]
A UIButton, a UITableViewCell?

**Comment by mrfarukturgut** [comment]
There is a uibutton in table view cell but, toggling process is triggered when user tapped on the cell not button

**Comment by iDevelopper** [comment]
You can intercept when the cell is selected by implementing:

didSelectRowAtIndexPath
