### ISSUE TITLE
Animation behaves unexpected on specific view. Animating Statusbar and subsequent views individually 

### ISSUE THREAD

**Issue by nexus49** [John-Lluch/SWRevealViewController#673]
In my application the the menu works great, except for one single view where i observe all elements of the view animate individually which looks really odd. I did follow the recommendation for other issues to not use "relative margin" constraints.

Please see below video to see the behavior, I'd be grateful for a hint that could explain that behavior. I can provide additional detail on the application setup if needed, but i was hoping somebody has seen such a behavior and can come up with a hint based on that video.

![reveal-gif](https://cloud.githubusercontent.com/assets/52737/22171709/8e136d0c-df59-11e6-8d5a-cce510bc3f12.gif)

**Comment by iDevelopper** [comment]
How do you animates these views?

**Comment by nexus49** [comment]
Well I use custom storyboard segues of class `SWRevealViewControllerSeguePushController` and with `animated=true`

Then in the Controller of the background view I invoke 
`self.performSegue(withIdentifier: "activeTrip", sender: self)` to switch to that respective menu element view.

**Comment by iDevelopper** [comment]
Yes then 2 segues are executed (two animations), this is probably the problem.

**Comment by nexus49** [comment]
Hm, I made sure that only one segue is triggered. In this case there is only one segue with the identifier `activeTrip`.

One thing to mention is that this is a segue to another storyboard, which is one of the differences over other segues. So the custom segue points to a `Storyboard Reference` which uses the initial ViewController of the other Storyboard. 

But if i change the app to create the segue from code like this:

```
let storyBoard = UIStoryboard(name: "trip", bundle: nil)
let controller = storyBoard.instantiateViewController(withIdentifier: "trips")
self.revealViewController().pushFrontViewController(controller, animated: true)
```

The behavior is exactly the same.

**Comment by nexus49** [comment]
Ok i found the reason by trial and error.

As part of the view loading process i had a section where i animate a changed constraint like this:

```
UIView.animate(withDuration: 1) {
   self.view.layoutIfNeeded()
}
```

This must have caused the double animation that you mentioned earlier. 

Thanks a lot for your hint, this pointed me in the right direction.
