### ISSUE TITLE
White stripes on top

### ISSUE THREAD

**Issue by ghost** [John-Lluch/SWRevealViewController#684]
Hi !

When I open the menu with a drag (and not with a tap on my burger button), I have a white stripe on top of it (picture below). If I put the application in background and re-open it, the white stripe disappear with a look-like fade animation. Any idea ?

![img_0804](https://cloud.githubusercontent.com/assets/15651664/23331977/ab2e8b5a-fb70-11e6-8132-298b5ac746d5.PNG)

**Comment by iDevelopper** [comment]
#649 
#604

**Comment by ghost** [comment]
Ok 
My top constraint was the problem. It was set to 0 but apparently not apply so I remove it and I add it again. No problem anymore but weird behavior.
