### ISSUE TITLE
Unable to use SWRevealViewrController in UIViewController

### ISSUE THREAD

**Issue by legendashish** [John-Lluch/SWRevealViewController#685]
(void)viewDidLoad {
[super viewDidLoad];
 FrontViewController *frontViewController = [[FrontViewController alloc] init];
	RearViewController *rearViewController = [[RearViewController alloc] init];
    
    UINavigationController *frontNavigationController = [[UINavigationController alloc] initWithRootViewController:frontViewController];
    UINavigationController *rearNavigationController = [[UINavigationController alloc] initWithRootViewController:rearViewController];

    SWRevealViewController *mainRevealController = [[SWRevealViewController alloc]
        initWithRearViewController:rearNavigationController frontViewController:frontNavigationController];
    
    mainRevealController.delegate = self;
    
	self.viewController = mainRevealController;
	
	self.window.rootViewController = self.viewController;
	[self.window makeKeyAndVisible];
	
}

**Comment by iDevelopper** [comment]
Why do not do that in AppDelegate? What is self.viewController?

**Comment by legendashish** [comment]
If implemented in AppDelegate then it directly loads the app with the controller in the root view on app launch.I want to load the controller after i login to the application in my HomePage's UIViewController.
Is there a way to do that ?

**Comment by iDevelopper** [comment]
Ok, what is self.viewController?

**Comment by legendashish** [comment]
Its 
@property (strong, nonatomic) SWRevealViewController *viewController;

**Comment by iDevelopper** [comment]
And self.window is a property of your viewController too? Is it initialized somewhere?

**Comment by iDevelopper** [comment]
Try like that:

```
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.

    FrontViewController *frontViewController = [[FrontViewController alloc] init];
    RearViewController *rearViewController = [[RearViewController alloc] init];
    
    UINavigationController *frontNavigationController = [[UINavigationController alloc] initWithRootViewController:frontViewController];
    UINavigationController *rearNavigationController = [[UINavigationController alloc] initWithRootViewController:rearViewController];
    
    SWRevealViewController *mainRevealController = [[SWRevealViewController alloc]
                                                    initWithRearViewController:rearNavigationController
                                                    frontViewController:frontNavigationController];
    
    mainRevealController.delegate = self;
    
    AppDelegate *appDelegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
    
    appDelegate.window.rootViewController = mainRevealController;
}
```

**Comment by legendashish** [comment]
yes 
i have initialized both 
@property (strong, nonatomic) SWRevealViewController *viewController;
@property (strong, nonatomic) UIWindow *window;
 in my ViewController.h file 

and in my ViewController.m in the viewDidLoad  method i have implemented the controller, but it doesn't seem to work.
Kindly suggest !

**Comment by legendashish** [comment]
Thanks,
I tried to implement as mentioned above but ,
i get the below
Warning: Attempt to present<HomeViewController: 0x7fc14ac12fc0> on <LoginViewController: 0x7fc14ac06b90> whose view is not in the window hierarchy!

Can u implement it in a ViewController and test?

**Comment by iDevelopper** [comment]
[SWCreateFromController.zip](https://github.com/John-Lluch/SWRevealViewController/files/819231/SWCreateFromController.zip)

**Comment by legendashish** [comment]
Its working perfectly with your example.
I got the mistake i did.
Really appreciate the time you have invested.
Thank you ! :)
