### ISSUE TITLE
UIBarButtonItem changes the color when UIAlertController is shown

### ISSUE THREAD

**Issue by idelfonsog2** [John-Lluch/SWRevealViewController#688]
When I present a UIAlertController the menu icon changes the color to white. Why?

<img width="373" alt="screen shot 2017-03-16 at 2 47 29 pm" src="https://cloud.githubusercontent.com/assets/7195235/24013390/9a5e1d04-0a57-11e7-9f40-16ab4fad0a1a.png">

<img width="389" alt="screen shot 2017-03-16 at 2 47 14 pm" src="https://cloud.githubusercontent.com/assets/7195235/24013389/9a5dc1b0-0a57-11e7-8f11-0df51eb9b03f.png">

**Comment by iDevelopper** [comment]
Post your question on https://stackoverflow.com/ as this not a question relative to SWRevealViewController

**Comment by idelfonsog2** [comment]
Ok Thanks!
