### ISSUE TITLE
Menu collapses when expanded over the point it will span to

### ISSUE THREAD

**Issue by MaikoHermans** [John-Lluch/SWRevealViewController#690]
I'm trying to make the SWRevealViewController work in my application.

What I did is I didn't want to be able to open the menu from everywhere on the screen so I changed all the `UIPanGestureRecognizer` with `UIScreenEdgePanGestureRecognizer` so it would only be triggered from the side of the screen.

to achieve this I also altered the` panGestureRecognizer` method. This looks as follows right now

```
- (UIScreenEdgePanGestureRecognizer*)panGestureRecognizer
{
    if ( _panGestureRecognizer == nil )
    {
        _panGestureRecognizer = [[SWRevealViewControllerPanGestureRecognizer alloc] initWithTarget:self action:@selector(_handleRevealGesture:)];
        _panGestureRecognizer.delegate = self;
        _panGestureRecognizer.edges = UIRectEdgeLeft;
        [_contentView.frontView addGestureRecognizer:_panGestureRecognizer];
    }
    return _panGestureRecognizer;
}
```

However (not sure if this change is causing my problem) when I start to open the menu from the left side and expand it over the point where it will normally snap to when opened up it will collapse back in.

so let's say it opens to 500px of the screen. When I drag it beyond those 500px it will automatically close the menu.

Also it's currently not possible to close the menu again by swiping it. What I did for now is add a gesturerecognizer which will trigger the `revealViewController.revealToggle(animated: true)` method.

**Comment by iDevelopper** [comment]
Use the delegate method and test the location:

```
- (BOOL)revealControllerPanGestureShouldBegin:(SWRevealViewController *)revealController {
    CGPoint point = [revealController.panGestureRecognizer locationInView:self.view];
    // Menu is close, pan gesture should begin if pan start from border
    if (revealController.frontViewPosition == FrontViewPositionLeft && point.x < 50.0) {
        return YES;
    }
    // Menu is open, pan gesture should begin
    else if (revealController.frontViewPosition == FrontViewPositionRight) {
        return YES;
    }
    return NO;
}
```

**Comment by iDevelopper** [comment]
For the over point, use:

#import <UIKit/UIGestureRecognizerSubclass.h>

...

```
- (void)revealController:(SWRevealViewController *)revealController panGestureMovedToLocation:(CGFloat)location progress:(CGFloat)progress {
    if (location >= revealController.rearViewRevealWidth) {
        revealController.panGestureRecognizer.state = UIGestureRecognizerStateEnded;
    }
}
```

**Comment by MaikoHermans** [comment]
awesome thanks that works!

I've translated it to swift to for anyone that is looking for this. My code looks like this

``` swift
import UIKit
import SWRevealViewController
import UIKit.UIGestureRecognizerSubclass

class ViewController: UIViewController, SWRevealViewControllerDelegate {

    @IBOutlet var openMenu: UIBarButtonItem!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        openMenu.target = self.revealViewController()
        openMenu.action = #selector(SWRevealViewController.revealToggle(_:))
        
        revealViewController().delegate = self
        self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
        
        self.hideMenuWhenTappedAround()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    func revealControllerPanGestureShouldBegin(_ revealController: SWRevealViewController!) -> Bool {
        let point = revealController.panGestureRecognizer().location(in: self.view)
        
        if revealController.frontViewPosition == FrontViewPosition.left && point.x < 50.0 {
            return true
        }
        else if revealController.frontViewPosition == FrontViewPosition.right {
            return true
        }
        
        return false
    }
    
    func revealController(_ revealController: SWRevealViewController!, panGestureMovedToLocation location: CGFloat, progress: CGFloat) {
        if location >= revealController.rearViewRevealWidth {
            revealController.panGestureRecognizer().state = UIGestureRecognizerState.ended
        }
    }
}
```

the `self.hideMenuWhenTappedAround()` method is a function in an extension that will close the menu when you tap anywhere on the view

**Comment by iDevelopper** [comment]
Cool! Just a suggestion: You do not need to add the pan gesture recognizer to your view. Just call once [self.revealViewController panGestureRecognizer, and it will automatically be added to all front views...

```
// By default, the panGestureRecognizer is added to the view containing the front controller view. To keep this default behavior
// you still need to call this method, just don't add it to any of your views. The default setup allows you to dissable
// user interactions on your controller views without affecting the recognizer.
- (UIPanGestureRecognizer*)panGestureRecognizer;
```

**Comment by MaikoHermans** [comment]
Will take a look at that thanks.

another quick question (maybe I should create a new issue for this)
is there a way to set the endpoint of the menu to a percentage of the screen?

Like I want it to open up so that only a small part of the frontview remains visible when the menu is active.

I know this can be done like this
```revealViewController().rearViewRevealWidth = self.view.frame.width * 0.8``` but that would mean doing it for every view controller?

**Comment by iDevelopper** [comment]
This is not my library, I am an user like you. Then I don't care you open a new issue or not. Now I have my own library (see my profile) inspired from @John-Lluch SWRevealViewController's Class. I wrote it because I wanted to have the possibility to present the left/right view on top, and I shared it on Github (with a special thanks to @John-Lluch) 

I think you should change this ratio each time before pushing a new front view controller. For example in -tableView:didSelectRowAtIndexPath:, before push:

```
        self.revealViewController.rearViewRevealWidth = [UIScreen mainScreen].bounds.size.width * 0.6; // For example
        [self.revealViewController pushFrontViewController:yourController animated:YES];
```

Or in prepareForSegue method, but I do not use push segue.
