### ISSUE TITLE
Newbies problem with UINavBar and StatusBar Colors.

### ISSUE THREAD

**Issue by BullzLabz** [John-Lluch/SWRevealViewController#692]
Hi, i'm a newbies with swift and xcode dev, and i try to fix a problem with colors of StatusBar and NavBar.

I've already set the "Bar Tint" to black color in "Navigation Controller" storyboard.

I've followed this tuts to implement SWRevealViewController, but colors customisation isn't mentioned.

Could you please help me.

[vIdeo of my problem](https://github.com/BullzLabz/shared-items/blob/master/problem_iOS-statut-navbar-desktop.m4v?raw=true)

Thanks

**Comment by iDevelopper** [comment]
This issue has no relation with SW, so you should also ask your question on https://stackoverflow.com/

How do you push the front view controller from rear view controller?

If you instantiate the new front view controller from storyboard, and create by code a UINavigationController setting his root view controller to this new front view controller, the bar tint color will be the default color. You have to change this default color by code too.

Or instantiate from story board the navigation controller itself in which is embedded the font view controller.

For the status bar color, if you want a black navigation bar, I suppose you want a white status bar color.

In the General tab of your target, set status bar style to light. And ensures that "View controller-based status bar appearance" key in your Info.plist is set to NO.

Or set status bar style to default.

Hope it helps!

**Comment by iDevelopper** [comment]
A sample:

[SWIssue263.zip](https://github.com/John-Lluch/SWRevealViewController/files/922236/SWIssue263.zip)

**Comment by BullzLabz** [comment]
Thanks a lot @iDevelopper for your help !

Have a nice day ;-)

**Comment by iDevelopper** [comment]
Welcome, keep me informed.

**Comment by BullzLabz** [comment]
Ok, thanksi ;-)

**Comment by BullzLabz** [comment]
Hi @iDevelopper , 

I've add this in my tableViewController for each cell 👍 
```
        navigationController.navigationBar.barStyle = .black
        navigationController.navigationBar.isTranslucent = false
```

And all work fine for the NavBar Colors.

And for the statut bar color, i've just followed ur tips. like this 👍 

```
For the status bar color, if you want a black navigation bar, I suppose you want a white status bar color.

In the General tab of your target, set status bar style to light. And ensures that "View controller-based status bar appearance" key in your Info.plist is set to NO.

Or set status bar style to default.
```

**Comment by BullzLabz** [comment]
Thanks a lot for ur help @iDevelopper

**Comment by iDevelopper** [comment]
Welcome, but for each cell, It is useless!
