### ISSUE TITLE
Singleton as Front View Controller

### ISSUE THREAD

**Issue by PlasmaSoftUK** [John-Lluch/SWRevealViewController#697]
I'm trying to set my front view controller as a Singleton, so that I can share data from it in to the other view in my App. I made it a singleton like this:

>static DocumentsViewController *sharedInstance = nil;
>
> + (id) sharedInstance
> {
>     return sharedInstance;
> }
>
> -(id)initWithCoder:(NSCoder *)decoder {
>     if (!sharedInstance) {
>         if (self = [super initWithCoder:decoder]) {
>             sharedInstance = self;
>         }
>     }
>     return sharedInstance;
> }

This works fine for the first load, I can also open up the "menu" which successfully pulls data from this shared view. However when selecting the menu option that loads up the Front View it crashes with:

> 2017-05-03 22:59:12.822 Documents[60216:2406648] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'This coder requires that replaced objects be returned from initWithCoder:'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x0000000108bf7b0b __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x000000010865c141 objc_exception_throw + 48
> 	2   CoreFoundation                      0x0000000108c60625 +[NSException raise:format:] + 197
> 	3   UIKit                               0x0000000109f5a4f9 UINibDecoderDecodeObjectForValue + 767
> 	4   UIKit                               0x0000000109f5a1ef -[UINibDecoder decodeObjectForKey:] + 89
> 	5   UIKit                               0x0000000109d69bf6 -[UIRuntimeConnection initWithCoder:] + 136
> 	6   UIKit                               0x0000000109f5a4af UINibDecoderDecodeObjectForValue + 693
> 	7   UIKit                               0x0000000109f5a64d UINibDecoderDecodeObjectForValue + 1107
> 	8   UIKit                               0x0000000109f5a1ef -[UINibDecoder decodeObjectForKey:] + 89
> 	9   UIKit                               0x0000000109d68e1d -[UINib instantiateWithOwner:options:] + 1262
> 	10  UIKit                               0x000000010a12182f -[UIStoryboard instantiateViewControllerWithIdentifier:] + 181
> 	11  UIKit                               0x000000010a1294f4 -[UIStoryboardSegueTemplate instantiateOrFindDestinationViewControllerWithSender:] + 90
> 	12  UIKit                               0x000000010a12973e -[UIStoryboardSegueTemplate _perform:] + 52
> 	13  UIKit                               0x000000010a129a1f -[UIStoryboardSegueTemplate perform:] + 157
> 	14  UIKit                               0x0000000109ab8d77 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1677
> 	15  UIKit                               0x0000000109ab8fe3 -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 344
> 	16  UIKit                               0x000000010996e7f3 _runAfterCACommitDeferredBlocks + 318
> 	17  UIKit                               0x000000010995b7bc _cleanUpAfterCAFlushAndRunDeferredBlocks + 532
> 	18  UIKit                               0x000000010998d28c _afterCACommitHandler + 137
> 	19  CoreFoundation                      0x0000000108b9d717 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
> 	20  CoreFoundation                      0x0000000108b9d687 __CFRunLoopDoObservers + 391
> 	21  CoreFoundation                      0x0000000108b82720 __CFRunLoopRun + 1200
> 	22  CoreFoundation                      0x0000000108b82016 CFRunLoopRunSpecific + 406
> 	23  GraphicsServices                    0x000000010e149a24 GSEventRunModal + 62
> 	24  UIKit                               0x00000001099620d4 UIApplicationMain + 159
> 	25  Documents                           0x000000010804069f main + 111
> 	26  libdyld.dylib                       0x000000010c3a665d start + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException

I tried a different Singleton template which didn't use "initWithCoder" but while the app works fine when switching to and from the Front View it doesn't seem to make it a singleton, and the shared data doesn't work. Does anyone have a working Singleton Template that I can use as a Front View, or can explain to my why what I am doing isn't working.

Thanks in advance for any help!

Plasma

**Comment by iDevelopper** [comment]
Please create a singleton as a subclass of NSObject for your datas. Its instance will be accessible to all controllers.

```
@implementation YourSingleton

+ (void)load // Optional
{
    dispatch_async(dispatch_get_main_queue(), ^{
        [self sharedInstance];
    });
}

+ (instancetype)sharedInstance
{
    static dispatch_once_t once;
    static YourSingleton *sharedInstance = nil;
    dispatch_once(&once, ^{
        sharedInstance = [(YourSingleton *)[self alloc] init];
    });
    return sharedInstance;
}
```

**Comment by PlasmaSoftUK** [comment]
Now why didn't I think of that! I actually have a class that does this in a few of my other apps, so I just copied those in and a bit of config ......Tadaaaaaa Problem solved!

THANK YOU!

I had come so blinkered looking at making the main class in to a singleton!

Plasma

**Comment by PlasmaSoftUK** [comment]
One final comment just for completeness, after implementing the common class, I was able to get the values in to the menu, however because the menu only gets loaded once the cell data I was trying to update was not changing and stayed at the initial value. I added this to reload the cell with changing data each time the menu is opened:

- (void) viewWillAppear:(BOOL)animated {
    
    NSLog(@"Menu Appear - Reload Expiry Date");
    NSIndexPath *indexPath = [NSIndexPath indexPathForRow: 5 inSection:0];
    
    [self.tableView beginUpdates];
    [self.tableView reloadRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationNone];
    [self.tableView endUpdates];
    
}
