### ISSUE TITLE
Problem when closing with finger

### ISSUE THREAD

**Issue by jrbecart** [John-Lluch/SWRevealViewController#699]
If I open the menu with the icon (top left)  and close the drawer with gesture (right to left), I can't scroll the page and when I remove my finger from the screen the drawer open again. 
Dis somebody notice that before?

**Comment by iDevelopper** [comment]
Could you elaborate please? What scroll? Pan gesture right to left is designed to close rear view. If rear view open again, it is because your pan length is not enough.

**Comment by jrbecart** [comment]
In the image below: 
1: I touch the hamburger icon to open the menu. (It works)
2: I close the menu with gesture. (It works)
3: After I touch the screen (or slide or scroll) the menu open again.(My problem)
4: Menu is opening again. 

![image](https://cloud.githubusercontent.com/assets/11264667/26251564/ab217536-3c7b-11e7-9dc0-7fded22759b6.png)

If I want to close the menu properly I have to touch the hamburger icon or touch outside the menu.
If open the menu with gesture, I can close it with gesture.(It works)

**Comment by iDevelopper** [comment]
ave you implemented some delegate method?

**Comment by jrbecart** [comment]
Yes I have some delegate method.

**Comment by iDevelopper** [comment]
Okay, what are they doing?

**Comment by jrbecart** [comment]
I manage notifications, I have utility method and also I have authentication method. (firebase based)

**Comment by iDevelopper** [comment]
You could add a SW delegate method to allow open the menu by panning from the border of the screen like this:

```
- (BOOL)revealControllerPanGestureShouldBegin:(SWRevealViewController *)revealController {
    CGPoint point = [revealController.panGestureRecognizer locationInView:self.view];
    // Menu is close, pan gesture should begin if pan start from border
    if (revealController.frontViewPosition == FrontViewPositionLeft && point.x < 50.0) {
        return YES;
    }
    // Menu is open, pan gesture should begin
    else if (revealController.frontViewPosition == FrontViewPositionRight) {
        return YES;
    }
    return NO;
}
```

**Comment by jrbecart** [comment]
Thank you @iDevelopper, I tried this but it doesn't help, also for information my view is a uiwebview. It seems to works if it's not a uiwebview...

**Comment by iDevelopper** [comment]
Ok then you have to implement also:

```
- (BOOL)revealController:(SWRevealViewController *)revealController panGestureRecognizerShouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    return YES;
}
```

**Comment by iDevelopper** [comment]
I did not remember but you have also a property in SW named  draggableBorderWidth which you can use instead of the delegate method:

    self.revealViewController.draggableBorderWidth = 50;

**Comment by jrbecart** [comment]
It's much better!  I can open & close with panGesture. I can open & close with tapGesture. 
I can't mix tapGesture and panGesture, like open with panGesture and close with tapGesture.
I'm ok with your solutions, thank you.
