### ISSUE TITLE
call webservice on table cell

### ISSUE THREAD

**Issue by nikhil191090** [John-Lluch/SWRevealViewController#702]
hello all ,
i want to call webservice and load new view controller with json values from click on table view cell which is in my left menu controller . please help

**Comment by iDevelopper** [comment]
And what is the problem? What did you try? What did you expect? What happens instead?

**Comment by nikhil191090** [comment]
@iDevelopper  is it possible to call webservice on cell and how can we do it. because i also want to show json data on next view controller that is frontview. i am bit confused so if u help me m really thankful

**Comment by iDevelopper** [comment]
In the didSelectRowAtIndexPath method, call your web service and in the callback (when you receive your datas, instantiate the next view controller if it does not already exist, set its property with the received data and push it.

**Comment by nikhil191090** [comment]
thank you so much @iDevelopper . you are saviour. !!!
