### ISSUE TITLE
SWRevealViewController revisiting 

### ISSUE THREAD

**Issue by akshay1318a** [John-Lluch/SWRevealViewController#706]
when I revisit the page with the left menu I am getting error

  - (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    UIPanGestureRecognizer *pan;
    
    self.title = @"Welcome";

    UIGraphicsBeginImageContext(self.view.frame.size);
    [[UIImage imageNamed:@"background"] drawInRect:self.view.bounds];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    self.view.backgroundColor = [UIColor colorWithPatternImage:image];
    
    //Left slidebutton
    _leftbarbutton.target = self.revealViewController;
    _leftbarbutton.action = @selector(revealToggle:);
    [self.view addGestureRecognizer:self.revealViewController.panGestureRecognizer];

    UITapGestureRecognizer *tap = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(onButtonTapped:)];
    _drinksi.userInteractionEnabled = YES;
    [_drinksi addGestureRecognizer:tap];

    UITapGestureRecognizer *tap1 = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(onButtonTapped1:)];
    _foodi.userInteractionEnabled = YES;
    [_foodi addGestureRecognizer:tap1];
    
}

this is my view did load method and the app gets terminated at

    [self.view addGestureRecognizer:self.revealViewController.panGestureRecognizer];

the above line it debugger stays there for link two or three play clicks and  gets terminated
!!1

**Comment by iDevelopper** [comment]
What is the error message?

**Comment by iDevelopper** [comment]
How do you present this controller? With SWRevealViewController? I think self.revealViewControler is nil.

**Comment by akshay1318a** [comment]
yes how to rectify it??

**Comment by akshay1318a** [comment]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
  what shud I do to make it work??

**Comment by iDevelopper** [comment]
How do you present this controller from left menu?

**Comment by akshay1318a** [comment]
self.revealviewcontroller.pangesturerecogniser

**Comment by akshay1318a** [comment]
the line which gave me error I use that to present the tableview controller

**Comment by iDevelopper** [comment]
I asked you how do you present your view controller?

    [self.revealViewController pushFrontViewController:yourController animated:YES];

???

**Comment by akshay1318a** [comment]
no I have not done that!!
the above is my entire viewdidload and the menu works well until I visit others and come back!!

**Comment by akshay1318a** [comment]
I think[self.view addGestureRecognizer:self.revealViewController.panGestureRecognizer];
presents me the side menu

**Comment by akshay1318a** [comment]
[self setFrontViewPosition:toogledFrontViewPosition animated:animated];
in swrevealviewcontroler
I have not made an changes

**Comment by akshay1318a** [comment]
- (UIPanGestureRecognizer*)panGestureRecognizer
{
    if ( _panGestureRecognizer == nil )
    {
        SWDirectionPanGestureRecognizer *panRecognizer =
            [[SWDirectionPanGestureRecognizer alloc] initWithTarget:self action:@selector(_handleRevealGesture:)];
        
        panRecognizer.direction = SWDirectionPanGestureRecognizerHorizontal;
        panRecognizer.delegate = self;
        [_contentView.frontView addGestureRecognizer:panRecognizer];
        _panGestureRecognizer = panRecognizer ;
    }
    return _panGestureRecognizer;
} this is the method of pan gesture

**Comment by akshay1318a** [comment]
and what is the use of presenting the view controller???? pan gesture is enuf right to navigate to menu and back

**Comment by akshay1318a** [comment]
and I use storyboard!!

**Comment by iDevelopper** [comment]
No, first you don't have to add the pangesturderecognizer to your view. Just call in the first front view controller [self.revealViewController pangesturderecognizer];

Second, from the menu, present your controller with SW:

    [self.revealViewController pushFrontViewController:yourController animated:YES];

**Comment by akshay1318a** [comment]
I used [self.revealViewController panGestureRecogoniser];  and the button has become invisible the bar button of left menu (i.e.first it worked well when I moved three pages and revisit them it became grey)!!!and may I know what will happen if I use segue for menu?

**Comment by iDevelopper** [comment]
This is a sample:

[SW706ObjC.zip](https://github.com/John-Lluch/SWRevealViewController/files/1093807/SW706ObjC.zip)

**Comment by akshay1318a** [comment]
This is a sample of my error here it disappears but in. My project I get nsarray obj can’t be  il (reveal view controller becomes null)

**Comment by iDevelopper** [comment]
Where is your sample?

**Comment by akshay1318a** [comment]
Got it??

**Comment by iDevelopper** [comment]
No, you have to select a zip file with your project

**Comment by akshay1318a** [comment]
I have showed the error in your project made some changes did u check that??are you receiving ur zip file??

**Comment by iDevelopper** [comment]
No you have to upload it again

**Comment by akshay1318a** [comment]
I have above attached the zip files both are same!!

**Comment by iDevelopper** [comment]
No attachment found.

**Comment by akshay1318a** [comment]
I am attaching all the time and I have sent 2.0mb mail while sending I saw the size how is it not coming??let me upload somewhere and send u the link

**Comment by iDevelopper** [comment]
Send me your project by email: patrick.bodet4@wanadoo.fr

**Comment by akshay1318a** [comment]
my segue connection was wrong i.e it was given to menu view controller and it should be moved to reveal view controller and I used [self.revealViewController panGestureRecogoniser]; now it works fine!! thank you for ur support!!

**Comment by iDevelopper** [comment]
Why do not use navigation controllers and push instead off all these modal segues?

**Comment by akshay1318a** [comment]
I am actually new to iOS so I didn't know abt warnings and deprications!! will that be a serious issue??
as I am new it was bit confusing to understand the nav controllers

**Comment by iDevelopper** [comment]
There are a lot of memory leaks because each time you present a modal view controller, you never dismiss it then they stay in memory. I would use navigation controller and push and I would have the reveal view controller as the initial controller.

**Comment by akshay1318a** [comment]
ok thank you very much for your information !!I
 ll try to change the segues:)!!!
