### ISSUE TITLE
Working with multiple View Controller

### ISSUE THREAD

**Issue by vunhatminh241191** [John-Lluch/SWRevealViewController#708]
Hi,
I have a little bit issue while trying to use this awesome library. My issue is using this library for multiple view controller. There are many tutorial they do that but you have to make a real connection between SWRevealViewController. My question is do we have any way, which using like inheritance methodology, where we could reuse SWRevealViewController when we need and we don't need to make a real connection in storyboard.

I am very appreciated you guys help.
Thanks.

**Comment by iDevelopper** [comment]
I'm not sure I understand your question:

You want to use SWRevealViewController without segue? If so, of course it is possible.

**Comment by vunhatminh241191** [comment]
Hi iDeveloper,
I means I would like to create separate Storyboard for SWReveal library, after that, if I need use that in some view controller, I could uses that like an super class of this view controller.  I hope you understand my situation.
Thanks

**Comment by vunhatminh241191** [comment]
I think my problem is using a lot of sw_front view controller. I want every view controllers in my application could using SWReveal controller. Therefore, I have to add everything into storyboard and do some connection. Is there any way that I can only have that SWReveal controller and use that like a super class of other view controllers?

**Comment by iDevelopper** [comment]
In your storyboard you must have SWRevealViewController with two set segues (sw_front and sw_rear). After that , from the rear view controller you can have some push segues to others controllers. Or, in your code (from didSelectRowAtIndexPath method for example), you can call [self.revealViewController pushFrontViewController: aController animated:YES]; or replace the front view controller with [self.revealViewController setFrontViewController: aController animated:YES];

**Comment by thihaaung6245** [comment]
@iDevelopper , I am also seeking for the same thing. Using this library on multiple storyboards. Example project will be helpful. Btw, your [https://github.com/iDevelopper/PBRevealViewController](url) is great. I am looking forward to convert this to Swift 3. If you have created, I am ready to contribute. It will be better if we separated this "Menu.storyboard" for eg. which only include SWRevalViewController and use this as window rootViewController and navigate to other controllers at other storyboard. Is this possible?

I have implemented one using this [https://github.com/dekatotoro/SlideMenuControllerSwift](url). But, I don't know how to implement such feature using yours or SWRevealViewController

**Comment by iDevelopper** [comment]
1) If you want to use multiple storyboard, there is no problem but you cannot use the push segue. You have to instantiate the others controllers from others storyboards and push them in code.

2) Why do you want to convert this library to Swift? It can be use in a Swift project...

**Comment by thihaaung6245** [comment]
@iDevelopper, yeah correct that it can be used in Swift. But, as you can see Swift is becoming popular now.

1. Many beginners can't read obj-c and there is only a documentation written on obj-c. Even when I first start use SWRevealViewController, I don't know how to apply in swift or how to use it correctly without the help of yours.
2. If you convert this to swift, there will be more contributions and forks to come. And the library will be active and full of pull requests. And swift it's easy to read.


@vunhatminh241191 , I understand your situation. Mean you only want to insert SWRevealViewController at one storyboard assume (Menu.storyboard) and you want to use that storyboard and navigate to other view controllers at their storyboards without need to declaring "SW_Front" and "SW_Rear" at each storyboard. Am I correct?

**Comment by iDevelopper** [comment]
1. You have the auto completion when you write code in Swift.

2. You are right, but I have to find time to convert it. I know Swift, but for me Objective-c is easiest to read!!! I will think about this, as Swift begin to be stabilised!!!!!

**Comment by thihaaung6245** [comment]
@iDevelopper , please let me know when ready, I will help you contribute. But, if you are waiting Swift to stable, I think it's not possible. But, at Swift 4, you can use Swift 3 as well. So, no need to worry about stable now lol,Thanks. 

@vunhatminh241191 , I will get back to you. Let me test for an example project. I am trying the same thing.

**Comment by vunhatminh241191** [comment]
I think I follow this tutorial "https://www.youtube.com/watch?v=xp6zpHACVbI" to add some view controller in the front side, is that the way that you are mention iDeveloper? Moreover, based on my understanding, I know we are using sw_rear for working with some menu items, and sw_front is the view controller, which is the current view controller is running. Therefore, I am kind of confusing about how pushfrontviewcontroller function should work in this case.

I am very appreciated your help. Thanks

**Comment by iDevelopper** [comment]
I don't like to use SWRevealViewControllerSeguePushController segues. Because it make the storyboard difficult to read if you have a lot of view controller. Instead I use in code:

            revealViewController().pushFrontViewController(aController, animated:true)

witch push a new front view controller.

**Comment by vunhatminh241191** [comment]
I see what you mean. Could you please tell me where can I push that?

**Comment by iDevelopper** [comment]
Hi @vunhatminh241191 , from the rear view controller, if it is a table view controller, from didSelectRow, example:

```
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        var controller: UIViewController?
        //let storyboard = UIStoryboard(name: "Main", bundle: nil)
        
        switch (indexPath as NSIndexPath).row {
        case 0:
            controller = self.storyboard?.instantiateViewController(withIdentifier: "ViewController1")
        case 1:
            controller = self.storyboard?.instantiateViewController(withIdentifier: "ViewController2")
            
        default: break
        }
        
        if (controller != nil) {
            let cell = tableView.cellForRow(at: indexPath)
            controller!.title = cell?.textLabel?.text
            let navController = UINavigationController(rootViewController: controller!)
            revealViewController().pushFrontViewController(navController, animated:true)
        }
    }
```

**Comment by vunhatminh241191** [comment]
Thanks for your help iDeveloper. I am very appreciated that.

**Comment by iDevelopper** [comment]
Hi @htarwara6245 ,

This is a beta version of PBRevealViewController written in Swift:

[PBRevealSwift.zip](https://github.com/John-Lluch/SWRevealViewController/files/1131129/PBRevealSwift.zip)

The project is not yet on Github.

Not tested yet for tvOS projects.
Not tested yet for ObjC projects.

If you still want to contribute, thanks for tests and callbacks, but please open an issue at https://github.com/iDevelopper/PBRevealViewController

**Comment by nav106II** [comment]
@iDevelopper  I work excellent, thank you very much for the contribution man!
