### ISSUE TITLE
UINavigationBar height not increased?

### ISSUE THREAD

**Issue by Lyankar** [John-Lluch/SWRevealViewController#713]
I'm using SWRevealViewController in my project, it's working fine. But I got small problem, i am increasing navigationBar height programmatically( in viewWilAppear  [self.navigationController.navigationBar setFrame:CGRectMake(0,0,self.view.frame.size.width,100.0)]; ). It's working when it's loaded first time. But when we click menu item from menu list the navigationBar height was set to default height (i.e. 44.0000). How to increase navigationBar height. Is there any solution for me. Can u help me...

**Comment by Lyankar** [comment]
[SideOutMenuExample.zip](https://github.com/John-Lluch/SWRevealViewController/files/1184786/SideOutMenuExample.zip)

This is example file...

**Comment by iDevelopper** [comment]
In viewDidAppear, it will work (don't forgot [super viewDidAppear:animated];)

**Comment by Lyankar** [comment]
Yes, it's working. Fine, thank u.....
