### ISSUE TITLE
Toggling Menu via button not working (Swift)

### ISSUE THREAD

**Issue by rikesan** [John-Lluch/SWRevealViewController#723]
I have setup a navigation bar with a bar button which toggles the menu animation, but somehow it's not working (although the function gets called and I get no errors nor warnings).

I am setting up my views programmatically and tried to put up the simplest example possible showing the problem I'm facing. The pan gesture works flawlessly.

Any ideas? 

[TestMenuSwift.zip](https://github.com/John-Lluch/SWRevealViewController/files/1212777/TestMenuSwift.zip)

**Comment by iDevelopper** [comment]
You have mainRevealController?.rearViewRevealWidth = 0 in AppDelegate and no need to add the pan gesture to the view (in ViewController).

revealController.panGestureRecognizer() is sufficient.

**Comment by rikesan** [comment]
Edit

**Comment by iDevelopper** [comment]
Your menu is open because in AppDelegate you wrote:

        mainRevealController?.frontViewPosition = .right
