### ISSUE TITLE
Add a view controller other than tabbar controller 

### ISSUE THREAD

**Issue by malenchelon** [John-Lluch/SWRevealViewController#729]
[SWTabBarSwift Args.zip](https://github.com/John-Lluch/SWRevealViewController/files/1267758/SWTabBarSwift.Args.zip)

**Comment by iDevelopper** [comment]
Hello, could you elaborate please?

**Comment by malenchelon** [comment]
i just added 3 tabbars for my project ! and i would like to add another 2 view controllers which should not be in tabbar controller!

**Comment by iDevelopper** [comment]
You can't have two sw_front set segue, you have to choose which view controller is the front view controller at launch (i.e the first front view controller to be displayed). The other ones must replace it by using revealViewController.setFrontViewController or by pushing them from left menu using revealViewController.pushFrontViewController (or a push segue: SWRevealViewControllerSeguePushController).

**Comment by malenchelon** [comment]
i need the index1 tabbar to be the first view controller. i wrote that .But i also need item4 item5 in side menu. which should not be there in tabbar. how can i assign view controllers for item4 and item5 to get display in side menu but not in the tabbar menu..and by adding in the menu item4 and item5 im getting error indexrange bounds 0 ..2 ..i understand that i gave only 3 tabbars and asking for extra one to display

**Comment by malenchelon** [comment]
[SWTabBarSwift Args.zip](https://github.com/John-Lluch/SWRevealViewController/files/1269301/SWTabBarSwift.Args.zip)
please have a look at this ... that helps u fast to understand what i would like to say

**Comment by iDevelopper** [comment]
Humm... Stop saying you wrote anything! This is not your project but a sample you found in an other issue. And this sample was written by me!!

Then I just modified it:

[SWTabBarSwift Args-3.zip](https://github.com/John-Lluch/SWRevealViewController/files/1269307/SWTabBarSwift.Args-3.zip)

Hope it helps!

**Comment by malenchelon** [comment]
Thank you . it worked liked charm. i found it from u only. what i mean i wrote is . i just set the default index of tabbar . i not meant that i wrote the things. Any way thanks for your help.

Sir, can i have ur email id. Or just message to this mail id malenchelonandrew@gmail.com

**Comment by iDevelopper** [comment]
Welcome!
