### ISSUE TITLE
The screen of UIViewController is black

### ISSUE THREAD

**Issue by dtco-kimi** [John-Lluch/SWRevealViewController#732]
As title, here is my code snippet,
 
    @interface TrusterViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
    @property (weak, nonatomic) IBOutlet UITableView *tableview;
    @end

Im my implementation file, 

    - (void)viewDidLoad {
        [super viewDidLoad];
        [_tableview setDelegate:self];
        [_tableview setDataSource:self];

        SWRevealViewController *revealController = [self revealViewController];
    [self.navigationController.navigationBar addGestureRecognizer:revealController.panGestureRecognizer];
    
        UIBarButtonItem *revealButtonItem = [[UIBarButtonItem alloc] initWithImage:[UIImage imageNamed:@"reveal-icon.png"]
                                                                         style:UIBarButtonItemStyleBordered
                                                                        target:revealController
                                                                        action:@selector(revealToggle:)];
        self.navigationItem.leftBarButtonItem = revealButtonItem;
    }

I also put two buttons on this view controller, but I can see nothing. The page is fine If I put it 
 as a storyboard entry point.
However, if I use UITableViewController in another file 

    @interface RecordTableViewController : UITableViewController 
    @end

the code in  - (void)viewDidLoad is exactly the same. It works well, everything is fine.
What happened?? It's really strange. Because I need buttons and a table view on the same page, I chose UIViewController. 

Any help is appreciate.

**Comment by iDevelopper** [comment]
How SWRevealViewController is created? How TrustedViewController is instantiated?

**Comment by dtco-kimi** [comment]
SWRevealViewController is workimg well. The other two table views are working. I can change from a view to a view.
I created it by my storyboard. The other two are in the same way.

**Comment by iDevelopper** [comment]
Can you upload a sample?

**Comment by iDevelopper** [comment]
Do you have several sw_front?

**Comment by dtco-kimi** [comment]
Hi 
I don't know how to attach files here, I uploaded my project to my google drive, 
https://drive.google.com/file/d/0B9MK5mvfSa22VmsySW81TE55Wms/view?usp=sharing

No, I don't have serveral sw_front.

Thanks

**Comment by iDevelopper** [comment]
You have a storyboard but you do not use it!

You created an instance of TrustersViewController with alloc init, instead of instantiating it from your storyboard.

And in TrustersViewController, you do not create a table view.

So I have added a table view in the storyboard and I instantiate the controllers from this one.

[phrOS_Demo.zip](https://github.com/John-Lluch/SWRevealViewController/files/1291691/phrOS_Demo.zip)

**Comment by dtco-kimi** [comment]
Cool! It works. 
I'm still wondering that the other two were created with alloc, init, but they work well. Any reasons that TrustersViewController have to instantiate from my storyboard?

Many thanks for your help!

**Comment by iDevelopper** [comment]
This is because the TableViewController Class include already a table view and not a UIViewController.

**Comment by dtco-kimi** [comment]
Got it! 
Thanks for  your reply.
