### ISSUE TITLE
SWRevealViewController nil

### ISSUE THREAD

**Issue by tiskender2** [John-Lluch/SWRevealViewController#733]
> `fatal error: unexpectedly found nil while unwrapping an Optional value`

`   let revealViewController:SWRevealViewController = self.revealViewController()//the error here .   
   
 let mainStroyBoard:UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
    let desController = mainStroyBoard.instantiateViewController(withIdentifier: "MessageViewController") as! MessageViewController
    let newFrontViewController = UINavigationController.init(rootViewController:desController)
    revealViewController.pushFrontViewController(newFrontViewController, animated: true)`

> how do i resolve this error

**Comment by iDevelopper** [comment]
What class is self, and how do you present it?
