### ISSUE TITLE
How to go login page when we click logout from menu in SWRevealViewController?

### ISSUE THREAD

**Issue by Lyankar** [John-Lluch/SWRevealViewController#734]
I am using SWRevealViewController, in my project first I have login page with navigation controller then I am using reveal view controller. It's working fine, but when I click logout from menu list based on json response I want to go login page(first view controller, with out segue). With segue it's working fine, but based on json response only I want to go login page. For this I am writing code like this...

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    
   if (indexPath.row == 5) { // Logout
       [self callLogoutMethod];
       if (status == success) {
             LogoutVC *lvc = [self.storyboard instantiateViewControllerWithIdentifier:@"LVC"];       
             [self.navigationController pushViewController:lvc animated:YES];
        }
   }
}
  It's not working for me.

**Comment by iDevelopper** [comment]
From LoginViewController, how do you present SWRevealViewController?

**Comment by Lyankar** [comment]
Based on json response....
if (login == success) {
SWRevealViewController *swrvc= [self.storyboard instantiateViewControllerWithIdentifier:@"SWRVC"];
[self.navigationController pushViewController:swrvc animated:NO];
}

**Comment by iDevelopper** [comment]
Then to come back to LoginViewController:

[self.revealViewController.navigationController popToRootViewController animated: YES OR NO];

**Comment by Lyankar** [comment]
No sir, it's not working
I am writing like this..
if (indexPath.row == 5) { // Logout
[self callLogoutMethod];
}

//In logout method based on json response
if (login == success) {
dispatch_async(dispatch_get_main_queue(), ^{
[self.revealViewController.navigationController popToRootViewControllerAnimated:NO];
});
}

**Comment by iDevelopper** [comment]
How do you remove the navigation bar when you push sw?

**Comment by Lyankar** [comment]
I am writing code like this second view controller (in main viewcotroller)....
- (void)viewWillAppear:(BOOL)animated {
    [self.navigationController.navigationBar setBarTintColor: [UIColor colorWithRed:24/255.0 green:56/255.0 blue:131/255.0 alpha:1]];
    [self.navigationController.navigationBar setTranslucent:NO];
    
    UILabel* lbNavTitle = [[UILabel alloc] initWithFrame:CGRectMake(0, 0, 575, 40)];
    lbNavTitle.textAlignment = NSTextAlignmentLeft;
    lbNavTitle.text = @"Title";
    lbNavTitle.textColor = [UIColor whiteColor];
    lbNavTitle.font = [UIFont boldSystemFontOfSize:35.0f];
    self.navigationItem.titleView = lbNavTitle;
   
}

- (void) viewDidAppear:(BOOL)animated {
    
    [super viewDidAppear:animated];
    [self.navigationController.navigationBar setFrame:CGRectMake(0, 0, self.view.frame.size.width, 80.0)];
}

**Comment by Lyankar** [comment]
Sorry, through story board i am removing navigation bar (To uncheck navigation bar)
<img width="256" alt="screen shot 2017-09-15 at 2 48 16 pm" src="https://user-images.githubusercontent.com/30499569/30475583-f0ee54c4-9a24-11e7-8c92-06edb47a0409.png">

**Comment by Lyankar** [comment]
I selected navigation bar for first view controller (login vc), but it's not working.
<img width="255" alt="screen shot 2017-09-15 at 2 52 09 pm" src="https://user-images.githubusercontent.com/30499569/30475743-7ca07bfa-9a25-11e7-8059-04af4c880778.png">

**Comment by iDevelopper** [comment]
What about this?

[SWIssue734.zip](https://github.com/John-Lluch/SWRevealViewController/files/1306004/SWIssue734.zip)

**Comment by Lyankar** [comment]
Thank u for your reply, it's working in your scenario, but in my case it's not working.

//Now it's working....
if (indexPath.row == 5) { // Logout
[self.revealViewController.navigationController popToRootViewControllerAnimated:NO];
}

if I write this line [self.revealViewController.navigationController popToRootViewControllerAnimated:NO]; in some another class logout method like this, it's not working. (function calling successfully).
Here, I am getting json response in this logout method. That's why I am writing this line in another class method.

 if (indexPath.row == 5) { // Logout
[self callLogoutMethod];
}

//This was in another class
//In logout method based on json response
if (login == success) {
dispatch_async(dispatch_get_main_queue(), ^{
[self.revealViewController.navigationController popToRootViewControllerAnimated:NO];
});
}

**Comment by iDevelopper** [comment]
I was expecting this question!

[SWIssue734.zip](https://github.com/John-Lluch/SWRevealViewController/files/1306070/SWIssue734.zip)

**Comment by Lyankar** [comment]
In LeftMenuTBVC, u wrote logout method, but in case this method was in another class that is GlobalVC, I imported SWRevealViewController in this GlobalVC  and I imported this GlobalVC into MenuVC then I write this below code...

if (indexPath.row == 5) { // Logout
[self callLogoutMethod];
}

Function calling successfully, but screen not moving.

**Comment by iDevelopper** [comment]
What is GlobalVC class? A singleton? Inherit from which class?

**Comment by Lyankar** [comment]
@interface GlobalClassViewController : UIViewController

**Comment by iDevelopper** [comment]
And how do you instantiate it? This class don't know the SWRevealViewController instance, probably.

**Comment by Lyankar** [comment]
can u send how to instantiate?

**Comment by iDevelopper** [comment]
I would like to know how do you because I don't know what job does this class.

**Comment by Lyankar** [comment]
Nothing, to access this class globally to entire project. It has multiple API's and parameters along with this logout method.

**Comment by iDevelopper** [comment]
This class has no view, then she would be a NSObject class not a UIViewController class.

**Comment by iDevelopper** [comment]
I think this is the class in which you call your requests?

**Comment by Lyankar** [comment]
ok, if i create Class with Sub class of NSObject is it workingna

**Comment by Lyankar** [comment]
Dear friend I created global class like this @interface GlobalClass : NSObject

Now I am getting this error 
<img width="1988" alt="screen shot 2017-09-15 at 4 54 09 pm" src="https://user-images.githubusercontent.com/30499569/30480260-8a0aefa8-9a36-11e7-8070-eac3a4bdb39c.png">

**Comment by iDevelopper** [comment]
Can you upload this class here?

**Comment by Lyankar** [comment]
ok I will upload

**Comment by Lyankar** [comment]
[GlobalClassFile.txt](https://github.com/John-Lluch/SWRevealViewController/files/1306207/GlobalClassFile.txt)

**Comment by iDevelopper** [comment]
And the GlobalClassViewController?

**Comment by Lyankar** [comment]
[GCVC.txt](https://github.com/John-Lluch/SWRevealViewController/files/1306265/GCVC.txt)

**Comment by iDevelopper** [comment]
I added a class named APIManager( singleton) with a property named rvc set in LoginViewController in login method:

[SWIssue734.zip](https://github.com/John-Lluch/SWRevealViewController/files/1306706/SWIssue734.zip)

**Comment by Lyankar** [comment]
Thank u very much to spent your valuable time for me....

**Comment by iDevelopper** [comment]
This is what you were looking for?
