### ISSUE TITLE
iOS 11 - safeAreaInsets gets messed up on rotate

### ISSUE THREAD

**Issue by spybart** [John-Lluch/SWRevealViewController#739]
On iOS 11, if you have both the front and back view controllers visible, rotating the device will cause the front view controller to have incorrect safe area insets, and therefore the content will be misaligned. It goes away when you hide the back view controller (slide the menu off).

**Comment by iDevelopper** [comment]
Can you upload a screenshot?

**Comment by spybart** [comment]
Here is a set of screenshots going through each step. Basically what is happening is that upon rotation, the front view does not update it's safeAreaInsets, and its view is drawn with the old safeAreaInsets in the new frame.
![screenshot](https://user-images.githubusercontent.com/20375286/31247533-e1d28cd4-a9de-11e7-8c38-a4f5e62f72ad.png)

**Comment by spybart** [comment]
I don't know what I did... but the problem appears to be gone. I wish I knew what the solution was so I can help the next poor sucker to experience this.
