### ISSUE TITLE
How to remove NavigationBar space in menu?

### ISSUE THREAD

**Issue by mchan004** [John-Lluch/SWRevealViewController#744]
![screen shot 2017-10-09 at 18 46 59](https://user-images.githubusercontent.com/17780317/31338373-288dd46a-ad29-11e7-864b-cfcbe4f560d1.png)
![screen shot 2017-10-09 at 19 32 56](https://user-images.githubusercontent.com/17780317/31338361-1633be88-ad29-11e7-996b-e1be77632f79.png)
![screen shot 2017-10-09 at 18 54 33](https://user-images.githubusercontent.com/17780317/31338363-1afe5f4a-ad29-11e7-8de7-f2557e616e5f.png)

**Comment by iDevelopper** [comment]
Are you sure it is a navigation bar. You have section in your table view...

**Comment by mchan004** [comment]
I'm not sure it is a navigation bar.
UIView above TableView, I pick UIView and drop on top TableView. It's use Static Cells

**Comment by iDevelopper** [comment]
Try to delete Table View section

**Comment by iDevelopper** [comment]
What does the UIView contains?
