### ISSUE TITLE
Is SWRevealViewController compatible with iOS 10+?

### ISSUE THREAD

**Issue by gangelo** [John-Lluch/SWRevealViewController#749]
Is SWRevealViewController even compatible with iOS 10+? I want to try to use it, but it's a lot of work setting up it seems

**Comment by iDevelopper** [comment]
Compatible iOS 11 yes, but with a lot of warnings now. Its very easy to use. Your other similar choice would be https://github.com/iDevelopper/PBRevealViewController (ObjC or Swift).
