### ISSUE TITLE
26 warning on Swift 4

### ISSUE THREAD

**Issue by mchan004** [John-Lluch/SWRevealViewController#751]
I create new project and add SWRevealViewController to project
Xcode have 26 warning?
![screen shot 2017-10-26 at 10 49 20](https://user-images.githubusercontent.com/17780317/32041916-2090a3f2-ba60-11e7-88f5-fc6ea82be10e.png)

**Comment by iDevelopper** [comment]
#749

**Comment by Ishita6317** [comment]
Same issue

**Comment by Ishita6317** [comment]
Same warnings..

**Comment by iDevelopper** [comment]
#749

**Comment by anunay** [comment]
same for me. 
http://d.pr/i/fswBzS

**Comment by iDevelopper** [comment]
#749
