### ISSUE TITLE
Come back to login page view controller  from third view controller?

### ISSUE THREAD

**Issue by Lyankar** [John-Lluch/SWRevealViewController#754]
In my app i have login page, then i am using SWRevealViewController. In my menu i have 5 view controllers. I clicked 3rd view in my menu, now i am in third view controller. I want to go from this third VC to login page view controller. For this i am using below code, but it's not working.

[self.revealViewController.navigationController popToRootViewControllerAnimated:YES];

If login success  i am using navigationController to move first view controller.
SWRevealViewController *swrvc= [self.storyboard instantiateViewControllerWithIdentifier:@"SWRVC"];
[self.navigationController pushViewController:swrvc animated:NO];

I am using below code o come back login page VC, it's working when we click in menu list.
[self.revealViewController.navigationController popToRootViewControllerAnimated:YES];

But when we click button in 3rd view controller it's not come back to login page VC.

Can you please help me.....

**Comment by iDevelopper** [comment]
Can you upload your sample here?

**Comment by iDevelopper** [comment]
Here is a sample:

[SWLoginPushObjC.zip](https://github.com/John-Lluch/SWRevealViewController/files/1474028/SWLoginPushObjC.zip)

**Comment by Lyankar** [comment]
Sorry for the late reply, I am uploading my sample app. Please verify it...
In this app when we click button in MenuFourViewController , i want to come back  from MenuFourViewController to ViewController , that is login page.
[SWRevealViewController.zip](https://github.com/John-Lluch/SWRevealViewController/files/1484525/SWRevealViewController.zip)

**Comment by iDevelopper** [comment]
First, in your storyboard your segues must be SWRevealViewControllerSegueSetController, not SWRevealViewControllerSeguePushController. When I tap the login button I have a black screen.

**Comment by iDevelopper** [comment]
Sample modified:

[SWRevealViewController.zip](https://github.com/John-Lluch/SWRevealViewController/files/1484853/SWRevealViewController.zip)

**Comment by Lyankar** [comment]
Yes, thank u very much. It's working fine....

**Comment by Lyankar** [comment]
This is my sample code, here i am not getting Menu in Menu2ViewController and Menu3ViewController...
But your sample code has Menu for all view controllers, how ?
[MenuSample.zip](https://github.com/John-Lluch/SWRevealViewController/files/1490280/MenuSample.zip)

How you added left bar button item for view controller two. It's not visible on storyboard. But, it's showing in list.
<img width="308" alt="screen shot 2017-11-21 at 12 18 48 pm" src="https://user-images.githubusercontent.com/30499569/33058597-59d54a0e-ceb6-11e7-9a06-0b586285b28e.png">

**Comment by iDevelopper** [comment]
In your storyboard, drag a navigation item to the controller, this will add and show the top bar. After that drag a bar button item to the top bar and connect it to the IBOutlet of your controller. Done for Menu 2 View Controller. Try it for Menu 3 View Controller.

[MenuSample.zip](https://github.com/John-Lluch/SWRevealViewController/files/1490411/MenuSample.zip)

**Comment by Lyankar** [comment]
Yes, thank u.... I changed my view controller top bar from "Inferred" to "Translucent Navigation Bar" . Now it's visible.
https://stackoverflow.com/questions/16287963/navigation-bar-disappeared-from-my-storyboard-items

Thank u very much sir...

**Comment by Lyankar** [comment]
One more small doubt sir... I got around 27 warnings in SWRevealViewController. I am using x code 9.1.
I added new version from https://github.com/John-Lluch/SWRevealViewController
<img width="1237" alt="screen shot 2017-11-22 at 1 50 56 pm" src="https://user-images.githubusercontent.com/30499569/33116874-7236a922-cf8c-11e7-925a-bea2d8abb77b.png">

**Comment by iDevelopper** [comment]
It seems that this library is not maintained anymore. Your alternative should be https://github.com/iDevelopper/PBRevealViewController, inspired from this one.

**Comment by Lyankar** [comment]
[MenuSample.zip](https://github.com/John-Lluch/SWRevealViewController/files/1512574/MenuSample.zip)

I'm uploading above same example, I tried to working with PBRevealViewController in this example.  But I con't develop the menu. Can you help me please....

**Comment by iDevelopper** [comment]
1. pb_left instead of pb_main, and pb_main instead of pb_left in your storyboard segues.

2. In TableViewController.m:

```
//        [self.revealViewController pushViewController:nc animated:YES];
        [self.revealViewController pushMainViewController:nc animated:YES];
```

3. In Menu1ViewController.m: (No need with PBRevealViewController, automatic)
```
    // This is valid for all the app, no need to add the gesture recognizer to all views
    //[self.revealViewController tapGestureRecognizer];
    //[self.revealViewController panGestureRecognizer];
```
[MenuSample-2.zip](https://github.com/John-Lluch/SWRevealViewController/files/1513322/MenuSample-2.zip)

Please next time open an issue at https://github.com/iDevelopper/PBRevealViewController

**Comment by Lyankar** [comment]
Ok, thank u sir...From next time on words i will follow PBRevealViewController....
It's so simple and easy to use... Thank u very much sir....
