### ISSUE TITLE
Extra cells at the bottom

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [John-Lluch/SWRevealViewController#756]
I created the menu using a static table view like this.

![screen shot 2017-11-13 at 4 27 44 pm](https://user-images.githubusercontent.com/2551877/32722826-2e2b06f8-c891-11e7-8598-cfaf9f50b1bd.png)

It has 3 sections. First section has one cell, second one four and the third one has one cell.

But when I run it in the device, the last section gets extra cells which I did not add.

![img_5387](https://user-images.githubusercontent.com/2551877/32722862-55cd63f4-c891-11e7-9782-e90ab4395bf7.PNG)

Any idea why this happens and how to fix it?

Thanks!

**Comment by iDevelopper** [comment]
This is the default behaviour for a table view. To avoid this, in viewDidLoad:

```
        tableView.tableFooterView = UIView(frame: CGRect.zero)
```

**Comment by Isuru-Nanayakkara** [comment]
Thank you!
