### ISSUE TITLE
White View when i log in for second time, using SWRevealViewController

### ISSUE THREAD

**Issue by jorge-mr** [John-Lluch/SWRevealViewController#768]
Hi there, please some one help me :c 
I have a login in my app (LoginViewController), and when the login is successful, **my app have to present the home (HomeViewController)**, then if the user wants to log out, go to the SideMenu, press Profile and then press log out, this takes the user to the LogViewController, if the login is successful again (2nd time) then the app goes to the ProfileViewController and instead of present all the content of the view, present an empty white view.
All the SideMenu works fine! the tricky part is the login :c

See the images below... please

![captura de pantalla 2018-01-29 a la s 22 50 57](https://user-images.githubusercontent.com/31960313/35549303-8c93d968-054a-11e8-8b8d-244839eb3576.png)
![captura de pantalla 2018-01-29 a la s 22 51 11](https://user-images.githubusercontent.com/31960313/35549313-930344b4-054a-11e8-8975-fe64d5a3cd4f.png)
![captura de pantalla 2018-01-29 a la s 22 51 24](https://user-images.githubusercontent.com/31960313/35549315-952e5da0-054a-11e8-905c-3109977ea000.png)
![captura de pantalla 2018-01-29 a la s 22 51 34](https://user-images.githubusercontent.com/31960313/35549318-97221f7a-054a-11e8-88e9-5ca538eb44f2.png)
![captura de pantalla 2018-01-29 a la s 22 50 57 2](https://user-images.githubusercontent.com/31960313/35549320-98e088f6-054a-11e8-8245-9080a20bc739.png)
![captura de pantalla 2018-01-29 a la s 22 51 49](https://user-images.githubusercontent.com/31960313/35549322-9b06d112-054a-11e8-9e5a-ff3db2a6a931.png)

![captura de pantalla 2018-01-29 a la s 23 25 09](https://user-images.githubusercontent.com/31960313/35549720-7b19ddb6-054c-11e8-8106-5b99b28a3ad0.png)

```
My code:
----------------  LoginViewController when I press log in button --------------------
let sb = UIStoryboard(name: "Main", bundle: nil)
let controller = sb.instantiateViewController(withIdentifier: "HomeNavViewController")
self.revealViewController().setFront(controller, animated: true)
--------------------------------------------------------------------------------------


----------------   When I press Profile button on SideMenu --------------------------
let revealViewController : SWRevealViewController = self.revealViewController()
        let cell = tableView.cellForRow(at: indexPath)! as! SideMenuTableViewCell
        let mainStoryboard:UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        var newFrontViewController: UINavigationController!
        if cell.titleLabel.text == "Perfil" {
            let desController = mainStoryboard.instantiateViewController(withIdentifier: "ProfileViewController") as! ProfileViewController
            newFrontViewController = UINavigationController.init(rootViewController: desController)
        }
        ...
        revealViewController.pushFrontViewController(newFrontViewController, animated: true)
--------------------------------------------------------------------------------------


----------------  ProfileViewController when I press log out button --------------------
let sb = UIStoryboard(name: "Main", bundle: nil)
let controller = sb.instantiateViewController(withIdentifier: "LoginViewController")
self.revealViewController().pushFrontViewController(controller, animated: true)
--------------------------------------------------------------------------------------
```

**Comment by iDevelopper** [comment]
"Perfil" or "Profile"?
```
        if cell.titleLabel.text == "Perfil" {
            let desController = mainStoryboard.instantiateViewController(withIdentifier: "ProfileViewController") as! ProfileViewController
            newFrontViewController = UINavigationController.init(rootViewController: desController)
        }
```

**Comment by jorge-mr** [comment]
Your'e right! but... I have changed it to "Profile", but its still no working. :(

**Comment by iDevelopper** [comment]
It is not very easy to debug without a project. Could you upload the project?

**Comment by jorge-mr** [comment]
Sorry, everything was fine, it was my mistake, I was having a switch to configure the view, and I was going always to the default case.
