### ISSUE TITLE
SWRevealViewController not show status bar push from Appdelegate

### ISSUE THREAD

**Issue by yonathansteam** [John-Lluch/SWRevealViewController#770]
I open the issue at here https://stackoverflow.com/questions/49027713/swrevealviewcontroller-not-show-status-bar-push-from-appdelegate

when i open the app at first the status bar was shown but after it load the view controller its totally gone. Any help is appreciated

I am trying to push SWRevealViewController from appdelegate at first, the status bar is shown only temporary and after loading the viewController its not appearing.

Here is my code and I am using swift:

let storyboard = UIStoryboard(name: "Main", bundle: nil)
let sw = storyboard.instantiateViewController(withIdentifier: "revealControllerStoryboard") as! SWRevealViewController
self.window?.rootViewController = sw

let destinationController = storyboard.instantiateViewController(withIdentifier: "searchViewStoryboard") as! SearchViewController
let navigationController = UINavigationController(rootViewController: destinationController)
sw.pushFrontViewController(navigationController, animated: true)

**Comment by iDevelopper** [comment]
In your storyboard, be sure the RevealViewController is the initial View Controller. Add some segues (set segue i.e. sw_rear and sw_front) to left view controller and front view controller. That's all! No need to push!

**Comment by yonathansteam** [comment]
i solved it with this 
self.window = UIWindow(frame: UIScreen.main.bounds)
