### ISSUE TITLE
How to have TabBarController at the bottom itself as front controller, and side menu as rear controller programmatically?  Swift

### ISSUE THREAD

**Issue by valentinkukjans** [John-Lluch/SWRevealViewController#771]
I have tab bar controller now as root view controller, but I wanna implement side menu as rear controller. How I can achieve this programmatically?  I can find many tutorials and sample project with story board, but not programmatically. 

Thanks

**Comment by valentinkukjans** [comment]
I just figure out how to implement. 

In AppDelegate :


let rearViewController = ProfileController(collectionViewLayout: UICollectionViewLayout())
        let navRear = UINavigationController(rootViewController: rearViewController)
         let swRevealVC = SWRevealViewController(rearViewController: navRear, frontViewController: MainTabBarController())
        window?.rootViewController = swRevealVC

**Comment by iDevelopper** [comment]
Yes and what does not work?

**Comment by valentinkukjans** [comment]
Yeep, its works perfectly.Thanks.
