### ISSUE TITLE
Top space under cells in Menu tableviewcontroller with static cells 

### ISSUE THREAD

**Issue by iOSDias** [John-Lluch/SWRevealViewController#773]
![simulator screen shot - iphone 8 plus - 2018-03-06 at 16 53 40](https://user-images.githubusercontent.com/31696378/37028597-f5b8f934-215e-11e8-8b8e-0489e3aaa7c6.png)
I thought that this space in tableview and try to solve it in tableview, then I create tableviewcontroller not using swreveal, and this space is disappear. 
So, using uitableviewcontroller as side menu and SWRevealViewControllerSegueSetController, there is a white space under cells.
P.s. it is not TableViewHeader or tableview top constraint to safe area, it is bug in SWRevealViewController library and I do not know how to fix it.

**Comment by iDevelopper** [comment]
Could you provide some more informations about your code and your storyboard? Because I don't think it is a bug in the library.

**Comment by iOSDias** [comment]
@iDevelopper Of course, I solve it timely using UIViewController as Menu view and containerView(MenuTableViewController) in this UIViewController. The space disappears.
<img width="515" alt="2018-03-06 17 22 20" src="https://user-images.githubusercontent.com/31696378/37030033-a0a2df32-2163-11e8-8687-0ccb8ab50fb3.png">
The storyboard and code screens 
<img width="535" alt="2018-03-06 17 24 17" src="https://user-images.githubusercontent.com/31696378/37030046-ac681800-2163-11e8-9de6-be3d83fce781.png">
<img width="804" alt="2018-03-06 17 24 45" src="https://user-images.githubusercontent.com/31696378/37030056-b1e0ca5c-2163-11e8-9c6f-99b06f69863a.png">
<img width="803" alt="2018-03-06 17 24 55" src="https://user-images.githubusercontent.com/31696378/37030062-b60fb89a-2163-11e8-9126-51041fa4ea98.png">
<img width="721" alt="2018-03-06 17 25 06" src="https://user-images.githubusercontent.com/31696378/37030064-b821fcc4-2163-11e8-90e6-434809d372c6.png">
<img width="696" alt="2018-03-06 17 25 31" src="https://user-images.githubusercontent.com/31696378/37030067-ba50eb40-2163-11e8-8788-4031e7b49d95.png">
This is test version of library's bug

**Comment by iDevelopper** [comment]
Embed your rear view controller (UITableViewController) in a navigation controller, and uncheck Shows Navigation Bar, like in this sample:

[SWStaticCell.zip](https://github.com/John-Lluch/SWRevealViewController/files/1785090/SWStaticCell.zip)

**Comment by iOSDias** [comment]
@iDevelopper thank you

**Comment by iOSDias** [comment]
@iDevelopper there is one problem in your solution - you can not to make changes on menu view controller(change width, etc.)
Furthermore, usage menu view controller in container admit to change menu parameters

**Comment by iDevelopper** [comment]
And why not?

**Comment by iDevelopper** [comment]
[SWStaticCell.zip](https://github.com/John-Lluch/SWRevealViewController/files/1785811/SWStaticCell.zip)

**Comment by iOSDias** [comment]
@iDevelopper Thanks again

**Comment by iDevelopper** [comment]
What was the problem?

**Comment by iOSDias** [comment]
@iDevelopper the setupRevealController function was implemented in Menu controller, not front

**Comment by iDevelopper** [comment]
Ok, you have to do this in front. In SW the rear view controller is load the first time when you open it.

**Comment by iDevelopper** [comment]
After you can have a look to https://github.com/iDevelopper/PBRevealViewController
