### ISSUE TITLE
On selecting menu Item from the side menu TabBar gets disappear?

### ISSUE THREAD

**Issue by Bilal10Akram** [John-Lluch/SWRevealViewController#780]
I have burger button (menu button) in almost all vc and my main screen is tabBarController. Currently I'm getting the side menu when tapping on the Button .On choosing a menu, it shows the desired vc but the bottom tab bar is not there which was there before i select menu item. I want to have the bottom tabbar in entire pages also in pages from the side menu. I.'m using SWRevealViewController for burger menu

How can I acheive this? Please help me.

The code I'm using in didSelectRowAtIndexPath is:

if indexPath.row == 1 {
   let vc = storyboard?.instantiateViewController(withIdentifier: "FeedScreenVC") as! FeedScreenVC
   let nav = UINavigationController.init(rootViewController: vc)
       self.revealViewController().pushFrontViewController(nav, animated: true)
}

**Comment by iDevelopper** [comment]
You  have to push your tab bar controller with the correct selected item not the controller.

**Comment by Bilal10Akram** [comment]
@iDevelopper sorry didn't get you. Can you please share in more detail :)

**Comment by iDevelopper** [comment]
Could you upload your project here?

**Comment by Bilal10Akram** [comment]
@iDevelopper 
[cssFeed.zip](https://github.com/John-Lluch/SWRevealViewController/files/1931162/cssFeed.zip)

**Comment by iDevelopper** [comment]
Only the rearVC has been modified to push the tab bar controller instead of a new instantiated controller.

[cssFeed.zip](https://github.com/John-Lluch/SWRevealViewController/files/1932317/cssFeed.zip)
