### ISSUE TITLE
Don't show bar buttom item with tab bar controller 

### ISSUE THREAD

**Issue by AdnanAfsari** [John-Lluch/SWRevealViewController#782]
Hi,
I am trying to implement the slideout menu with tab bar controller but when i add tab bar controller,i can't  see the bar buttom item in the navigation bar. please have a look at the screenshoot.
![screen shot 2018-04-26 at 16 54 52](https://user-images.githubusercontent.com/8613710/39302068-3974d1d4-4973-11e8-8292-86c5d79b1853.png)

**Comment by iDevelopper** [comment]
Can you upload the project?

Otherwise this a sample:

[SWIssue782.zip](https://github.com/John-Lluch/SWRevealViewController/files/1951114/SWIssue782.zip)

**Comment by AdnanAfsari** [comment]
Hi,here is my project.
[MoviesHub.zip](https://github.com/John-Lluch/SWRevealViewController/files/1951815/MoviesHub.zip)

I can't opne your project because its in Xcode version 9.3 and mine is 9.2.

**Comment by iDevelopper** [comment]
Xcode 9.3 does not want to open your project!

**Comment by AdnanAfsari** [comment]
Please have a look in this and update your project like so then upload it again.
[https://stackoverflow.com/questions/49622341/failed-to-load-project-incompatible-project-version-pop-up-appears-when-i-op](url)

**Comment by iDevelopper** [comment]
This link is broken (404)

**Comment by iDevelopper** [comment]
I have changed the deployment target to 10.0. It was 11.3.

[SWIssue782.zip](https://github.com/John-Lluch/SWRevealViewController/files/1952108/SWIssue782.zip)

**Comment by AdnanAfsari** [comment]
hay I fixed the issue.thanks a lot 😃
