### ISSUE TITLE
How to avoid multiple SW RevealController instances

### ISSUE THREAD

**Issue by ghost** [John-Lluch/SWRevealViewController#784]
Hello,

First of all, thanks a lot for the great project - it's an awesome ViewController that saves me tons of time! It's also working super well except in one instance were multiple VC get created. 

Here is my (simplified) set-up and actions leading to the issue:
- I've got 4 VC: One log-in, one SW Reveal (with three panels VC - main/ channel/ friend), and one settings (which is the only one I embedded in a Navigation VC)
- When I instantiate my app through the log-in screen or by directing my app delegate to instantiate straight to SW Reveal (i.e. if user is logged in) it works flawlessly. 
- To log-out I go through the settings menu, present the log-in menu (creating an instance of log in programatically through let main= sb & let loginVC = sb.instantiateVC.
- To re-log-in I use a segue that points to my SWRVC
- That's where the problem comes - instead of re-using the existing instance of the SWRVC it create a separate one and I end up with another main/channel/ friend VC...

I know this is not a bug with SWVC but a lack of understanding of how it's handled in memory + how it should be dismissed/ presented. 

In any case, I would really can you guys shed light to where I go wrong? I can see two culprits: 
- One option is that I have a retain cycles somewhere in the VCs that rely on SWRVC (stoping it from getting dismissed when I segue to Login)
-  The other is that I am doing something wrong with my segue/ present approach (using present to show log-in and segue to go back to the SWVC) with unintended consequences I don't fully get... Btw, I checked and all my VC correctly de-initialize when I close them, incl. the settings one. The only 3 that don't are those handled by the SWVC but my understanding is that it's by intent (I assume SWVC handles its daughter VCs like Navigation Controller does).

Any pointers as to what the issue could be would be super helpful!

Thanks again,
Francois

**Comment by iDevelopper** [comment]
When log out you have to dismiss the reveal view controller (with dismiss:animated or popToRootViewController) depending how you presented it.

Your segue create a new instance of reveal view controller.

SWVC does not handle (unlike UITabBarController) his child VC except the rear/right view controller. The front view controller is always replaced by the new one you have pushed.

You can dismiss RWC but keep the same instance anyway by setting a property, as in this sample:

[SWLoginPushRV.zip](https://github.com/John-Lluch/SWRevealViewController/files/2016009/SWLoginPushRV.zip)

Hope it helps!

**Comment by ghost** [comment]
Thanks a lot Patrick! This was super helpful. I was indeed not dismissing the SWRevealVC and then re-initiating a new instance from my log-in screen... The strange thing is when trying to manual dismiss the SWVC (say from my log-in screen) it returned an unwrapped nil error... Could have it been because my SWVC was my root controller? 

Anyway it now works, so thanks again for the help and the file (which help me see better what I was doing wrong!).
