### ISSUE TITLE
Two-Level Menu

### ISSUE THREAD

**Issue by zaeem-khatib** [John-Lluch/SWRevealViewController#785]
![screen shot 2018-05-19 at 1 22 42 am](https://user-images.githubusercontent.com/38113338/40255027-4bb1301c-5b03-11e8-825f-b4347b1dead2.png)

Is it possible to create a two-level side menu same as the attached image through this library? Or is any other library available for this? Any help would be much appreciated.

**Comment by iDevelopper** [comment]
There is an example in the repo (example 3). You need to have two instances of SW.

**Comment by zaeem-khatib** [comment]
Thanks for the reply. As you know that in example 3, once we select an item from child reveal controller and then close the menu. The next time we open the menu from the front view, we see the child reveal controller as the main rear view of the front view. I want to keep the main rear view the same always regardless of any child rear view item selection. In my case, the rear view with Home, Order and Schedule items will always open from the front view even if previously any item from the child rear view was selected.

**Comment by iDevelopper** [comment]
Do you absolutely want to see the two menus at same time ?

**Comment by zaeem-khatib** [comment]
Yes. But I need to keep the front view same unlike the example 3 in which the front view changes. So basically from the front menu parent rear view will slide out and on selection of any item another child menu will slide out. I need to show a pop up on selection from any item of the child menu, so the front view remains the same. From the front view always the parent rear view will open.

**Comment by iDevelopper** [comment]
You have just to save a reference to the current front view controller before replacing it with child rvc  for coming back to it. And set a proper action for reveal rear view controller instead calling revealToggle of RVC.

I have modified Example 3 for this purpose:

[SWRevealViewController-master 2.zip](https://github.com/John-Lluch/SWRevealViewController/files/2020139/SWRevealViewController-master.2.zip)

**Comment by zaeem-khatib** [comment]
Looks like this might do the trick. Thanks a lot!
