### ISSUE TITLE
SideBar opens every time on double click not on first click?

### ISSUE THREAD

**Issue by parthbarot** [John-Lluch/SWRevealViewController#787]
When I Click on the button on first time sidebar doesn't opens but when I again click on the button it opens. Why is that issue?

This is my code to open sidebar.

@IBAction func btnMenubarClicked(_ sender: Any) {
        if revealViewController() != nil {
            btnMenubar.addTarget(revealViewController(), action: #selector(SWRevealViewController.revealToggle(_:)), for: .touchUpInside)
            self.revealViewController()?.rearViewRevealWidth = 300
           view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
        }
    }

**Comment by iDevelopper** [comment]
This part of code must be written in viewDidLoad function of your front view controller:
```
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.btnMenuBar.addTarget(revealViewController(), action: #selector(SWRevealViewController.revealToggle(_:)), for: .touchUpInside)
        self.revealViewController().panGestureRecognizer()
        self.revealViewController().tapGestureRecognizer()

        self.revealViewController().rearViewRevealWidth = 300
    }
```
And remove the IBAction!

In your case, the first time you tap the button, btnMenubarClicked(_ :) is invoked and you just set the target/action, nothing else.
The second time, the target/action you have set is invoked but not yours.

**Comment by parthbarot** [comment]
Hello,
          You were right now the issue is solved in each and every view
controller. Thank you very much for the help.
Thank You,
Parth Barot.
