### ISSUE TITLE
nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by maximegheraille** [John-Lluch/SWRevealViewController#792]
hi, 

after looking at a lot of people with the same problem I cannot find a solution.

so I can open the menu and click on the "nouveautes" that works fine but the 2 other menu items give me the error : " nil while unwrapping an Optional value"

 this is the part where I get the bug:

    override func viewDidLoad() {
        super.viewDidLoad()
        if (self.revealViewController() != nil)
        {
            
            menuButton.target = self.revealViewController()
            menuButton.action = #selector(SWRevealViewController.revealToggle(_:)) //here is the error
            self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
          
        }

<img width="904" alt="screenshot 2018-07-05 at 13 07 16" src="https://user-images.githubusercontent.com/32335849/42320086-5f8c0cf8-8054-11e8-820d-e8c178a8e526.png">

**Comment by iDevelopper** [comment]
In which view controller are you in your sample code?

Are you sure the crash is exactly on this line?

**Comment by maximegheraille** [comment]
it's good I found a tutorial on yt and its works fine now :)

for the people having this problem watch this and it will work ! 
https://www.youtube.com/watch?v=DCbB2cuJzOE&t=777s
