### ISSUE TITLE
nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by maximegheraille** [John-Lluch/SWRevealViewController#793]
hi,

everything was working fine and then this error appeared again

I would like to know how to fix it and know what it is 

all my view do have differents files for the class but they are all the same code apart from the webview that is extra in that view

here are some screenshots of my project
<img width="1109" alt="screenshot 2018-07-05 at 20 08 31" src="https://user-images.githubusercontent.com/32335849/42340096-61bbbab0-808f-11e8-92f7-56af8cf45d6c.png">
<img width="1109" alt="screenshot 2018-07-05 at 20 06 31" src="https://user-images.githubusercontent.com/32335849/42340097-61de0c78-808f-11e8-9e8a-7ed06777eb2f.png">
<img width="1109" alt="screenshot 2018-07-05 at 20 06 25" src="https://user-images.githubusercontent.com/32335849/42340098-61fc384c-808f-11e8-9c9d-34514461bac6.png">
<img width="1109" alt="screenshot 2018-07-05 at 20 06 13" src="https://user-images.githubusercontent.com/32335849/42340099-621abcae-808f-11e8-8432-90de3f46e6b8.png">
<img width="904" alt="screenshot 2018-07-05 at 20 05 41" src="https://user-images.githubusercontent.com/32335849/42340101-623c3064-808f-11e8-8118-9cdc624b9fe9.png">

**Comment by iDevelopper** [comment]
Ok, your menuBarButton is surely nil. Check the connection with storyboard.

**Comment by maximegheraille** [comment]
im might be stupud but cannot find it ,

here are all my connections: 

<img width="1109" alt="screenshot 2018-07-05 at 21 02 58" src="https://user-images.githubusercontent.com/32335849/42342652-0842ddda-8097-11e8-8c95-ea45b43dfb39.png">
<img width="1109" alt="screenshot 2018-07-05 at 21 03 05" src="https://user-images.githubusercontent.com/32335849/42342645-fe7898e4-8096-11e8-96de-d89a413e6832.png">
<img width="1109" alt="screenshot 2018-07-05 at 21 03 12" src="https://user-images.githubusercontent.com/32335849/42342654-088477d6-8097-11e8-8bf4-05144ea1a9db.png">
<img width="1158" alt="screenshot 2018-07-05 at 21 03 21" src="https://user-images.githubusercontent.com/32335849/42342655-08a98260-8097-11e8-89c5-a7f196b7c270.png">
<img width="1158" alt="screenshot 2018-07-05 at 21 03 28" src="https://user-images.githubusercontent.com/32335849/42342656-08ccaf1a-8097-11e8-9d3c-c913b3f42b52.png">
<img width="1158" alt="screenshot 2018-07-05 at 21 03 34" src="https://user-images.githubusercontent.com/32335849/42342658-08ede75c-8097-11e8-9725-0b16e4425da1.png">
<img width="1158" alt="screenshot 2018-07-05 at 21 03 41" src="https://user-images.githubusercontent.com/32335849/42342659-0910fe9a-8097-11e8-98bc-809382fc9a29.png">
<img width="1158" alt="screenshot 2018-07-05 at 21 03 48" src="https://user-images.githubusercontent.com/32335849/42342660-093caae0-8097-11e8-8ecb-97163b989bca.png">

**Comment by iDevelopper** [comment]
In the fourth screenshot (PlayListViewController) you can see that menuBarButton is not connected. So click on the + button and drag it to Menu item on the view.

**Comment by maximegheraille** [comment]
it worked , thx a lot !
