### ISSUE TITLE
Menu button not working because of segue

### ISSUE THREAD

**Issue by yagubshukurov** [John-Lluch/SWRevealViewController#794]
Hi, I have researched in your answers, but could not find exact answer for this case. Can you look at this issue? I have view controller that was directed from side menu table and when I perform segue to back to the tab bar, menu button and gesture are disabled.  I use "selectedIndex" when I click on the button on view controller "A", but when I get to "B" side menu is disabled, because of TabBarViewController. This project is in Swift 4

<img width="512" alt="asaaaaa" src="https://user-images.githubusercontent.com/25871364/42420551-73e441da-82d8-11e8-9d8b-84c74ddf5829.png">

Kind regards

**Comment by iDevelopper** [comment]
I don't know what type of segue you perform to show the tab bar view controller, but I should replace the front view controller of SWRevealViewController instead.

```
tabBarController.selectedIndex = ...
self.revealViewController()?.setFront(tabBarController, animated: true)
```

**Comment by yagubshukurov** [comment]
to show TabBarViewController I use SWRevealViewControllerSegueSetController. Sorry, I do not understand what I can use instead of SWRevealViewController as front? 

When I perform segue to SWRevealViewController, I cannot include code tabBarController.selectedIndex which is very important for me. Otherwise I perform segue from a View Controller to TabBarViewController, then menu is not working.

Kind regards

**Comment by iDevelopper** [comment]
You can override performSegue in a subclass of SWRevealViewController:

```
class RevealViewController: SWRevealViewController, SWRevealViewControllerDelegate {
    
    override func performSegue(withIdentifier identifier: String, sender: Any?) {
        super.performSegue(withIdentifier: identifier, sender: sender)
        if identifier == "sw_front" {
            let tabBarVC = self.frontViewController as! UITabBarController
            tabBarVC.selectedIndex = 1
        }
    }
...
```

**Comment by yagubshukurov** [comment]
Thank you very much!
