### ISSUE TITLE
Move back to Home View, which is Front view of SWRevealController, on successful sign up.

### ISSUE THREAD

**Issue by kunaltyagi26** [John-Lluch/SWRevealViewController#799]
Hi,

Below is my storyboard:

<img width="905" alt="screen shot 2018-08-01 at 12 59 47 pm" src="https://user-images.githubusercontent.com/28871881/43507595-2dda58da-958b-11e8-8b25-136cb54a845e.png">

On successful signup on RegisterVC, the current view should be moved to MapVC which is the front view of SWRevealController. Whenever I try to present that view, it shows me with the error "Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value". Can you please let me know, how can this be achieved.

Thanks.

**Comment by iDevelopper** [comment]
Need some part of code. How do you present your MapVC?

**Comment by kunaltyagi26** [comment]
Inside the function of clicking sign up button, I tried the following things:

1. `guard let mapVC = storyboard.instantiateViewController(withIdentifier: mapVC) as MapVC else { return }`
`present(mapVC , animated: true, completion: nil)`

But here, it have me error Unexpectedly found nil while unwrapping an Optional value, though I have already set identifier in storyboard for MapVC.

2. `self.revealViewController().pushFrontViewController(self.revealViewController().frontViewController, animated: true)`
`self.revealViewController().setFrontViewPosition(.left, animated: true)`

This is also not working for me.

Can you please let me know where am I going wrong, or is there any other way by which I can achieve this.

**Comment by iDevelopper** [comment]
1. In mapVC revealViewController is nil because you did not use it to present mapVC.

2. Try this:
```
        guard let mapVC = storyboard.instantiateViewController(withIdentifier: mapVC) as MapVC else { return }
        revealViewController().setFront(mapVC, animated: true)
```

**Comment by kunaltyagi26** [comment]
Tried the above piece of code, still getting the same error.

<img width="730" alt="screen shot 2018-08-02 at 11 47 25 am" src="https://user-images.githubusercontent.com/28871881/43565964-68c06998-964a-11e8-945a-55a211c1e004.png">

I am not able to understand where I am going wrong.

**Comment by iDevelopper** [comment]
How do you present loginVC? It should be presented with SWRevealViewController too. In fact loginVC should be the front view controller at the beginning... Not the mapVC.

**Comment by kunaltyagi26** [comment]
MapVC and SidePanelVC are assigned as the front view and rear view respectively for SWRevealController. Inside SidePanelVC, on clicking Sign Up/ Login button, I used the following code to present LoginVC:

```
if Auth.auth().currentUser == nil {
            guard let loginVC = storyboard?.instantiateViewController(withIdentifier: "loginVC") as? LoginVC else { return }
            present(loginVC, animated: true, completion: nil)
        }
```

**Comment by iDevelopper** [comment]
So:
```
if Auth.auth().currentUser == nil {
            guard let loginVC = storyboard?.instantiateViewController(withIdentifier: "loginVC") as? LoginVC else { return }
            revealViewController().setFront(loginVC, animated: true)
 }
```

**Comment by kunaltyagi26** [comment]
Hey man, thnx, it worked. For presenting as well as dismissing the view, I used setFront function only. Just one more point I need to ask, do I need to remove the former view from somewhere before setting the new view using setFront()?

**Comment by iDevelopper** [comment]
Great!

> do I need to remove the former view from somewhere before setting the new view using setFront()?

 No. This is done automatically by the library (removeFromParentViewController).

**Comment by kunaltyagi26** [comment]
Hey man, thnx a lot for ur help...closing this issue.

**Comment by ghost** [comment]
Follow setups i get solution

import SWRevealViewController

let appDelegate = UIApplication.shared.delegate as! AppDelegate

//call viewcontroller 
let storybaord = UIStoryboard(name: "Main", bundle: nil)
let descVC = st.instantiateViewController(withIdentifier: "HomeVC") as? HomeVC
let navVC = UINavigationController(rootViewController: descVC !)
let SideMenuVC = st.instantiateViewController(withIdentifier: "SideMenuVC") as? SideMenuVC
let mainRevealController = SWRevealViewController()
mainRevealController.rearViewController = SideMenuVC
mainRevealController.frontViewController = navVC 
appDelegate.window?.rootViewController = mainRevealController
