### ISSUE TITLE
can't open viewController programmatically 

### ISSUE THREAD

**Issue by eburnay** [John-Lluch/SWRevealViewController#80]
Hello

I'm using storyboard in my app but i want to manage the left menu programmatically.
I'm trying to setFrontViewController like this.

MapViewController *frontViewController = [[MapViewController alloc] init];
            UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:frontViewController];
            [revealController setFrontViewController:navigationController animated:YES];

I'm using the didSelectRowAtIndexPath in the table view controller.

When I click in the menu item it doesn't open the MapViewController, only a black screen.

Thankyou

**Comment by VLEIX** [comment]
works fine!! :D
