### ISSUE TITLE
Is it possible set delegate in rear view controller?

### ISSUE THREAD

**Issue by hungwei0331** [John-Lluch/SWRevealViewController#807]
As title, I would like to set protocol in rear vc,

update something to my front vc when rear vc did some action,

I had try notificationCenter, but it cost a lot,

does there have a better way to solve it, 

thanks in advance for any comment.

**Comment by iDevelopper** [comment]
I do not see what could be the problem. What did you try about this protocol?

**Comment by hungwei0331** [comment]
Sorry, I didn't specific my problem,

I had a front vc, I would like to push vc by front vc after right vc when pressed, 
(cause I need back button so I have to)

so I set the protocol in the right vc , that make front vc to know when the row pressed,

but I have no idea how could write that "optionVC.delegate = self" in front vc,

please check the image below, thank you Patrick.

![simulator screen shot - iphone se - 2019-02-06 at 23 00 05](https://user-images.githubusercontent.com/10335229/52350916-89e39380-2a64-11e9-859b-9336c1eb41d2.png)

![screen shot 2019-02-06 at 11 05 15 pm](https://user-images.githubusercontent.com/10335229/52350940-9a940980-2a64-11e9-82c1-7999e57d5f6e.png)

**Comment by iDevelopper** [comment]
Oups, if I understand you are using the rearViewController of SW for your main VC? Why?

**Comment by hungwei0331** [comment]
my main vc called homePageVC, optionVC is my rightVC

**Comment by iDevelopper** [comment]
Ok, why do you want a protocol to do that? In your rightViewController, when Search is selected for example, retrieve the front view controller (i.e. revealViewController.frontViewController). It is a navigation controller as I can see. Use this navigation controller (the navigation controller of your actual front view controller) to push another view controller (and close the right menu).

**Comment by iDevelopper** [comment]
You will have a back button on the navigation controller.

**Comment by hungwei0331** [comment]
I had write down the code below,

but seems like I couldn't have back button,

dose there anything I missed, thank you so much

![screen shot 2019-02-07 at 6 22 43 pm](https://user-images.githubusercontent.com/10335229/52405120-8eac5400-2b05-11e9-93bd-cf90987d5000.png)

![app](https://user-images.githubusercontent.com/10335229/52405146-9c61d980-2b05-11e9-83f2-c2f8e54f3f03.gif)

**Comment by iDevelopper** [comment]
didSelectRow at indexPath:

Syntax not checked:

// Retrieve the front view controller
let nc = self.revealViewController().frontViewController as! UINavigationController
// Push your searchViewController with the nc. Don't push with SW!
nc.pushViewController(searchViewController, animated: true)
// Hide the right menu
self.revealViewController().rightRevealToggle(animated: true)

**Comment by hungwei0331** [comment]
OMG, it works, 
thank you Patrick,
you save my world,  : D

**Comment by iDevelopper** [comment]
Glad to hear that!

If you want a maintained framework:

https://github.com/iDevelopper/PBRevealViewController

**Comment by hungwei0331** [comment]
Yes, its my pleasure
