### ISSUE TITLE
Black Screen when i compile with IOS 13.1, in oldest version works fine

### ISSUE THREAD

**Issue by djerick1989** [John-Lluch/SWRevealViewController#817]
I am stuck my application doesn´t work with IOS 13.1, immediately start with launchscreen and after that show a black screen, because the SWRevealViewController load empty, with oldest versions works fine if i compile the application with IOS 12.4 but my application in testflight doesn´t work with IOS 13.1.

**Comment by djerick1989** [comment]
I could resolve my problem, it was in the storyboard. only i remove the searchDisplayController references.

```
<searchDisplayController id="pWz-So-g6H">
  <connections>
  <outlet property="delegate" destination="Yci-sd-Mof" id="fjs-ah-jLs"/>
  <outlet property="searchContentsController" destination="Yci-sd-Mof" id="gQN-1r-gti"/>
  <outlet property="searchResultsDataSource" destination="Yci-sd-Mof" id="2Jf-lh-Ute"/>
  <outlet property="searchResultsDelegate" destination="Yci-sd-Mof" id="Hap-SA-f02"/>
  </connections>
  </searchDisplayController>
```

**Comment by Ucdemir** [comment]
what is "searchDisplayController "??

**Comment by faizantariq1** [comment]
@djerick1989  same happening but didn't find any searchDisplayController in my storyboard or anywhere in the project.
