### ISSUE TITLE
iOS 13 new modal presentation style

### ISSUE THREAD

**Issue by tachang** [John-Lluch/SWRevealViewController#819]
Might help anyone else but I had to do:
  
self = [super initWithRearViewController:sidebarViewController frontViewController:mainController];
self.modalPresentationStyle = UIModalPresentationFullScreen;

to get it to go fullscreen.

**Comment by mobileonekh** [comment]
hello, where to add this code? I am facing issue of viewdidappear is not called in ios13

**Comment by iDevelopper** [comment]
What is the question / problem?
