### ISSUE TITLE
viewDidLoad called everytime!

### ISSUE THREAD

**Issue by zerbfra** [John-Lluch/SWRevealViewController#82]
hello - i noticed that when i go back to the front view, it is called every time viewDidLoad. 
Can I specify to load the view with viewWillAppear? 

I think viewDidLoad is best to be called only once!

**Comment by saad352** [comment]
Hi John,
I am facing this same issue i.e. viewDidLoad is called every time view appears. I have read the whole issue and quite understood what you are saying but I dowloaded your sample app and all of the samples are showing this behavior. ViewDidLoad is called everytime. I have logged by using NSLog in viewDidLoad and it is called again and again when view appears. Can you please look in to this issue. 
Thanks

**Comment by iDevelopper** [comment]
Hi,

This is not an issue. Simply, the sample create a new instance of the front view controller each time an item of the rear menu is selected. Keep a reference of your's controllers in some properties, and use them to push them.

**Comment by saad352** [comment]
Oh i thought this thing was done by the class itself. 
Thanks for mentioning that @iDevelopper . Btw can't this thing be implemented in this class just to make things a little bit easier or is there a downside to this? Just curious

**Comment by iDevelopper** [comment]
It is easy, see a sample I have wrote (in MenuTableViewController class, the two maps are saved in properties):

[MapSample.zip](https://github.com/John-Lluch/SWRevealViewController/files/365961/MapSample.zip)

**Comment by saad352** [comment]
Thanks a lot @iDevelopper .. But I had figured it out already. :)

**Comment by iDevelopper** [comment]
What do you mean?

**Comment by saad352** [comment]
I said i understood what you said in comment earlier and there was no need of sample project you provided. Anyways Thanks for helping.

**Comment by iDevelopper** [comment]
Ok !

I also wrote this:
https://github.com/iDevelopper/PBRevealViewController
