### ISSUE TITLE
Set width of the view

### ISSUE THREAD

**Issue by shmidt** [John-Lluch/SWRevealViewController#87]
Is it possible to change width of the view?
For ex.: if there is checkmark or detail accessory in menu, it will be hidden when it reveals.

**Comment by Salvo2689** [comment]
I'm sorry , to me a strange thing happens .

I do not understand your code , but I put this to the left menu with viewMenuLaterale.rearViewRevealDisplacement = 200 .

 override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)

```
    print(self.view.frame)
    print(self.view.frame.origin)


    var frame:CGRect = self.view.frame
    frame.origin.x = 0
    if (UIInterfaceOrientationIsLandscape(self.interfaceOrientation)) {
        print("1")
        frame.size.width = UIScreen.mainScreen().bounds.size.height - 60
    } else if (UIInterfaceOrientationIsPortrait(self.interfaceOrientation)) {
        frame.size.width = UIScreen.mainScreen().bounds.size.width - 165
        print("2")
    }

    self.view.frame = frame
    print(self.view.frame)
}
```

This phenomena for the right menuLaterale_Dx ! .rightViewRevealWidth = 150 .

  override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)

```
    print(self.view.frame)
    print(self.view.frame.origin)


    var frame:CGRect = self.view.frame
    frame.origin.x = 60
    if (UIInterfaceOrientationIsLandscape(self.interfaceOrientation)) {
        print("1")
        frame.size.width = UIScreen.mainScreen().bounds.size.height - 60
    } else if (UIInterfaceOrientationIsPortrait(self.interfaceOrientation)) {
        frame.size.width = UIScreen.mainScreen().bounds.size.width - 60
        print("2")
    }

    self.view.frame = frame
    print(self.view.frame)
}
```

Watch what happens

![menu](https://cloud.githubusercontent.com/assets/10288095/8578267/0a2e4eb4-25ae-11e5-9431-fe513f6f58e6.gif)

I explain the code to change according to the size of my menu , menu or other future ? thanks

**Comment by Salvo2689** [comment]
and if you can tell me how to add an action. If I active action to the side menu ( realRevealToggle , or rightRevealToggle ) would give effect to the view frotn
