### ISSUE TITLE
How to disable user interaction when reveal view is shown?

### ISSUE THREAD

**Issue by alextor** [John-Lluch/SWRevealViewController#92]
I want to disable interaction with front view when left or right views are revealed. How to do this ?

**Comment by williamnoto** [comment]
Thanks @adamdehaven, that really helped me.

**Comment by lobotommy** [comment]
Any tips on doing this with Swift? 
My current (unsuccessfulI) attempt looks like this: 

<pre>code class ProductTableViewController: UITableViewController, SWRevealViewControllerDelegate</pre>

in viewDidLoad(): 
<pre>self.revealViewController().delegate = self</pre>

And the attempt at implementing a delegate method looks like this: 
<pre>func willMoveToPosition(revealController: SWRevealViewController!, 
willMoveToPosition: FrontViewPosition) {
        ...
    }</pre>

Any tips would be greatly appreciated

**Comment by lobotommy** [comment]
Thanks @adamdehaven , helped me as well.

### Swift-ified: 
<pre>    func revealController(revealController: SWRevealViewController!,  willMoveToPosition position: FrontViewPosition){
        if(position == FrontViewPosition.Left) {
            // self.view.userInteractionEnabled = true
            sidebarMenuOpen = false
        } else {
            // self.view.userInteractionEnabled = false
            sidebarMenuOpen = true
        }
    }
    
    func revealController(revealController: SWRevealViewController!,  didMoveToPosition position: FrontViewPosition){
        if(position == FrontViewPosition.Left) {
            // self.view.userInteractionEnabled = true
            sidebarMenuOpen = false
        } else {
            // self.view.userInteractionEnabled = false
            sidebarMenuOpen = true
        }
    }
    
    override func tableView(tableView: UITableView, willSelectRowAtIndexPath indexPath: NSIndexPath) -> NSIndexPath? {
        if(sidebarMenuOpen == true){
            return nil
        } else {
            return indexPath
        }
    }</pre>

Also implemented the *SWRevealViewControllerDelegate*, as well as <pre>self.revealViewController().delegate = self</pre> in the *viewDidLoad* method.

**Comment by MVakas** [comment]
That Swift-ified version worked for me as I’m working in Swift.

**Comment by Surya61995** [comment]
https://github.com/Surya61995
https://github.com/MVaka
https://github.com/MVaka
https://github.com/Surya61995ss

**Comment by iDevelopper** [comment]
What are these links? 404 for all...

**Comment by iDevelopper** [comment]
https://github.com/iDevelopper/PBRevealViewController

**Comment by Surya61995** [comment]
https://github.com/dekatotoro/SlideMenuControllerSwift 
Refer above good bettter than this -> https://github.com/iDevelopper/PBRevealViewController

**Comment by Surya61995** [comment]
https://github.com/iDevelopper - refer Above

**Comment by xsada** [comment]
Thanks for Swift-ified version. It worked for me, too.

**Comment by iDevelopper** [comment]
As @John-Lluch wrote, the simplest way is:

[SWSwiftSample.zip](https://github.com/John-Lluch/SWRevealViewController/files/542019/SWSwiftSample.zip)

**Comment by rnf-imran** [comment]
[self.view addGestureRecognizer:revealViewController.tapGestureRecognizer];

**Comment by iDevelopper** [comment]
No, you don't need to add the gesture recognizers to your view yourself. Just call the SWRevealViewController's methods in your first front view controller:

Swift:
```
        revealViewController().tapGestureRecognizer()
        revealViewController().panGestureRecognizer()
``` 
Objective-C
``` 
        [self.revealViewController tapGestureRecognizer];
        [self.revealViewController panGestureRecognizer];
```

**Comment by nathanmrtns** [comment]
The fastest way (that worked for me) to do if the side menu is a table view is to add the delegate methods in the MenuViewController.swift:

`override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath){
self.revealViewController().rearViewController.view.isUserInteractionEnabled = false
}`

and run `self.revealViewController().rearViewController.view.isUserInteractionEnabled = true` when it appears
